### PR TITLE
PA US322: HighSt +-> PotPk

### PR DESCRIPTION
**Pull request by yakra**
http://tm.teresco.org/forum/index.php?topic=2101

### CODE REVIEW

**Comment by yakra** [comment]
@rickmastfan67, do you have any pending edits in PA that might conflict? I'll leave it to you to reopen this PR.

**Comment by rickmastfan67** [comment]
Nope.

**Comment by yakra** [comment]
Nothing conflicting -- Shall I reopen the PR, then?

**Comment by jteresco** [comment]
I see no reason not to do so. I'll reopen and merge.

**Pull request merged**
