### PR TITLE
AR deletions & relocations

### PR DESCRIPTION
**Pull request by yakra**
I have one more quick update to add to this that I'd like to have in tonight's update. I'll get it in ASAP; just wanted to put this in your radar before the update happens.

### CODE REVIEW

**Comment by yakra** [comment]
Wrong route number in updates entry; will force push.

**Comment by yakra** [comment]
New commit still forthcoming. Still need to:
* Finish editing (almost done, just need the updates entries)
* Errorcheck locally (maybe 5-8 mins? Disk not cached.)
* Push

**Comment by yakra** [comment]
Ready to rock!

**Comment by jteresco** [comment]
go!

**Comment by yakra** [comment]
Those comments were posted milliseconds apart! :grinning:

**Pull request merged**
