### PR TITLE
NL & TX in-dev edits

### PR DESCRIPTION
**Pull request by yakra**
no update texts, as these systems are in-dev.

### CODE REVIEW

**Comment by ovoss** [comment]
A global question, unrelated to NL2: Should those of us maintaining other 
provinces be updating their Canada Select Provincial Highways and Canada 
Select Named Freeways routes? My inclination, for BC, SK, and QC, would be 
to leave their updates (I know of some in SK, at least) for whoever ends up 
taking on those unassigned provincial route sets, which might not be me.

--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages (NEW ADDRESS):
http://www.alaskaroads.com/home.html

**Comment by si404** [comment]
Oscar, I would say that, while you are under no obligation to, it would be nice to do what you can there, so that if you do hand it over, someone else gets routes that are up-to-date.

**Comment by yakra** [comment]
Agreed. It'd be nice, but needn't be mandatory or even compulsory.

**Comment by yakra** [comment]
Derp. I meant, "or even a priority."

**Comment by ovoss** [comment]
"It'd be nice" isn't enough for me. There are two in-dev systems on my plate 
already (a limit I'd stick to, especially since one of them is the large 
California state route set), not to mention other things both TM and 
otherwise, to keep me busy and out of trouble for awhile.

Oscar

----- Original Message -----

**Comment by yakra** [comment]
With the system all but officially mothballed, I also see no problem with letting the routes sit & gather dust till someone's ready to take them on as part of a full provincial set.

**Pull request merged**
