### PR TITLE
Uruguay: add 11Jos

### PR DESCRIPTION
**Pull request by neroute2**
https://forum.travelmapping.net/index.php?topic=6092.0

### CODE REVIEW

**Comment by michihdeu** [comment]
@neroute2 you missed the update.csv entry.

**Comment by neroute2** [comment]
> @neroute2 you missed the update.csv entry.

I didn't realize that was necessary if existing routes weren't being modified (more than the addition of new points).

**Comment by rickmastfan67** [comment]
> > @neroute2 you missed the update.csv entry.
> 
> I didn't realize that was necessary if existing routes weren't being modified (more than the addition of new points).

100% necessary if it's an addition to an already active highway system on the site.  Only if the system is in 'preview' or 'development', is it not required.

**Comment by michihdeu** [comment]
> > @neroute2 you missed the update.csv entry.
> 
> I didn't realize that was necessary if existing routes weren't being modified (more than the addition of new points).

https://travelmapping.net/devel/manual/maintenance.php#newroute

**Pull request merged**
