### PR TITLE
LA: Laissez les bonnes routes rouler

### PR DESCRIPTION
**Pull request by mapcat**
usala preview -> active
Delete MI 137

### CODE REVIEW

**Comment by mapcat** [comment]
Data check was successful

**Comment by jteresco** [comment]
Note to myself when I pull this in tonight or to @mapcat before: Still need a systemupdates.csv entry?

**Comment by mapcat** [comment]
Sorry--fixed now.

**Comment by jteresco** [comment]
Thanks for adding that.

**Pull request merged**
