### PR TITLE
usafl: forum fixes

### PR DESCRIPTION
**Pull request by rickmastfan67**
http://forum.travelmapping.net/index.php?topic=323.msg18002#msg18002
&
http://forum.travelmapping.net/index.php?topic=3462.0

### CODE REVIEW

**Comment by yakra** [comment]
StJohRivFry -> SJRivFry, [etc.](http://travelmapping.net/devel/manual/wayptlabels.php#truncate)
NavStaMayG5 similarly has too many words
AlaBoatRamp -> FLA1A_U

**Comment by jteresco** [comment]
Don't forget to run datacheck.

<pre>
ABORTING due to 1 errors:
1: System mismatch parsing line [usafl;FL;PoiPkwy;;;Poinciana Parkway;fl.poipkwy;], expected usasf
</pre>

I'll fix this one and re-run the site update.

**Comment by rickmastfan67** [comment]
My bad. Got it right in the '_con' file but messed up in the other.  That's what I get for being stir crazy because of this Covid-19 stuff.

**Comment by rickmastfan67** [comment]
@yakra See my post in the usafl thread about those.

**Pull request merged**
