### PR TITLE
do what I can with a brief window on a PC.

### PR DESCRIPTION
**Pull request by si404**
This needs checking - saying 210 files changed, though most aren't my changes. It seems like its calling all the changes that I pulled from TM/master to my fork as changes, but hopefully I'm not actually changing them

### CODE REVIEW

**Comment by si404** [comment]
There weren't any conflicts when I made the pull request. That must have been due to pulling in another request first.

What I'm more worried about is undoing changes previously made. I don't think it's the case, but...

**Comment by yakra** [comment]
Was e94541d84e8546c90a29df9b85fbb356696fa154 a squash&merge commit?
Anyway...
tur.ah005.wpt has had additional commits, d07efabad6570e3b6e3af555f2ec8370a674c1a7 & 484eaef855a7f5b68852a29551c9ba9e574a161f
Based on the changes I see in there, it looks like  line 174 should be `Kay_W` rather than `Kay`.

**Comment by si404** [comment]
Thanks Eric, it was squash and merge, which explains the problem.

**Comment by yakra** [comment]
Shall I have a go at [resolving conflicts](https://github.com/TravelMapping/HighwayData/pull/2903/conflicts)?

**Comment by si404** [comment]
Yes please!

**Comment by yakra** [comment]
Done.
Hm. So apparently I had permission to make [that commit](https://github.com/si404/HighwayData/commit/153ef36f41b5c3811f86a5ea62806eca4220ae49) to [si404:master](https://github.com/si404/HighwayData)?
I would think that I shouldn't be allowed to do that...

**Pull request merged**
