### PR TITLE
POL + ITA

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by michihdeu** [comment]
@si404 I don't know if I was the only traveler but do generally suggest the subsequent changes:
`2024-08-20;Poland;DW680 (Ostrowek);;Route deleted` -->
`2024-08-20;Poland;DW680 (Ostrowek);pol.dw799;Route deleted (DW799 now)`

hwy_data/POL/poldw/pol.dw799.wpt:
Wis http://www.openstreetmap.org/?lat=51.989766&lon=21.243289 ->
Wis +DW680 http://www.openstreetmap.org/?lat=51.989766&lon=21.243289

I think that the E45Cag change needs an update entry (one traveler).

Thank you!

**Comment by si404** [comment]
Done the Polish change. I don't think the E25 warrants an update entry as it's merely moving a point to the correct location a short distance away

**Comment by michihdeu** [comment]
@si404 about SS roads:
- SS389DirUdd and SS389 wps needs to be synced (in ITA directory, didn't check ITA-SAR)
- E25Cag + SS554 concurrency broken
- Please check SS729's west end. It on concurrency with SS597 now but OSM, GM and [April 2024 GSV](https://maps.app.goo.gl/XzMLZZce1ERCdsAd8) indicate it on the direct route to SS131 which is not covered by any SS road now.

I didn't check _all_ changes though.

**Comment by michihdeu** [comment]
Well, I still had mapview opened.... There is a concurrency issue at https://travelmapping.net/hb/showroute.php?r=ita.ss389&lat=40.797811&lon=9.280851&zoom=15 SS389 meets SS597 but there are also SS729 and E840. Not sure if SS597 should exist at all here.

**Comment by si404** [comment]
Can you put these on the forum. Not least as I don't believe I am meant to be the person dealing with itass (I certainly don't want to be as it=ass) and shouldn't really have done what I did.

If you are twiddling your thumbs, perhaps you could sort out Sardinia?

**Comment by michihdeu** [comment]
I thought you will fix want you've just introduced when fixing what I reported for [Sardinia](https://forum.travelmapping.net/index.php?topic=2095.msg35346#msg35346) and [Sicily](https://forum.travelmapping.net/index.php?topic=2095.msg35352#msg35352). @rmihailucian could you deal with my ITA comments above? Maybe this month? If not, of course I _could_ since a want a clean system when visiting the islands in September......................................................................................................................................................................................................................... btw, we hope that we can split Italy into regions _soon_... @yakra is currently working on some magic behind the scenes...

**Comment by rmihailucian** [comment]
@michihdeu I will see what I can do, but I cannot guarantee that I can find time in August, as I expect a lot of things to do at my work, and on 31st of August I will also go on holiday for 2 weeeks on Sardinia :) What are your plans? Maybe we could meet there for a few hours?

**Comment by michihdeu** [comment]
I'll copy my points over to the forum.

**Pull request merged**
