### PR TITLE
datacheck

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by yakra** [comment]
marking ita.a018sir;SP26;;;VISIBLE_HIDDEN_COLOC;ita.e45cat@+X242320 as an FP?
I think I wanna look into that a bit and form an opinion...

**Comment by si404** [comment]
The A18 ends, with the E45 taking what are sliproads (of what will be a trumpet interchange), but there is no de facto junction there.

**Comment by yakra** [comment]
Aah, gotcha. A little bit similar to I-22, then.

**Comment by jteresco** [comment]
Removing idn.ah002 entry from asiah.csv, no corresponding wpt file.

**Comment by jteresco** [comment]
Also from asiah_con.csv

**Pull request merged**
