### PR TITLE
DEU split / QC update entry

### PR DESCRIPTION
**Pull request by michihdeu**

### CODE REVIEW

**Comment by michihdeu** [comment]
@jteresco, I think it should work. Minimum, I don't see any conflict with the production files. deubystc, deuhelc and deunwlc are copies only, deuac, eursfc and eurec routes have been split.

Please put the "railway systems" on tmtest. Thanks!

If it works, is it possible to get graphs of these regions to check concurrencies?

deub (Bundesstraßen is still missing. It comprises 647 routes before being split...

**Comment by jteresco** [comment]
Graphs will get created for all regions anyway.  Do you want any system graphs?

**Comment by jteresco** [comment]
I realize what you were asking is to have graphs include these devel systems.  That would be harder, so I can't do it tonight at least.  I can look into how hard it would be to build some.

**Comment by jteresco** [comment]
Here are the errors encountered on an attempt to populate the TravelMappingTest DB based on railsystems:

`ABORTING due to 84 errors:
1: Could not find Route matching root espri.a013		 in system espab.
2: No roots in _con.csv line [espab;A13;;;espri.a013		]
3: Could not find Route matching root espcl.bu011		 in system espab.
4: No roots in _con.csv line [espab;BU11;;;espcl.bu011		]
5: Could not find Route matching root espmc.rm001		 in system espab.
6: No roots in _con.csv line [espab;RM1;;;espmc.rm001		]
7: Could not find Route matching root espmc.rm002		 in system espab.
8: No roots in _con.csv line [espab;RM2;;;espmc.rm002		]
9: Could not find Route matching root espmc.rm003		 in system espab.
10: No roots in _con.csv line [espab;RM3;;;espmc.rm003		]
11: Could not find Route matching root espmc.rm016		 in system espab.
12: No roots in _con.csv line [espab;RM16;;;espmc.rm016		]
13: Could not find Route matching root espmc.rm017		 in system espab.
14: No roots in _con.csv line [espab;RM17;;;espmc.rm017		]
15: Duplicate root in route lists: deunw.l084
16: Duplicate root in route lists: deunw.l124
17: Duplicate root in route lists: deunw.l150
18: Duplicate root in route lists: deunw.l232
19: Duplicate root in route lists: deunw.l260
20: Duplicate root in route lists: deunw.l705
21: Duplicate root in con_route lists: deunw.l084
22: Duplicate root in con_route lists: deunw.l124
23: Duplicate root in con_route lists: deunw.l150
24: Duplicate root in con_route lists: deunw.l232
25: Duplicate root in con_route lists: deunw.l260
26: Duplicate root in con_route lists: deunw.l705
27: Check FAILED: 2535 routes != 2528 connected route roots.
28: route espri.a013 not matched by any connected route root.
29: route espcl.bu011 not matched by any connected route root.
30: route espmc.rm001 not matched by any connected route root.
31: route espmc.rm002 not matched by any connected route root.
32: route espmc.rm003 not matched by any connected route root.
33: route espmc.rm016 not matched by any connected route root.
34: route espmc.rm017 not matched by any connected route root.
35: Duplicate list name: DEU-NW L232
36: Duplicate list name: DEU-NW L705
37: Duplicate list name: DEU-NW L84
38: Duplicate list name: DEU-NW L150
39: Duplicate list name: DEU-NW L124
40: Duplicate list name: DEU-NW L260
41: Duplicate list name: DEU-NW L84
42: Duplicate list name: DEU-NW L124
43: Duplicate list name: DEU-NW L150
44: Duplicate list name: DEU-NW L232
45: Duplicate list name: DEU-NW L260
46: Duplicate list name: DEU-NW L705
47: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-BY/deuac/deuby.a094muc.wpt'
48: Route contains fewer than 2 points: deuby.a094muc (0 total points)
49: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.l232.wpt'
50: Route contains fewer than 2 points: deunw.l232 (0 total points)
51: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-HB/eursfc/deuhb.autzubhem.wpt'
52: Route contains fewer than 2 points: deuhb.autzubhem (0 total points)
53: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.k004.wpt'
54: Route contains fewer than 2 points: deunw.k004 (0 total points)
55: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.l705.wpt'
56: Route contains fewer than 2 points: deunw.l705 (0 total points)
57: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.chozub.wpt'
58: Route contains fewer than 2 points: deunw.chozub (0 total points)
59: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.l084.wpt'
60: Route contains fewer than 2 points: deunw.l084 (0 total points)
61: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.indstrkol.wpt'
62: Route contains fewer than 2 points: deunw.indstrkol (0 total points)
63: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.l150.wpt'
64: Route contains fewer than 2 points: deunw.l150 (0 total points)
65: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.malstrdor.wpt'
66: Route contains fewer than 2 points: deunw.malstrdor (0 total points)
67: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.k008.wpt'
68: Route contains fewer than 2 points: deunw.k008 (0 total points)
69: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.munstrdus.wpt'
70: Route contains fewer than 2 points: deunw.munstrdus (0 total points)
71: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.l124.wpt'
72: Route contains fewer than 2 points: deunw.l124 (0 total points)
73: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.l260.wpt'
74: Route contains fewer than 2 points: deunw.l260 (0 total points)
75: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.rhebrudus.wpt'
76: Route contains fewer than 2 points: deunw.rhebrudus (0 total points)
77: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.quespaunna.wpt'
78: Route contains fewer than 2 points: deunw.quespaunna (0 total points)
79: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-NW/eursfc/deunw.k003.wpt'
80: Route contains fewer than 2 points: deunw.k003 (0 total points)
81: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-HE/deuhelc/deuhe.l3126a.wpt'
82: Route contains fewer than 2 points: deuhe.l3126a (0 total points)
83: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/DEU-HE/deuhelc/deuhe.l3250a.wpt'
84: Route contains fewer than 2 points: deuhe.l3250a (0 total points)
`

**Comment by michihdeu** [comment]
> I realize now what you were probably asking is to have graphs for the DEU regions that include these devel systems. That would be harder, so I can't do it tonight at least. I can look into how hard it would be to build some.

No, not devel systems. All are active or in preview, railsystems.csv. But they are rail systems instead of road systems. The regions.csv has all DEU-xx (and ESP-xx) entries but only DEU-region.tmg and ESP-region.tmg are generated. I guess related to the systems.csv?

It's no matter if it is not (easily) possible but it would help.

I'll look into the error output now...

**Comment by michihdeu** [comment]
I have NOT changed ESP files but we get errors which let the update fail!?!?!?!?!

>  1: Could not find Route matching root espri.a013 in system espab.
2: No roots in _con.csv line [espab;A13;;;espri.a013 ]
3: Could not find Route matching root espcl.bu011 in system espab.
4: No roots in _con.csv line [espab;BU11;;;espcl.bu011 ]
5: Could not find Route matching root espmc.rm001 in system espab.
6: No roots in _con.csv line [espab;RM1;;;espmc.rm001 ]
7: Could not find Route matching root espmc.rm002 in system espab.
8: No roots in _con.csv line [espab;RM2;;;espmc.rm002 ]
9: Could not find Route matching root espmc.rm003 in system espab.
10: No roots in _con.csv line [espab;RM3;;;espmc.rm003 ]
11: Could not find Route matching root espmc.rm016 in system espab.
12: No roots in _con.csv line [espab;RM16;;;espmc.rm016 ]
13: Could not find Route matching root espmc.rm017 in system espab.
14: No roots in _con.csv line [espab;RM17;;;espmc.rm017 ]

**Comment by jteresco** [comment]
No idea - I'll run another update now.

**Pull request merged**
