### PR TITLE
TX forum items, 2024-01-04

### PR DESCRIPTION
**Pull request by yakra**
https://forum.travelmapping.net/index.php?topic=6019
Ping @mapcat because you were there.
Ping @Markkos1992 because you're good at finding errors.
https://forum.travelmapping.net/index.php?topic=5958
https://forum.travelmapping.net/index.php?topic=5994

### CODE REVIEW

**Comment by yakra** [comment]
need to add an update entry for that last one

**Comment by yakra** [comment]
I'll resubmit this with today's date for the updates entries, because userlog route updates.
With luck & time I may get the I-20 thread in there too.

**Comment by michihdeu** [comment]
> I'll resubmit this with today's date for the updates entries, **because userlog route updates**.

I did the same for my yesterday's update entry since Jim missed running an update yesterday.

**Comment by yakra** [comment]
The new one is ready to go; I'm just running a few scripts to find out who to ping about some of the newsworthy changes.

**Pull request closed without merging**
