### PR TITLE
CANBC (and others)

### PR DESCRIPTION
**Pull request by si404**
First draft of canbc. Sorts out WY datacheck error and usamts issues.

### CODE REVIEW

**Comment by yakra** [comment]
I'd prefer to:
1.) keep CANSPH in place as a holding ground for indefinitely-mothballed provincial systems (e.g. cannl, canqc, cansk), until proper development starts on them.
2.) see more discussion before changes are brought into place affecting other collaborators' regions.

**Comment by si404** [comment]
1) cansph is still there and is the front-facing one. I actually explain that in that commit!
2) a) I've changed no files in active systems (other than the MT, ID and WY ones that are in my regions) - I've simply added some devel ones
b) Given the near silence I've had from collaborators wrt reviewing my in dev systems (and then, other than your vague promise to eventually get round to reviewing some of the state route systems, it's to ask why I haven't activated it yet despite my requests for some review before I do), I've assumed the policy is that talk is bad and action is good.
c) You can simply revert changes, or ask for them to be reverted (and I will happily change it), if you don't want them.
d) You say you want more discussion, but you don't actually take part in the discussion by reading what I'm proposing in this pull request, or saying what you want me to do.

**Comment by ovoss** [comment]
I thought Bickendan had his eye on doing CANBC. He did the first draft of 
many of the routes, after all.

Also, I thought yakra was working on CANMB (at least the trunk routes, which 
include all of the routes in CANSPH).

I have no problem with Si's taking on CANBC, if Bickendan and yakra (as 
master of Canadian GeoBase shapefiles) don't. I've said that my handling BC 
active routes maintenance doesn't mean I intend to do the provincial routes 
myself, so I don't have a competing claim. My GPS reads from BC 37, BC 77, 
and the northern part of BC 97 could possibly help cover areas of northern 
BC where online mapping can be really sucky (as it is for most of the 
Arctic).

But I suggest that in the future we first "claim" a proposed new system, and 
wait for others to chime in or perhaps put in their own claims, before 
starting work on drafting route files.

Oscar

----- Original Message ----- 
From: Si Hollett
To: TravelMapping/HighwayData
Sent: Thursday, February 04, 2016 9:17 AM
Subject: [HighwayData] CANBC (and others) (#400)


First draft of canbc. Sorts out WY datacheck error and usamts issues.



You can view, comment on, or merge this pull request online at:
  https://github.com/TravelMapping/HighwayData/pull/400
Commit Summary
sct national tourist routes
Merge remote-tracking branch 'refs/remotes/TravelMapping/master'
usamts
CAN SPH split
canbc - first draft
wy59 datacheck
ID label tweaks
File Changes
A hwy_data/BC/canbc/bc.bc001.wpt (292)
A hwy_data/BC/canbc/bc.bc001ache.wpt (10)
A hwy_data/BC/canbc/bc.bc001avan.wpt (16)
A hwy_data/BC/canbc/bc.bc001buscha.wpt (3)
A hwy_data/BC/canbc/bc.bc001van.wpt (42)
R hwy_data/BC/canbc/bc.bc002.wpt (0)
R hwy_data/BC/canbc/bc.bc003.wpt (0)
A hwy_data/BC/canbc/bc.bc003acra.wpt (19)
A hwy_data/BC/canbc/bc.bc003aker.wpt (10)
A hwy_data/BC/canbc/bc.bc003anel.wpt (28)
A hwy_data/BC/canbc/bc.bc003b.wpt (31)
A hwy_data/BC/canbc/bc.bc004.wpt (65)
A hwy_data/BC/canbc/bc.bc004a.wpt (8)
R hwy_data/BC/canbc/bc.bc005.wpt (3)
A hwy_data/BC/canbc/bc.bc005a.wpt (53)
A hwy_data/BC/canbc/bc.bc006.wpt (90)
A hwy_data/BC/canbc/bc.bc006ver.wpt (49)
A hwy_data/BC/canbc/bc.bc007.wpt (64)
A hwy_data/BC/canbc/bc.bc007b.wpt (8)
A hwy_data/BC/canbc/bc.bc008.wpt (25)
A hwy_data/BC/canbc/bc.bc009.wpt (14)
A hwy_data/BC/canbc/bc.bc010.wpt (16)
A hwy_data/BC/canbc/bc.bc011.wpt (18)
A hwy_data/BC/canbc/bc.bc012.wpt (24)
A hwy_data/BC/canbc/bc.bc013.wpt (5)
A hwy_data/BC/canbc/bc.bc014.wpt (49)
A hwy_data/BC/canbc/bc.bc015.wpt (11)
A hwy_data/BC/canbc/bc.bc016.wpt (304)
A hwy_data/BC/canbc/bc.bc016hai.wpt (40)
R hwy_data/BC/canbc/bc.bc017.wpt (0)
A hwy_data/BC/canbc/bc.bc017a.wpt (4)
A hwy_data/BC/canbc/bc.bc017ric.wpt (26)
A hwy_data/BC/canbc/bc.bc018.wpt (11)
R hwy_data/BC/canbc/bc.bc019.wpt (0)
A hwy_data/BC/canbc/bc.bc019acou.wpt (57)
A hwy_data/BC/canbc/bc.bc019anan.wpt (12)
A hwy_data/BC/canbc/bc.bc020.wpt (135)
A hwy_data/BC/canbc/bc.bc021.wpt (8)
A hwy_data/BC/canbc/bc.bc022.wpt (21)
A hwy_data/BC/canbc/bc.bc022a.wpt (7)
A hwy_data/BC/canbc/bc.bc023.wpt (44)
A hwy_data/BC/canbc/bc.bc023nak.wpt (14)
A hwy_data/BC/canbc/bc.bc024.wpt (29)
A hwy_data/BC/canbc/bc.bc026.wpt (34)
A hwy_data/BC/canbc/bc.bc027.wpt (22)
A hwy_data/BC/canbc/bc.bc028.wpt (33)
A hwy_data/BC/canbc/bc.bc029.wpt (83)
A hwy_data/BC/canbc/bc.bc030.wpt (19)
A hwy_data/BC/canbc/bc.bc031.wpt (42)
A hwy_data/BC/canbc/bc.bc031a.wpt (15)
A hwy_data/BC/canbc/bc.bc033.wpt (44)
A hwy_data/BC/canbc/bc.bc035.wpt (15)
R hwy_data/BC/canbc/bc.bc037.wpt (52)
A hwy_data/BC/canbc/bc.bc037a.wpt (22)
A hwy_data/BC/canbc/bc.bc039.wpt (13)
A hwy_data/BC/canbc/bc.bc041.wpt (2)
A hwy_data/BC/canbc/bc.bc043.wpt (12)
R hwy_data/BC/canbc/bc.bc049.wpt (2)
A hwy_data/BC/canbc/bc.bc052.wpt (67)
A hwy_data/BC/canbc/bc.bc077.wpt (36)
R hwy_data/BC/canbc/bc.bc091.wpt (0)
R hwy_data/BC/canbc/bc.bc091a.wpt (0)
R hwy_data/BC/canbc/bc.bc093.wpt (2)
R hwy_data/BC/canbc/bc.bc095.wpt (2)
A hwy_data/BC/canbc/bc.bc095a.wpt (28)
R hwy_data/BC/canbc/bc.bc097.wpt (2)
A hwy_data/BC/canbc/bc.bc097a.wpt (26)
A hwy_data/BC/canbc/bc.bc097b.wpt (12)
R hwy_data/BC/canbc/bc.bc097c.wpt (0)
R hwy_data/BC/canbc/bc.bc097con.wpt (0)
A hwy_data/BC/canbc/bc.bc097d.wpt (13)
R hwy_data/BC/canbc/bc.bc097lia.wpt (0)
R hwy_data/BC/canbc/bc.bc097low.wpt (0)
R hwy_data/BC/canbc/bc.bc099.wpt (7)
R hwy_data/BC/canbc/bc.bc101.wpt (2)
R hwy_data/BC/canbc/bc.bc101pow.wpt (0)
A hwy_data/BC/canbc/bc.bc113.wpt (50)
A hwy_data/BC/canbc/bc.bc118.wpt (14)
R hwy_data/BC/canbc/bc.bc395.wpt (6)
D hwy_data/BC/cansph/bc.bc017ric.wpt (9)
A hwy_data/IA/usaush/ia.us006hiscou.wpt (4)
A hwy_data/IA/usaush/ia.us006hisred.wpt (27)
A hwy_data/IA/usaush/ia.us020hisepw.wpt (9)
M hwy_data/ID/usaid/id.id001.wpt (2)
M hwy_data/ID/usaid/id.id004.wpt (2)
M hwy_data/ID/usaid/id.id021.wpt (2)
M hwy_data/ID/usaid/id.id022.wpt (2)
M hwy_data/ID/usaid/id.id024.wpt (2)
M hwy_data/ID/usaid/id.id027.wpt (2)
M hwy_data/ID/usaid/id.id036.wpt (2)
M hwy_data/ID/usaid/id.id037.wpt (2)
M hwy_data/ID/usaid/id.id038.wpt (2)
M hwy_data/ID/usaid/id.id040.wpt (2)
M hwy_data/ID/usaid/id.id041.wpt (2)
M hwy_data/ID/usaid/id.id044.wpt (2)
M hwy_data/ID/usaid/id.id046.wpt (2)
M hwy_data/ID/usaid/id.id046sprwen.wpt (2)
M hwy_data/ID/usaid/id.id048.wpt (2)
M hwy_data/ID/usaid/id.id050.wpt (2)
M hwy_data/ID/usaid/id.id069.wpt (2)
M hwy_data/ID/usaid/id.id077.wpt (2)
M hwy_data/ID/usaid/id.id078.wpt (2)
M hwy_data/ID/usaid/id.id079.wpt (2)
M hwy_data/ID/usaid/id.id081sprcot.wpt (2)
M hwy_data/ID/usaid/id.id097.wpt (2)
A hwy_data/MA/usaush/ma.us020.wpt (4)
A hwy_data/MB/canmb/mb.mb001.wpt (117)
A hwy_data/MB/canmb/mb.mb001abra.wpt (8)
A hwy_data/MB/canmb/mb.mb001apor.wpt (11)
A hwy_data/MB/canmb/mb.mb006.wpt (162)
A hwy_data/MB/canmb/mb.mb010.wpt (285)
A hwy_data/MB/canmb/mb.mb016.wpt (62)
A hwy_data/MB/canmb/mb.mb016amin.wpt (9)
A hwy_data/MB/canmb/mb.mb029.wpt (2)
A hwy_data/MB/canmb/mb.mb059.wpt (79)
A hwy_data/MB/canmb/mb.mb060.wpt (45)
A hwy_data/MB/canmb/mb.mb075.wpt (37)
A hwy_data/MB/canmb/mb.mb083.wpt (109)
A hwy_data/MB/canmb/mb.mb100.wpt (16)
A hwy_data/MB/canmb/mb.mb101.wpt (21)
M hwy_data/MT/usamts/mt.sr328.wpt (12)
A hwy_data/NL/cannl/nl.nl001.wpt (265)
A hwy_data/NL/cannl/nl.nl002.wpt (23)
A hwy_data/NL/cannl/nl.nl003a.wpt (3)
A hwy_data/NL/cannl/nl.nl100.wpt (37)
A hwy_data/NL/cannl/nl.nl430.wpt (138)
A hwy_data/OH/usaush/oh.us020hisnor.wpt (16)
A hwy_data/OH/usaush/oh.us020hispai.wpt (5)
A hwy_data/QC/canqc/qc.qc117.wpt (153)
A hwy_data/QC/canqc/qc.qc133.wpt (32)
A hwy_data/QC/canqc/qc.qc155.wpt (79)
A hwy_data/QC/canqc/qc.qc170.wpt (55)
A hwy_data/QC/canqc/qc.qc173.wpt (39)
A hwy_data/QC/canqc/qc.qc175.wpt (77)
A hwy_data/QC/canqc/qc.qc185.wpt (8)
A hwy_data/SCT/sctntr/sct.angcr.wpt (32)
A hwy_data/SCT/sctntr/sct.argcr.wpt (80)
A hwy_data/SCT/sctntr/sct.borhisrt.wpt (63)
A hwy_data/SCT/sctntr/sct.clyvalrt.wpt (29)
A hwy_data/SCT/sctntr/sct.deetr.wpt (79)
A hwy_data/SCT/sctntr/sct.fifcr.wpt (52)
A hwy_data/SCT/sctntr/sct.forvalrt.wpt (27)
A hwy_data/SCT/sctntr/sct.galtr.wpt (64)
A hwy_data/SCT/sctntr/sct.higtr.wpt (71)
A hwy_data/SCT/sctntr/sct.morfirtr.wpt (50)
A hwy_data/SCT/sctntr/sct.nwhigrt.wpt (93)
A hwy_data/SCT/sctntr/sct.pertr.wpt (30)
A hwy_data/SK/cansk/sk.sk001.wpt (122)
A hwy_data/SK/cansk/sk.sk002.wpt (246)
A hwy_data/SK/cansk/sk.sk004.wpt (160)
A hwy_data/SK/cansk/sk.sk006.wpt (101)
A hwy_data/SK/cansk/sk.sk007.wpt (55)
A hwy_data/SK/cansk/sk.sk011.wpt (125)
A hwy_data/SK/cansk/sk.sk016.wpt (129)
A hwy_data/SK/cansk/sk.sk016a.wpt (4)
A hwy_data/SK/cansk/sk.sk016b.wpt (5)
A hwy_data/SK/cansk/sk.sk035.wpt (117)
A hwy_data/SK/cansk/sk.sk039.wpt (60)
M hwy_data/WY/usawy/wy.wy059.wpt (3)
A hwy_data/YT/canbc/yt.bc097con.wpt (4)
A hwy_data/YT/canbc/yt.bc097lia.wpt (9)
A hwy_data/YT/canbc/yt.bc097yuk.wpt (4)
A hwy_data/_systems/canbc.csv (83)
A hwy_data/_systems/canbc_con.csv (77)
A hwy_data/_systems/canmb.csv (15)
A hwy_data/_systems/canmb_con.csv (15)
A hwy_data/_systems/cannl.csv (6)
A hwy_data/_systems/cannl_con.csv (6)
A hwy_data/_systems/canqc.csv (6)
A hwy_data/_systems/canqc_con.csv (6)
A hwy_data/_systems/cansk.csv (12)
A hwy_data/_systems/cansk_con.csv (12)
M hwy_data/_systems/cansph.csv (24)
M hwy_data/_systems/cansph_con.csv (18)
A hwy_data/_systems/sctntr.csv (13)
A hwy_data/_systems/sctntr_con.csv (13)
M hwy_data/_systems/usamts.csv (2)
M hwy_data/_systems/usamts_con.csv (2)
M hwy_data/_systems/usaush.csv (5)
M hwy_data/_systems/usaush_con.csv (5)
M systems.csv (13)
Patch Links:
https://github.com/TravelMapping/HighwayData/pull/400.patch
https://github.com/TravelMapping/HighwayData/pull/400.diff
—
Reply to this email directly or view it on GitHub.



--
Oscar Voss - ovoss@pobox.com (old address still works) - Arlington VA

my Hot Springs and Highways pages (new address):
http://www.alaskaroads.com/home.html

**Comment by yakra** [comment]
1.) Taking a closer look at the commits, I'm seeing that's the case. I had overlooked noticed your commit message, sorry. Guess I was more hung up on looking at the file diffs themselves.
2c.) I'm starting to grok that this is a matter of forward-compatibility. "allowing them to be developed, and cansph to be removed", as you said. Pull a switch & make the change. I'd thought about reverting the changes (for my regions at least) if they'd gone thru, but that might just create animosity and start to look like an edit war; I'd discuss it first of course. :)
(Moot point now though; I see you've added a new commit.)
2d.) Taking part in the discussion is exactly what I'm doing by posting here. Again, my apologies if I missed the commit message, or if I spoke to soon before having a completely clear picture of the effects of the change. But telling you to do a specific thing needn't be the only direction a discussion can take.

3.) To be fair, It could be that I've been limited in my thinking: I tend to look at Pull Requests as something to be merged in; changes the collaborator expects to be implemented. And that's not necessarily correct. They can also be just a proposal -- to be accepted, rejected or modified, or discussed (there's that word again) and closed & abandoned. Thinking back now to the proposed USANYP system, which was tabled and closed, with no objections that I can remember.

**Comment by si404** [comment]
re: canbc and Bickenden: I found [this 2010 post](http://clinched.s2.bizhat.com/viewtopic.php?p=4888&mforum=clinched#4888) on the old forums, but couldn't see anything more recent (the system is described as "in queue (but available for anyone interested)" along with various systems that others have made/are making. I'm very happy for him (or anyone) to take the system off me if they want.

re: splitting cansph - ah good, what I proposed doing was understandable, even if it's not going ahead now.

re: claiming systems - I make draft files for systems pretty impulsively, and by the time I get the OK to start (especially with the time difference), I would have either made them already or lost interest. Obviously I'd avoid doing systems in areas where I'd step on toes (hence the going into new territory), but BC was both easy enough (I looked at QC and decided against it) and been declared fair game.

**Comment by jteresco** [comment]
@si404, please check that the CSV and/or filename mismatches that I corrected in BC and SCT were handled using the actual names you intended.

**Pull request merged**
