### PR TITLE
NC changes from mapmikey

### PR DESCRIPTION
**Pull request by mapcat**
YYYY-MM-DD;Country;Route;Root;Description
2016-02-17;(USA) North Carolina;NC 906;nc.nc906;added newly commissioned NC 906 requiring additional points to US 17 and US 17busbol
2016-02-17;(USA) North Carolina;I-74 High Point;nc.i074hig;added fut I-74 high point exits to this as it is now an interstate...also added new waypoint at 72B(73)
2016-02-17;(USA) North Carolina;I-73;nc.i073;added new waypoint at 72B
2016-02-17;(USA) North Carolina;US 220;nc.us220;added new waypoint at 72B(73)
2016-02-17;(USA) North Carolina;I-74 Future (High Point);nc.i074futhig;Route deleted

### CODE REVIEW

**Comment by jteresco** [comment]
Thanks.  Am I correct that we should also have an AltRouteName entry with I-74 for the old segment of the Future I-74 that's been merged in?

**Comment by yakra** [comment]
> Thanks. Am I correct that we should also have an AltRouteName entry with I-74 for the old segment of the Future I-74 that's been merged in?

I believe that's the case, though I've only read the discussion and not looked at any file diffs.

**Comment by yakra** [comment]
Also, on I-74Hig, should 55t & 56t be relabeled to 55 & 56?

**Comment by mapcat** [comment]
Busy at work now, but will make the changes later this afternoon.

**Comment by mapcat** [comment]
Anyone mind if I add some Sanford area fixes (US421 & NC87 moved to the bypass, + new US421 business & possibly 87 business) to this one?

**Comment by yakra** [comment]
Suggest checking in on the forum.
[mapmikey's been active there.](http://tm.teresco.org/forum/index.php?topic=54.msg481;topicseen#msg481)

**Comment by mapcat** [comment]
OK I'll wait for a response from him.

**Comment by jteresco** [comment]
I have no preference between adding a couple more commits to this pull for the Sanford area fixes, or creating a second pull request.  Whatever's easier on your end, I'd say.

**Comment by mapcat** [comment]
This is ready to go, unless you wish to wait for the Sanford edits assuming I get the go-ahead from mapmikey.

**Comment by jteresco** [comment]
I am pulling this in, please note the simplified updates entries I'm using.  We don't need updates entries for new points, so some were left out.

**Pull request merged**
