### PR TITLE
WV fixes (US-48 and others)

### PR DESCRIPTION
**Pull request by rickmastfan67**
15-09-07;(USA) West Virginia;US 48;wv.us048;Extended west from the access road to WV 42/WV 93 (ToWV42) to the County Line of Grant and Tucker (Gra/Tuc).
15-09-07;(USA) West Virginia;WV 93;wv.wv093;Relocated route just outside of Bismarck from the now abandoned old road and to slightly to the north onto the new 4-lane US 48 Corridor H between a new intersection with US 48 (US48_E) and the County Line of Grant & Tucker (US48_Tuc).

All other files were just fixes to intersections that were off the main route a good distance.  Also added a few new minor intersections to help smooth a few of the routes out.  Plus dealt with http://clinched.s2.bizhat.com/viewtopic.php?t=2194&mforum=clinched, which was a minor addition of a point where that road connected with a numbered KY highway on the other side of a river, yet doesn't have a number (is a CR route) on the WV side.

### CODE REVIEW

**Comment by jteresco** [comment]
Thanks, pulling this in.

**Comment by ovoss** [comment]
West endpoint of US 48 should be Tuc/Gra, not Gra/Tuc. Tucker County is on 
the west side of the county line where US 48 begins, Grant County is on the 
east side.

----- Original Message ----- 
From: rickmastfan67
To: TravelMapping/HighwayData
Sent: Monday, September 07, 2015 6:54 AM
Subject: [HighwayData] WV fixes (US-48 and others) (#85)


15-09-07;(USA) West Virginia;US 48;wv.us048;Extended west from the access 
road to WV 42/WV 93 (ToWV42) to the County Line of Grant and Tucker 
(Gra/Tuc).
15-09-07;(USA) West Virginia;WV 93;wv.wv093;Relocated route just outside of 
Bismarck from the now abandoned old road and to slightly to the north onto 
the new 4-lane US 48 Corridor H between a new intersection with US 48 
(US48_E) and the County Line of Grant & Tucker (US48_Tuc).
All other files were just fixes to intersections that were off the main 
route a good distance. Also added a few new minor intersections to help 
smooth a few of the routes out. Plus dealt with 
http://clinched.s2.bizhat.com/viewtopic.php?t=2194&mforum=clinched, which 
was a minor addition of a point where that road connected with a numbered KY 
highway on the other side of a river, yet doesn't have a number (is a CR 
route) on the WV side.



You can view, comment on, or merge this pull request online at:
  https://github.com/TravelMapping/HighwayData/pull/85
Commit Summary
(USA) West Virginia US 48: Extended west from the access road to WV 42/WV 93 
(ToWV42) to the County Line of Grant and Tucker (Gra/Tuc).
Fixes for new segment of US-48.
Resyncing cordinates for intersecting routes.
Resyncing cordinates for intersecting routes.
Intersection relocation fixes.
Intersection relocation fixes.
Intersection relocation fixes.
Intersection relocation fixes.
Intersection relocation fixes.
Intersection relocation fixes.
Intersection relocation fixes.
Overhualed WV-49.
Intersection relocation fixes.
File Changes
M hwy_data/WV/usaus/wv.us048.wpt (12)
M hwy_data/WV/usaus/wv.us052.wpt (4)
M hwy_data/WV/usawv/wv.wv007.wpt (2)
M hwy_data/WV/usawv/wv.wv020.wpt (17)
M hwy_data/WV/usawv/wv.wv032.wpt (4)
M hwy_data/WV/usawv/wv.wv042.wpt (10)
M hwy_data/WV/usawv/wv.wv049.wpt (28)
M hwy_data/WV/usawv/wv.wv063.wpt (2)
M hwy_data/WV/usawv/wv.wv085.wpt (2)
M hwy_data/WV/usawv/wv.wv093.wpt (32)
M hwy_data/WV/usawv/wv.wv099.wpt (2)
M hwy_data/WV/usawv/wv.wv598.wpt (6)
Patch Links:
https://github.com/TravelMapping/HighwayData/pull/85.patch
https://github.com/TravelMapping/HighwayData/pull/85.diff
—
Reply to this email directly or view it on GitHub.



--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages (NEW ADDRESS):
http://www.alaskaroads.com/home.html

**Comment by rickmastfan67** [comment]
Oops. Working on a fix right now. Also tweaking the label in WV-93's file to US48_Gra.

**Comment by rickmastfan67** [comment]
Fix submitted as #88.

**Comment by jteresco** [comment]
OK, pulling in #88.

**Comment by rickmastfan67** [comment]
Just quickly pushed a fix directly to the master to fix the labels in the 'updates.csv' file Jim since the mentions were for the old 'incorrect' labels.

**Comment by rickmastfan67** [comment]
@jteresco Just quickly pushed a fix directly to the master to fix the labels in the 'updates.csv' file since the mentions were for the old 'incorrect' labels and needed to be fixed.

**Comment by jteresco** [comment]
Thanks - same time as a change I was making but it was easy enough to resolve the conflict.

**Comment by rickmastfan67** [comment]
Sorry about that Jim.  Didn't know you were editing the file at the same time.

**Comment by jteresco** [comment]
Not a problem!  That's why we use version control.

**Pull request merged**
