### PR TITLE
Standardize header for system files (#1321)

### PR DESCRIPTION
**Pull request by Thing342**
sets all system and _con files to use the same set of headers:

System: `System;Region;Route;Banner;Abbrev;City;Root;AltRouteNames`
Conn: `System;Route;Banner;Name;Roots`

### CODE REVIEW

**Comment by jteresco** [comment]
Would there be any advantage to having these match the names of the columns in the DB tables?

**Comment by compdude** [comment]
What does the "Root/Roots" column mean?

**Comment by yakra** [comment]
root is the identifier for a single route file, the bit that goes in the *r=* field of a HB url, the bit that comes before .wpt in a filename, E.G. *me.us001*, or *me.us001altpor*.

**Comment by compdude** [comment]
Oh, okay. I think what confused me was that that column was previously called "Filename" in the usawa.csv and usawa_con.csv files.

**Comment by yakra** [comment]
Aa, sou. However it happened, the original creator of those files used a different variation on the header rows. Different terms to refer to different things. Which is fine -- the only purpose of the header row was for human-readable convenience, when editing the CSVs as a spreadsheet; it's not meant to be read or used by any program. I've seen some other variations in header row usage over the years. Or maybe just that one.

The syntax , as posted in the original *comment*, is the original syntax inherited from CHM. As for this pull request, the commits are all over the place, and I'm scratching my head as to its intent, direction, usefulness. That said, I rather dislike the idea of my files being edited out from under me. usame.csv, usanh.csv, cannb.csv, etc. are *mine*, and I'd prefer to just see myself in the commit history for those. :)

**Comment by jteresco** [comment]
The point of the edits in this pull request, which I was planning to merge in before the next site update, is to standardize all of those, and make them match the names of the DB tables in which this information is stored.  The idea is to be able to use python libraries that will read those in more efficiently.  If there's a strong objection, I can wait for further discussion.  Since to date, those header lines are simply skipped over by the site update code, I didn't think there would be any harm in standardizing in one big batch.

**Comment by yakra** [comment]
will have a specific datum in the header row provide any real advantage? Will it change the CSVs behavior WRT these Python libs at all?

**Comment by jteresco** [comment]
I'll defer to @Thing342 on that, since I have not used the faster Python libraries he's proposing.  But even ignoring that, I'd say a consistency among all csv files and the DB tables is a Good Thing.  Seems to me that standardizing headers has no downside (other than having to do it, which he's already done for us) and potential advantages.

**Pull request merged**
