### PR TITLE
usanyp -> preview

### PR DESCRIPTION
**Pull request by yakra**
addresses #56 & #514

### CODE REVIEW

**Comment by yakra** [comment]
I intended to run the *siteupdate* test before opening this pull request, but neglected to do so.
I'll do that and report whether we're good to go or there are problems.

**Comment by ssoworld** [comment]
Where does the Palisades Interstate Parkway fall into this?  Joint between the states? Port Authority?

**Comment by yakra** [comment]
@ssoworld [asks](https://github.com/TravelMapping/UserData/pull/1599#issuecomment-400109004):
> Where does the Palisades Interstate Parkway fall into this? Joint between the states? Port Authority?

NY PalIntPkwy, reference route 987C, is currently active as part of [usasf](http://travelmapping.net/hb/?units=miles&sys=usasf&rg=NY), and among the routes that will be transferred to [usanyp](http://travelmapping.net/hb/?u=wadsteckel&units=miles&sys=usanyp) when it's promoted to active.

Also included in this category is [NY GarStaPkwy](travelmapping.net/hb/index.php?&r=ny.garstapkwy) -- see http://forum.travelmapping.net/index.php?topic=1928.msg5229#msg5229

**Comment by yakra** [comment]
> I intended to run the siteupdate test before opening this pull request, but neglected to do so. I'll do that and report whether we're good to go or there are problems.

Data check successful!

**Pull request merged**
