### PR TITLE
IL/IA/MO/WI Updates from Highway63  

### PR DESCRIPTION
**Pull request by Markkos1992**
Illinois:
I-55 BL (Springfield, IL): Fixing IL29_S. (Done by @Markkos1992)
US 54: Slightly relocated point MO/IL for new bridge.
US 67: Added exit ConAreRd.
IL 29:  Removed from Springfield Road through Edinburg and relocated onto four-lane bypass on east side of Edinburg. Added points HicSt, WebSt_N.  (Corrected SanAve>-I-55BL_S by @Markkos1992)
IL 104:  Added point MorSt for new bridge across Illinois River. Added exit ConAreRd. (https://forum.travelmapping.net/index.php?topic=4814.0)

Iowa:
US 30 BUS (Mount Vernon, IA):  Added route.
US 52: Renamed IA3/136->IA3.
US 151: Renamed US151BusCas_S->248thSt.
US 151 BUS (Cascade, IA):  Removed from 1st Avenue southwest of IA 136 and relocated onto IA 136 between 1st Avenue and US 151 in Cascade. Point US151_S relocated from old south end to IA 136 interchange.(https://forum.travelmapping.net/index.php?topic=4817.0)
IA 1: LinHwy>-US30Bus_E.  (Done by @Markkos1992) 
IA 3:  Renamed US52/136->US52.
IA 136:  Truncated from IA 3 to US 20. Renamed US151->US151/151Bus. Renamed US151Bus->US151Bus_N.

Missouri:
I-44 BL (Lebanon, MO):  Deleted Route.
US 36: Added exit for AgExpoWay. (https://forum.travelmapping.net/index.php?topic=4811.0)
US 54: Added MOsHH_Ced, MOsPP_StC, OBPkwy, MOsMM_Mil, MOsCC_Col. Renamed US54Bus/242->MO242.  (https://forum.travelmapping.net/index.php?topic=4817.msg27109#msg27109) Deleted US54BusLak_E. Moved MO79_N from Frank Ford Road to 7th Street in Louisiana. Slightly relocated point MO/IL for new bridge.  (Note nonessential prefixes STowSt, SAshSt, ECenSt)
US 54 BUS (Lake Ozark, MO):  Deleted Route.
MO 5: Renamed I-44BL/32->MO32_W. (Note prefixes WGarSt, WMainSt along US 136 Concurrency)
MO 32:  Renamed I-44BL/5->MO5_N, I-44BL_W->ElmSt_W. Added CowDr.
MO 64: Renamed I-44BL/32->MO32_W.
MO 79: Relocated US54_W from Frank Ford Road to 7th Street in Louisiana.
US 66 Historic (St. Louis):  Renamed 44Leb->I-44(127). Renamed I-44BL_E->MOsMM.

Wisconsin:
WI 83: Truncated from WI 175 to WI 60.
WI 175: Renamed WI83->CRR.

### CODE REVIEW

**Comment by Markkos1992** [comment]
@jteresco I also removed some unused alternate labels.

**Comment by ssoworld** [comment]
@Markkos1992 can you confirm IA 163's truncation?  If help is needed let me know and I'll drive the route tomorrow.

**Comment by Markkos1992** [comment]
I found a paywalled article linked to about it on the IA 136 Wikipedia page (https://en.wikipedia.org/wiki/Iowa_Highway_136).

I guess Highway63 already knew about it or the file would not have been sent.

**Comment by ssoworld** [comment]
@Markkos1992 that's a confirm, (I subscribe to TH so I was able to see it 😁).  All good.

**Pull request merged**
