### PR TITLE
Final NM SR changes

### PR DESCRIPTION
**Pull request by ovoss**
Last few route file updates needed before usanm activation.

### CODE REVIEW

**Comment by yakra** [comment]
NM118: should AltLabels even be in use if the system hasn't been activated yet?

**Comment by ovoss** [comment]
I've used AltLabels sparingly for the pre-activation usanm route set. In this case, to avoid list file breakage from point label renames just a day or two before activation. 

----- Original Message -----

**Comment by jteresco** [comment]
I don't mind the AltLabels being in there.  They add a near-zero cost to site update processing, and no cost at all to the time or space needed after processing.

I'll pull this in and run an update.  If things look clean, I'll activate.

**Comment by jteresco** [comment]
Looking at the forum, I'll wait for word about the possible partial decommissioning mentioned there before activation.  Update running now.

**Pull request merged**
