### PR TITLE
MS routes, MN 67 reroute, and unused alt label cleanup

### PR DESCRIPTION
**Pull request by ajfroggie**
* Added the remaining Mississippi state routes (mainly the MS 5xx routes)
* Rerouted MN 67 and related changes, adding MN 167 and removing MN 274
* Cleaned up unused alt labels for AL, MN, MS, and VT

### CODE REVIEW

**Comment by yakra** [comment]
MN274 could be added as an AltRouteName for MN67, with some AltLabels added to preserve users' travels.
https://forum.travelmapping.net/index.php?topic=4967.msg30711#msg30711

**Comment by michihdeu** [comment]
> MN274 could be added as an AltRouteName for MN67, with some AltLabels added to preserve users' travels. https://forum.travelmapping.net/index.php?topic=4967.msg30711#msg30711

If so, the update entries should be:
`2023-02-11;(USA) Minnesota;MN 67;mn.mn067;New route (former M274)`
`2023-02-11;(USA) Minnesota;MN 274;mn.mn067;Deleted route (MN 67 now)`

**Comment by yakra** [comment]
^ Nope, MN67 already exists, so the [updates entry for its relocation](https://github.com/TravelMapping/HighwayData/pull/6393/files#diff-daafe14a3db78e6f30f5b12cb577fcf8adc63631d3315cea73322d3b2c6a3da0R5624) is appropriate.

For MN274, "(MN 67 now)" is helpful but not crucial IMO.
* Userlogs would have an update notification for MN67, which contains the info that it used to be MN274.
* Otherwise, one would have to be looking at the updates page to see the MN274 entry, and surely see the MN67 update on the same date.

**Comment by ajfroggie** [comment]
A further complication with that:  not all of the former MN 274 is being
used for the MN 67 reroute.  There's a segment on the south end that was
turned back to the county.

I felt this was a case of just "ripping the band aid off"...

**Comment by mapcat** [comment]
@ajfroggie do you need help editing systems.csv and systemupdates.csv? usams won't go to preview unless you (or someone) makes those edits

**Comment by ajfroggie** [comment]
I could, yes, especially since I’m not home for the evening and I work all day tomorrow.

Thank you.

-A

**Comment by mapcat** [comment]
These 2 will promote usams to preview:

https://github.com/TravelMapping/HighwayData/pull/6399
https://github.com/TravelMapping/HighwayData/pull/6400

(had to make separate because I have some edits on my base fork that may have conflicts with the OH updates submitted earlier today)

**Comment by yakra** [comment]
Oh yeah, I see that `CR21` is used at a new location and can't become an AltLabel.
For those on MN274, kramer & terminal_moraine would have to edit their lists anyway, unless they've already traveled  CR2.
With twinsfan87 already using the `CR2_E` point, I wonder if they already have. :D

ping @si404 @denishanson @mbeller2016 @dccooldude2002

**Comment by dccooldude2002** [comment]
I have already traveled on CR2.

**Comment by mbeller2016** [comment]
I also travelled on CR2 last July in anticipation of this change.Sent from my iPhoneOn Feb 11, 2023, at 7:29 PM, dccooldude2002 ***@***.***> wrote:﻿
I have already traveled on CR2.

**Comment by michihdeu** [comment]
fine to me. However, that's still valid:

> @ajfroggie `2023-02-11;(USA) Minnesota;MN 274;mn.mn274;Deleted route` should be read: `2023-02-11;(USA) Minnesota;MN 274;;Deleted route`

It's a dead link now.

**Comment by rickmastfan67** [comment]
@rmihailucian 
See: #6401

**Pull request merged**
