### PR TITLE
Minnesota US 14, MN 60, and MN 610 bypasses

### PR DESCRIPTION
**Pull request by ajfroggie**
Revisions for the US 14 Nicollet Bypass, MN 60 realignments near Worthington, and the MN 610 extension plus associated routes.

### CODE REVIEW

**Comment by yakra** [comment]
**US14:**
*Old14Nic_W & *Old14Nic_E should be *OldUS14Nic_W & *OldUS14Nic_E
"Missing Generic Road type" style datacheck error

**MN60:**
PaulAve & GatDr, as newly added points, do not need hidden AltLabels
+x02 extraneous? (I'm willing to let +x01 slide)

**I-90BLWor:**
Suggest retaining the old US59_S point, as [CliAve](http://www.openstreetmap.org/?lat=43.631020&lon=-95.580025), for those who have it in use

**US59:**
PaulAve & GatDr, as newly added points, do not need hidden AltLabels
+x02 extraneous? (I'm willing to let +x01 slide)
Suggest retaining the old I-90BL/60 point, as [CliAve](http://www.openstreetmap.org/?lat=43.631020&lon=-95.580025), for those who have it in use. +MN60_E AltLabel could be kept here, instead of moved to the new location of I-90BL/60.

**updates.csv:**
> 2017-06-22;(USA) Minnesota;I-94;mn.i094;Added point at new MN 610 interchange 

Adding a new point to an existing route doesn't affect any .list files, and is thus not newsworthy.

I suggest the more clean & informative CHM style updates in a few cases...

> 2017-06-16;(USA) Minnesota;MN 5;mn.mn005;Route truncated to MN 120

Truncated from the old east end at MN 36 to the new end at MN 120

> 2017-06-22;(USA) Minnesota;US 14;mn.us014;Route relocated onto Nicollet Bypass

Removed from (description) and relocated onto the southwestern Nicollet Bypass between (pivot waypoint A) and (pivot waypoint B)

> 2017-06-22;(USA) Minnesota;US 59;mn.us059;Route realigned near Worthington
> 2017-06-22;(USA) Minnesota;MN 60;mn.mn060;Route realigned near Worthington 

I'll leave these as an exercise for you, OTOH. :)

> 2017-06-22;(USA) Minnesota;MN 99;mn.mn099;Route truncated to MN 111

Truncated from the old west end at Old Highway 14 to the new end at MN 111

> 2017-06-22;(USA) Minnesota;MN 111;mn.mn111;Route extended south to US 14 Nicollet Bypass

Extended south from Old Hwy 14 to US 14 Nicollet Bypass

> 2017-06-22;(USA) Minnesota;MN 610;mn.mn610;Route extended west to I-94 

Extended west from CR 81/130 to I-94

**Comment by ajfroggie** [comment]
Given that there are no actual roads, but clearly a new alignment bypass, I'd consider the US 14 point "datacheck errors" false positives.  If people are going to be picky about it, I'll make them hidden points and leave it at that.

The Alt labels on the MN 60 and US 59 lists are how I'm internally keeping track that I'm missing the new reroute.

I didn't consider the northern 59/60 junction a significant enough shift (unlike south of town), but I'll consider the Clifton Ave point for the future.

**Comment by yakra** [comment]
> The Alt labels on the MN 60 and US 59 lists are how I'm internally keeping track that I'm missing the new reroute. They're not in use yet because my list update hasn't gone through yet.

Ah, K. "Note to Self" style AltLabels, I personally have no problem with. This was discussed a bit somewhere on the forum recently.

> Given that there are no actual roads, but clearly a new alignment bypass, I'd consider the US 14 point "datacheck errors" false positives. If people are going to be picky about it, I'll make them hidden points and leave it at that.

Brought it up as that was a deprecated labeling style, per discussion on the old forum. WPTedit would throw the [O] ("Label lacks the generic highway type") error. The manual *("make up a name using the former name")* would seem to support this style, though I'll concede it could be more clearly written in this section.
But please don't make them hidden points -- people who need to mark this section as de-clinched will need these points, and need to see them.

**Comment by jteresco** [comment]
I'll hold off on this until I hear it's set for merge.

**Comment by ajfroggie** [comment]
I don't see why it can't be merged now.

**Comment by jteresco** [comment]
OK, I'll merge it in.

**Comment by yakra** [comment]
While the issue of a CHM datacheck may not be *directly* applicable, I brought it up to underscore the fact that Old[numeric designation] labels should have the *type* of designation in them, E.G. OldUS66 or *OldME220.
However, what I cannot argue with is the fact that this PR was merged, and has been for some time now. :)

A little more discussion on #1525...

**Pull request merged**
