### PR TITLE
US 40, PA 21, PA 166, PA 188, PA 221, PA 481, and PA 917 Recentering 

### PR DESCRIPTION
**Pull request by Markkos1992**
Also includes US 40 BUS (Brownsville) and US 40 BUS (Uniontown).

Other Changes:
I-70: Adding +X01A and +X01B for mapping purposes.
US 30: Recentering +X101A.
US 40: Added +X2A, +X2B, Cunningham Rd (CunRd), +X3A, Sunset Beach Rd (SunBeaRd), Weirich Ave (WeiAve), +X4, Hayes Ave (HayAve), Maiden St (MaiStWas_W), Cresent Rd (CreRd_W), Hickory Rd (HicRd), Maiden St (MaiSt_Bea), Richeyville Rd (RicRd), Old National Pike (OldNatPk_B), Ridge Rd (RidRd), Malden Rd (MalRd), Twin Hills Rd (TwinHilRd), Stone Church Rd (StoChuRd) New Salem Rd (NewSalRd), Morgantown Rd (MorRd), Fort Necessity National Battlefield (FortNecNB-http://forum.travelmapping.net/index.php?topic=2947.0), and Dinner Bell-Ohiopyle Rd (DinBOhiRd). Realigned at PA 381. Replaced +X11 with Jumonville Rd (JumRd). Replaced +X13 and +X14 with Braddock Run Rd (BraRunRd), Newberry Rd (NewRd), and Campground Rd (CamRd).
US 40 BUS(Brownsville): Added +X1 to move the line to the south.
US 40 BUS(Uniontown): Lined up with PA 51. Added Hopwood Coolspring Rd (HopColRd).
US 119: Added Fallen Timbers Rd (FalTimRd), Church St (ChuSt), Smithfield-Masontown Rd (SmiMasRd), and York Run Rd.
PA 18: Added Tower Rd (TowRd_A), Garner Run Rd (GarRunRd), Andrew Rd (AndRd), Jolly School Rd (JolSchRd), Maiden Ave (MaiAve_W), and Tower Rd (TowRd_B). Replaced +X01 and +X02 with Garrison Ridge Rd (GarRidRd). Replaced +X03 and +X04 with Rush Run Rd. Replaced +X05A, +X05B, and +X05C with West Run Rd.
PA 21: Added Poland Run Rd (PolRunRd), Murtha Dr (MurDr), Havers Hill Rd (HavHillRd), Dugan Hill Rd (DugHillRd), and Footdale Rd (FooRd). Replaced GarLn and +X00 with Aleppo Rd (AleRd). Replaced +X01, +X02, +X03, OakRd, and +X04 with Hopewell Ridge Rd (HopRidRd), Harvey Hill Rd (HarHillRd), Jacobs Run Rd (JacRunRd), Tower Rd (TowTd), and West Run Rd. Replaced +X03A and +X04A with Rush Run Rd. Replaced CreRd with Kovalchecks Rd (KovRd). Removed BosRd and LitChiRd.
PA 51: Lined up with US 40 BUS (Uniontown). Added Upper Middletown Rd (UppMidRd) and Tippecanoe Rd (TipRd).
PA 88: Added George St (GeoSt), Willis Rd (WilRd), Shortcut Rd (ShoRd), Goslin Rd(GosRd), Clarksville Rd (ClaRd), Barneys Run Rd (BarRunRd), Ridge Rd (RidRd), Pike Run Dr, Dally Rd (DalRd), 1st St, 4th St, and Ginger Hill Rd (GinHillRd). Replaced +X0 with Blaine Hill Rd (BlaHillRd).
PA 136: Added Hazel Kirk Rd (HazKirkRd) and 4th St.
PA 166: Added Cagey School Rd (CagSchRd), Friendship Hill National Historic Site (FriHillNHS-http://forum.travelmapping.net/index.php?topic=2947.0), and Tomcat Hollow Rd (TomHolRd). Replaced 1st St with Grays Landing Hill Rd (GLHillRd). Replaced FaiAve with Church Ave (ChuAve). Replaced OakHillRd with New Salem Rd (NewSalRd).
PA 188: Added Valley Farm Dr (ValFarmDr), Reservoir Hill Rd (ResHillRd), and Pine St. Replaced +X1 with Goslin Rd (GosRd) and Shortcut Rd (ShoRd).
PA 221: Added Meadowbrook Rd (MeaRd), Porter St Ext (PorStExt), Craft Creek Rd (CraCreRd),Cracraft Rd (CraRd), Vaneal Rd (VanRd), Sunset Beach Rd (SunBeaRd), Rural Valley Rd (RurValRd), and Main St (MainSt_W). Replaced LonHolRd with Pie Ridge Rd (PieRidRd). Replaced +X1 with Green Cove Rd (GreCoveRd) and Oak Ridge Rd (OakRidRd).
PA 231: Added Rocky Run Rd (RocRunRd) and Pleasant Grove Rd (PleGroRd).
PA 331: Added Poplar Rd (PopRd), Oak Ridge Rd (OakRidRd), Cherry Rd (CheRd), Green Cove Rd (GreCoveRd), and Reed Rd.
PA 381: Realignment of road at US 40. (https://www.penndot.gov/RegionalOffices/district-12/pages/details.aspx?newsid=466)
PA 481: Added Spur Rd, Pike Run Dr, Deems Park Rd (DeeParkRd), Woodland Rd (WooRd), Grange Rd (twice-GraRd_A and GraRd_B), California Dr (CalDr), Old Route 71 (OldRt71), and Shannon Rd (ShaRd). Replaced +X1 with Old National Pike (OldNatPk_W). Replaced+X3 with Van Voorhis Hazelkirk Rd (VVHazRd).
PA 837: Added 4th St.
PA 917: Added Hickory Rd(HicRd), Almond Rd(AlmRd), Beallsville Rd(BeaRd), and Washington St(WasSt).

### CODE REVIEW

**Comment by rickmastfan67** [comment]
Would appreciate a '@' mention @Markkos1992 when you update a WV file so I can keep my 'offline' copies synced since I'm still working on the WV overhaul since I do it manually without the aid of GitHub (personal preference). ;)

**Comment by Markkos1992** [comment]
@rickmastfan67- For WV, I updated border points for US 40 and WV 891.

@Duke87ofST-For MD, I updated the border point for US 40.

I’ll note this in separate Github comments moving forward when I edit border points.  This way it will be clearer and concise to everyone.

I do not know if my @‘s will work replying via email.

-Mark

Mark Moore

Civil and Environmental Engineering
Virginia Tech Class of 2014
markm10@vt.edu
(804)691-4381

**Comment by rickmastfan67** [comment]
> @rickmastfan67- For WV, I updated border points for US 40 and WV 891.

If you did for US-40, it didn't make it into this pull request.

And no, the '@' didn't work via email.  Seems to only work if you're replying directly on GitHub.

**Comment by Markkos1992** [comment]
You are correct on US 40.  My apologies.

Mark Moore

Civil and Environmental Engineering
Virginia Tech Class of 2014
markm10@vt.edu
(804)691-4381

**Comment by ovoss** [comment]
In PA 381, +US40_W was added as an alternate label to *OldPA381. I had US40_W in the PA PA381 entry in my list file. The new version credits with a short new segment of PA 381 that I never traveled, since in that area I never left US 40, and I never traveled any other part of PA 381.

I know you've trying not to break list files, but this was a case where the file needed to be broken,

 I'll shortly remove the PA381 entry from my list file, as well as about two dozen other PA entries that are only concurrences with other routes. In CHM days, entries for such concurrencies were necessary, but no longer, so I can streamline my list file a little.

**Comment by michihdeu** [comment]
> I know you've trying not to break list files, but this was a case where the file needed to be broken,

I think that we generally try to not break any list file if it's possible. I don't like this policy and even prefer breaking list files over giving creadit for anything one never has traveled. I think that every relevant change (noted in updated.csv) should create an error and take mileage away so that everyone needs to look into it and decide whether one wants to ignore that alignment has changed or getting a gap. We lack of the technic right now but that's I would try to aiming for. Just my $0.02 😃

**Comment by Markkos1992** [comment]
@oscar,  I removed the US40_W alternate label.  I definitely was not thinking as I made the same mistake I made on I-95 6 months ago.

https://github.com/TravelMapping/HighwayData/pull/2677

**Pull request merged**
