### PR TITLE
CT I-395: sequential -> milepost

### PR DESCRIPTION
**Pull request by yakra**
No .list files are affected.
No updates entry necessary.

### CODE REVIEW

**Comment by rickmastfan67** [comment]
I think when a highway has a complete renumbering, a mention should be made for the update page.  We've done that before when we've had to 're-enter' a highway because of the entire highway getting new numbers.

Something simple like this would have worked IMO:
Converted highway exit numbers to brand new mileage based ones from previous sequential based exit numbers.

Do you agree with me on this @jteresco?

**Comment by jteresco** [comment]
No harm putting in an update entry.  Those with the old numbers will see an entry in their log saying that the old point was replaced, but might as well inform those who might just want to fix up their numbers right away.

**Comment by yakra** [comment]
Agreed, no harm in an update entry.

**Comment by jteresco** [comment]
I am putting in an update entry that will show up later tonight on the site.

**Pull request merged**
