### PR TITLE
cannf and NV changes

### PR DESCRIPTION
**Pull request by ovoss**
Datacheck attempt pending

### CODE REVIEW

**Comment by ovoss** [comment]
Datacheck successful, run from dying laptop. But for some reason, edit to nv.nv157 (to re-synch with nv.us095) didn't make it into pull request. Will need a small followup PR from my new laptop, probably tomorrow.

**Comment by rickmastfan67** [comment]
@jteresco @yakra Will the 'blank' line that was randomly added to the beginning of US-93's file hurt the site update?

**Comment by ovoss** [comment]
> @jteresco @yakra Will the 'blank' line that was randomly added to the beginning of US-93's file hurt the site update?

I pushed a commit to remove the blank line.

No changes were made to the US 93 route file, since we decide not to add a point for exit 43 in that or the I-15route file. We could remove the US 93 item from the PR.

**Comment by jteresco** [comment]
Seems like there's some discussion on the forum about this, so I'm going to hold off until I get word that this is good to go.

**Comment by ovoss** [comment]
I suggest pulling in the PR, then doing any necessary changes (including to the NV 157/US 95 junction) tomorrow or Friday.

The blank line rickmastfan mentioned has already been removed.

Oscar

**Comment by jteresco** [comment]
Great, thanks!  It's going in for tonight.

**Comment by yakra** [comment]
@rickmastfan67 [wrote](https://github.com/TravelMapping/HighwayData/pull/6353#issuecomment-1413010241):
> @jteresco @yakra Will the 'blank' line that was randomly added to the beginning of US-93's file hurt the site update?

@ovoss fixed it, but I'll respond anyway:
Nope! That was a [nasty bug](https://github.com/TravelMapping/DataProcessing/issues/443#issuecomment-874242306) a year and a half ago that I went to great pains to fix. :rofl:

**Pull request merged**
