### PR TITLE
ENG A683 Lancaster Northern Bypass

### PR DESCRIPTION
**Pull request by si404**
2016-10-31;(UK) England;A683;eng.a683;Removed from Morecambe Road and Caton Road, and relocated onto The Bay Gateway, between eastern junction with the A589 and junction with the M6

### CODE REVIEW

**Comment by si404** [comment]
2016-10-31;Denmark;PR14;Route truncated at south end from PR22 junction to PR54/O2 junction
2016-10-31;Denmark;PR54;Route removed from Køgevej between Ringstedgade and O2, and relocated onto Ring Nord between O2_E and PR22
2016-10-31;Denmark;O2 (Næstved);dnk.pro2nae;New Route

**Comment by jteresco** [comment]
Looks like 2 updates entries failed - will check it out tomorrow unless someone beats me to it.

**Comment by michihdeu** [comment]
Only file root column is missing:
2016-10-31;Denmark;PR14;**dnk.pr14**;Route truncated at south end from PR22 junction to PR54/O2 junction
2016-10-31;Denmark;PR54;**dnk.pr54**;Route removed from Køgevej between Ringstedgade and O2, and relocated onto Ring Nord between O2_E and PR22

**Comment by jteresco** [comment]
Thanks, fixing.

**Pull request merged**
