### PR TITLE
More usaar

### PR DESCRIPTION
**Pull request by mapcat**

### CODE REVIEW

**Comment by jteresco** [comment]
@mapcat I had to comment out usaar for tonight's update since the usaar_con.csv file was improperly formatted.  I think it might have been a copy of usaar.csv that got mistakenly named usaar_con.csv.

**Comment by mapcat** [comment]
Crap. I don't know why that happened. I will resubmit.

**Comment by mapcat** [comment]
They should be fixed now. Sorry for the trouble.

**Comment by jteresco** [comment]
I don't see a new pull request yet.

**Comment by jteresco** [comment]
I'll run an update in the morning if the new csv is ready to go.

**Comment by mapcat** [comment]
Just submitted it

**Pull request merged**
