### PR TITLE
CA Interstates cleanup part 6

### PR DESCRIPTION
**Pull request by ovoss**
Completes updates for CA Interstates, including I-5 and most northern California Interstates. Some affected US and in-dev state routes also modified.

If no glitches, this should complete work on issue #30, with all CA routes in active systems fully updated and synched.

### CODE REVIEW

**Comment by yakra** [comment]
Nota bene: This branch has conflicts that must be resolved

**Comment by ovoss** [comment]
Any idea of what conflict(s)? When I made the pull request a few hours ago, no conflicts were noted.

**Comment by jteresco** [comment]
I doubt they'll cause much if any trouble.  I'll take care of it today.

**Comment by yakra** [comment]
When there are conflicts, is there a way to view what they are?

**Comment by jteresco** [comment]
I haven't found a way through the web interface to view the conflicts.  When I follow the command line instructions, I can just look for the specially marked areas of the file and decide which version (or possibly both when we've had updates conflicts) should be kept.

I should be able to resolve this and bring in the other requests tonight, then I'll run a site update.

**Comment by jteresco** [comment]
The conflict is 2 versions of exits 4A and 4B in I-305:

`<<<<<<< HEAD
4A http://www.openstreetmap.org/?lat=38.568367&lon=-121.510838
4B http://www.openstreetmap.org/?lat=38.567268&lon=-121.506515
=======
4A http://www.openstreetmap.org/?lat=38.568367&lon=-121.510822
4B http://www.openstreetmap.org/?lat=38.567230&lon=-121.506553
>>>>>>> master
`
I'm somewhat arbitrarily choosing the first two.  Please commit a new change later if it should be the other.

**Comment by ovoss** [comment]
Jim:

A fix will be needed, but I'll wait until the site update is complete before 
composing the fix. 4B needs to be re-synched in files for three routes 
concurrent in downtown Sacramento (I-305, I-80BLSac, US 50), and 4A (I-5 
waypoint 518) in those files and I-5's.

Oscar

----- Original Message -----

**Comment by jteresco** [comment]
I'm done making changes for now, so please go ahead and get the fix in there at your convenience.

**Pull request merged**
