### PR TITLE
GA: Updating incorrect exit numbers on I-16.

### PR DESCRIPTION
**Pull request by rickmastfan67**
Moved I-16 '1' to the interchange with I-75.  Corrected former label for US-23/US-129 interchange from 1 > 1A.

http://clinched.s2.bizhat.com/viewtopic.php?p=16088

Hopefully I've done everything correctly.

### CODE REVIEW

**Comment by jteresco** [comment]
Thanks - anything here that will need an entry in the updates log?  I'll see about getting these into the system tomorrow some time.

**Comment by rickmastfan67** [comment]
I just think a mention about the exit number changes on I-16 since '1' was in user before.

This was the entry I had written up for Tim last year for this change:

(USA) Georgia I-16: Relabeled waypoint I-75 as 1 and previous waypoint 1 as 1A (US 23 & US 129; Spring Street) in Macon.

**Comment by yakra** [comment]
Hi guys. Ping!

**Comment by rickmastfan67** [comment]
Glad you're in now yakra. ;)

**Comment by yakra** [comment]
Not without trouble. Email is still unverified, though I may be able to proceed that way nonetheless.
Attempts to change my avatar are doing nothing.
And then there's still the small matter of learning the software...

**Comment by rickmastfan67** [comment]
The web interface is easy enough to figure out it seems.  You can pretty much can just copy and paste an entire file if you had made fixes in the past that aren't online yet to sync it with your local copy.

**Comment by yakra** [comment]
I'll start by having a look at the tutorial Jim wrote up, and also check out the Hello World tutorial here on GitHub. Meanwhile, the fact that I can't do such a simple thing as change my avatar is infuriating me. Or delete the repository I created as a test. %$)(*)!... guess I'll update Firefox and see how that works out...

**Comment by jteresco** [comment]
Could you see if you can add an updates.csv entry for it to this pull request, or create a second pull request with the updates.csv entry?

**Comment by rickmastfan67** [comment]
Just use the text 'update' I had for Tim, or do it in another way?

**Comment by jteresco** [comment]
Follow the model Si has started in the hwy_daya/updates.csv file as best you can.  The actual description should probably continue to use Tim's guidelines until we come up with something else.

**Comment by rickmastfan67** [comment]
I'll do that once I can figure out how to get GitHub to sync my copy with the master copy.

**Comment by rickmastfan67** [comment]
Looks like I need to make it as a new pull request.  See #25.

**Pull request closed without merging**
