### PR TITLE
Qc a routes canges phase 2

### PR DESCRIPTION
**Pull request by ovoss**
Updates to QC A-5, A-73, A-85, and TCH (Main), as well as related changes to west end of NB TCH (Main) and NB2. Also includes tweaks to just-submitted A-410 and A-730 -- PLEASE PROCESS PHASE 1 UPDATES FIRST, BEFORE THIS PHASE 2.

Updates text:

15-08-18;(Canada) Quebec;A-5;qc.a005;Extended north to Wakefield, absorbing former A-5 (Wakefield)

15-08-18;(Canada) Quebec;A-5 (Wakefield);(NONE);Route deleted, folded into rest of A-5

15-08-18;(Canada) Quebec;A-73 (St-Georges):qc.a073stg;Route added

15-08-18;(Canada) Quebec;A-85 (Notre-Dame-du-Lac);qc.a085not;Route added

15-08-18;(Canada) Quebec TCH (Main);qc.tchmai;East end moved to new A-85 freeway, from Ch. du Golf (*OldQC185_D - exit 40), Ch. du Lac (*OldQC185_C - *OldQC185_A), and Av. de la Madawaska (exit 14 - QC/NB border)

15-08-18:(Canada) New Brunswick;NB 2;nb.nb002;Moved from Madawaska Ave. to new freeway between QC/NB border and exit 1

15-08-18:(Canada) New Brunswick;TCH (Main).nb.tchmai;Moved from Madawaska Ave. to new freeway between QC/NB border and exit 1

### CODE REVIEW

**Comment by ovoss** [comment]
The A-85, TCH, and NB 2 changes address issue #35.

**Comment by jteresco** [comment]
File missing: qc.a073stg.wpt

**Comment by jteresco** [comment]
Feel free to email it to me if it's easier than opening a new pull request or adding  a branch to this one.

**Comment by jteresco** [comment]
I'm not sure what caused it or what to do about it yet, but this pull caused the encoding of the canqca csv files to change from utf-8 to iso-8859-1, which broke my Python program.  Another bit of Python converted it back (to be committed/pushed soon).  For now, if whatever you use to edit can be forced to utf-8, let's do that.

**Comment by ovoss** [comment]
I use WordPad to make minor edits to both .wpt and .csv files. I usually 
save as plain text (as I did this time), but can try the "save as Unicode 
text" option to see if it gives you the encoding you need. Let me know if 
you want me to resubmit.

I also wonder whether the French-language characters in some city names in 
the .csv files threw things off, and whether some of that didn't survive the 
encoding conversion(s).

----- Original Message -----

**Comment by jteresco** [comment]
The only problems were in the French characters, yes.  No need to resubmit.  I've made the fixes and pushed them up to the master.  I think trying the Unicode text option next time might be worth a shot, thanks.

**Comment by jteresco** [comment]
I poked around in your fork of the repository but didn't see the qc.a073stg.wpt file there either.  Maybe it's just in your local copy.  Anyway, it's easy enough for me to add it in (and put back the .csv entries) whenever you can send that one along.

**Comment by jteresco** [comment]
I have the file and it will be in tonight's DB update.

**Pull request merged**
