### PR TITLE
AR cleanup 2015-12-10

### PR DESCRIPTION
**Pull request by yakra**
addresses #244 & #247 and a few other odds & ends.

2015-12-10;(USA) Arkansas;I-69 Future (Texarkana, AR);;Route deleted (merged into I-49 (Texarkana, AR))

### CODE REVIEW

**Comment by rickmastfan67** [comment]
Shouldn't the entry be for I-130 and not I-69?

**Comment by yakra** [comment]
@rickmastfan67: It should be. Copy/paste fail! :(

-----
Should read:

2015-12-10;(USA) Arkansas;I-130 Future (Texarkana, AR);;Route deleted (merged into I-49 (Texarkana, AR))

**Comment by jteresco** [comment]
Fixed in updates.csv and another update being launched anyway to get my new miles on the Saw Mill and the Cross County, so we'll see it in 15-20 minutes.

**Comment by yakra** [comment]
That reminds me, I forgot to add those routes to my list file. HA!
Next time...

**Comment by jteresco** [comment]
Send them - I'll run another update tonight to get the new NM fixes in.

**Comment by yakra** [comment]
Done. Thanks.

**Pull request merged**
