### PR TITLE
Various usaca updates

### PR DESCRIPTION
**Pull request by ovoss**
As discussed in my post on the forum. Many of these routes have been fully updated, Others (including one active usaus route) partially updated for relabels and synching with newly-finalized routes.

### CODE REVIEW

**Comment by jteresco** [comment]
I think CA 12's label CA12/29 should refer to CA 121 instead of CA 12.

**Comment by ovoss** [comment]
Yes. I'll fix that in the next set of updates.

----- Original Message -----

**Comment by ovoss** [comment]
I'd run the file through CHM's waypoints editor, to try to catch the errors 
I sometimes get when I manually splice in points from a concurrent route 
file so that they stay in synch. Our Datacheck seems better at catching such 
"selfref" errors than the waypoint editor, though of course I can't use 
Datacheck to spot and fix them before submission.

The label is corrected to CA29/121 in my local copy of the CA12 route file.

----- Original Message ----- 
From: "Oscar Voss" <oscar.voss@comcast.net>
To: "TravelMapping/HighwayData" 
<reply@reply.github.com>
Sent: Monday, July 31, 2017 8:40 PM
Subject: Re: [TravelMapping/HighwayData] Various usaca updates (#1488)


> Yes. I'll fix that in the next set of updates.
>
> ----- Original Message ----- 
> From: Jim Teresco
> To: TravelMapping/HighwayData
> Cc: ovoss ; Author
> Sent: Monday, July 31, 2017 8:05 PM
> Subject: Re: [TravelMapping/HighwayData] Various usaca updates (#1488)
>
>
> I think CA 12's label CA12/29 should refer to CA 121 instead of CA 12.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
>
> --
> Oscar Voss - ovoss@pobox.com (old address still works) - Arlington VA
>
> my Hot Springs and Highways pages:
> http://www.alaskaroads.com/home.html


--
Oscar Voss - ovoss@pobox.com (old address still works) - Arlington VA

my Hot Springs and Highways pages:
http://www.alaskaroads.com/home.html

**Comment by jteresco** [comment]
Thanks.  Another reason we need our own waypoint editor-- it could read in from the current DB.

**Pull request merged**
