### PR TITLE
tourist routes + Macedonia

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by jteresco** [comment]
Missed this morning's special update by minutes.  This looks like the kind of large update that really would benefit from testing with the datacheck.sh script.

**Comment by michihdeu** [comment]
I don't think that E25/E80 are signed there...

**Comment by si404** [comment]
They clearly aren't signed there, given that, until this morning they went over the bridge - there's been far more important stuff for people to do than put up some cartouches. However it's clearly the diversion route for that traffic.

**Comment by michihdeu** [comment]
I don't like it but accept it.

**Comment by jteresco** [comment]
Commented out eurtr for tonight's update.  Here's the error log.

<pre>
[136.9] Performing data checks.ABORTING due to 52 errors:
1: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.borhistr.wpt'
2: Route contains fewer than 2 points: eng.borhistr (0 total points)
3: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.jurcoard.wpt'
4: Route contains fewer than 2 points: eng.jurcoard (0 total points)
5: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.norcr.wpt'
6: Route contains fewer than 2 points: eng.norcr (0 total points)
7: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.holrd.wpt'
8: Route contains fewer than 2 points: eng.holrd (0 total points)
9: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.a1120tr.wpt'
10: Route contains fewer than 2 points: eng.a1120tr (0 total points)
11: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.fosway.wpt'
12: Route contains fewer than 2 points: eng.fosway (0 total points)
13: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.lanendtr.wpt'
14: Route contains fewer than 2 points: eng.lanendtr (0 total points)
15: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.lowfurcr.wpt'
16: Route contains fewer than 2 points: eng.lowfurcr (0 total points)
17: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.pswtr.wpt'
18: Route contains fewer than 2 points: eng.pswtr (0 total points)
19: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.tawvaltr.wpt'
20: Route contains fewer than 2 points: eng.tawvaltr (0 total points)
21: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.utttr.wpt'
22: Route contains fewer than 2 points: eng.utttr (0 total points)
23: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.ekct.wpt'
24: Route contains fewer than 2 points: eng.ekct (0 total points)
25: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.hkct.wpt'
26: Route contains fewer than 2 points: eng.hkct (0 total points)
27: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.hwct.wpt'
28: Route contains fewer than 2 points: eng.hwct (0 total points)
29: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.rmrct.wpt'
30: Route contains fewer than 2 points: eng.rmrct (0 total points)
31: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.kiefordr.wpt'
32: Route contains fewer than 2 points: eng.kiefordr (0 total points)
33: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.mlt.wpt'
34: Route contains fewer than 2 points: eng.mlt (0 total points)
35: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.bwtra.wpt'
36: Route contains fewer than 2 points: eng.bwtra (0 total points)
37: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.cidrt.wpt'
38: Route contains fewer than 2 points: eng.cidrt (0 total points)
39: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.dudtt.wpt'
40: Route contains fewer than 2 points: eng.dudtt (0 total points)
41: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.elgrt.wpt'
42: Route contains fewer than 2 points: eng.elgrt (0 total points)
43: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.fordeansd.wpt'
44: Route contains fewer than 2 points: eng.fordeansd (0 total points)
45: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.temevalld.wpt'
46: Route contains fewer than 2 points: eng.temevalld (0 total points)
47: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.ywsdbev.wpt'
48: Route contains fewer than 2 points: eng.ywsdbev (0 total points)
49: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.ywsdbri.wpt'
50: Route contains fewer than 2 points: eng.ywsdbri (0 total points)
51: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ENG/eurtr/eng.ywsdpoc.wpt'
52: Route contains fewer than 2 points: eng.ywsdpoc (0 total points)
</pre>

**Pull request merged**
