### PR TITLE
BW

### PR DESCRIPTION
**Pull request by michihdeu**

### CODE REVIEW

**Comment by michihdeu** [comment]
@jteresco, please update the test DB with highway data and my user list file. Thank you!

**Comment by jteresco** [comment]
Got some errors.  I'll check them out later unless you beat me to it:

`ABORTING due to 6 errors:
1: System mismatch parsing line [espab;ESP-MD;E5;;;Madrid;espmd.e5;], expected eureb
2: System mismatch parsing line [espab;ESP-CM;E5;;Ses;Sesena;espcm.e5ses;], expected eureb
3: System mismatch parsing line [espab;ESP-MD;E5;;Ara;Aranjuez;espmd.e5ara;], expected eureb
4: System mismatch parsing line [espab;ESP-CM;E5;;;Manzanares;espcm.e5;], expected eureb
5: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ESP-GA/espnb/espga.n536que.wpt'
6: Route contains fewer than 2 points: espga.n536que (0 total points)
`

**Comment by si404** [comment]
Gah, I do 5856265 half-asleep and Michael does a superior pull request #1565. Thankfull Github's web interface allowed me to sort the conflict out.

**Comment by michihdeu** [comment]
I was not sure about N535Que and fixed error 1-4 only (Si also forgot error 5/6). AFTERWARDS, I thought that it's less than 1km border to border only and I should add it. After sync I got a conflict too. The csv file was broken and I couldn't figure it out. I deleted my repository and downloaded the whole shit again. It seems to work again... #1566

**Comment by jteresco** [comment]
I merged everything in and pulled down the latest, but still get the same set of errors above when I try to do a test DB update.

**Comment by michihdeu** [comment]
Not possible, [eureb.csv](https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/eureb.csv) has no `espab` entries anymore and [espga.n536que.wpt](https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/ESP-GA/espnb/espga.n536que.wpt) exists. It's the main branch... Odd...

**Comment by jteresco** [comment]
Good now.  Maybe I did the pull before the merge.  But whatever it was, we're good.  Test DB updated.

**Pull request merged**
