### PR TITLE
csv fixes for #795

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by si404** [comment]
working?

**Comment by jteresco** [comment]
Thought so, but hwy_data/KOR/asiah/kor.ah006.wpt is missing. Looks like it's in asiahp in the directory hierarchy.

**Comment by si404** [comment]
that should do it.

**Comment by jteresco** [comment]
Next one missing: hwy_data/CHN-SX/chng/chnsx.g05.wpt

**Comment by jteresco** [comment]
And another: hwy_data/AFG/asiah/afg.ah062.wpt

Going to comment out for now, but won't commit the systems.csv with chng and asiah commented out.

**Pull request merged**
