### PR TITLE
TN: TN 109 realignment and new I-65 exit 121

### PR DESCRIPTION
**Pull request by mapcat**

### CODE REVIEW

**Comment by rickmastfan67** [comment]
I think that the 'TN 109' mention in the US-31W update shouldn't have a space in it since you're specifically mentioning the point label being moved.

**Comment by mapcat** [comment]
True, that was unintentional. @jteresco can you fix it?

**Comment by jteresco** [comment]
Done.

**Comment by mapcat** [comment]
Thanks!

**Pull request merged**
