### PR TITLE
Adding SC NMP FPs

### PR DESCRIPTION
**Pull request by Markkos1992**
@michihdeu,  I just want to note that a couple of your files were originally inadvertently changed (deurp.l145 and deurp.1415).

I believed I have fixed those issues using the latest master files.

### CODE REVIEW

**Comment by michihdeu** [comment]
@Markkos1992 There seem to be more issues also with files from other contributors. Changes from June are undone and I don't have the time to go through all (my nor of all contributors) files. Please make sure that you don't change file by accident.

**Comment by Markkos1992** [comment]
I was using this secondarily as a chance to sync my master branch to the master Travel Mapping branch.

How two other files were accidentally (temporarily) changed?  I really do not know.

I definitely will be checking moving forward to make sure that only the files I intended to edit were edited.  Thankfully, I caught that and fixed the other files in this case.

**Comment by yakra** [comment]
@si404 wrote in https://github.com/TravelMapping/HighwayData/pull/3345#issuecomment-557830041:
> I forgot to close and reopen updates.csv over the sync up with the master branch.

**Comment by yakra** [comment]
Not sure if that applies here, or how other contributors' files would have gotten mucked up, but anyway.

The reversions checked out OK for my files, and checking their blame in @Markkos1992 's branch, it looked like these cases weren't even registering as new commits.

For example, now that it's merged into master, I'm still [blamed](https://github.com/TravelMapping/HighwayData/blame/master/updates.csv) for `2019-09-02;(Canada) Nova Scotia;NS 245;ns.ns245;Extended eastward from NS 227 to NS 4.`

**Comment by yakra** [comment]
What I think happened:
The changes to other contribs' files (or files with multiple maintainers such as updates.csv) didn't represent actual edits to the underlying files as such, not an *edit* commit -- but the *merge* commit that updated them in @Markkos1992's fork.
All that got reverted was the merge commit that synced `Markkos1992:master` or `Markkos1992:PA-I-90/US-20` etc to `TravelMapping:master`.
For example, at https://github.com/Markkos1992/HighwayData/pull/206 right near the top of the list, I see a couple of my own commits. My files were in fact edited by me.

So everything's fine, just a little funny-looking.

**Pull request merged**
