### PR TITLE
Short HI 380 relocation

### PR DESCRIPTION
**Pull request by ovoss**
Short part of HI 380 closed and relocated to tie route into new Airport Access Rd. (access road route signage not yet known). Waypoint for access road added to HI 36 route file.

Update entry (needed only for HI 380):

2015-11-17;(USA) Hawaii;HI 380;hi.hi380;Route relocated from closed Dairy Rd. segment between waypoints AirAccRd and PakSt_N, onto parts of Airport Access Rd. and Pakaula St.

### CODE REVIEW

**Comment by ovoss** [comment]
Please ignore the first two commits listed above. The third one (which corrects changes from the first two commits) is the correct one.

**Comment by ovoss** [comment]
Jim, the Updates entry was merged in, but not the updated HI 36 and HI 380 
route files.

--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages (NEW ADDRESS):
http://www.alaskaroads.com/home.html

**Comment by jteresco** [comment]
Oops, forgot a step.  Re-running update now.

**Comment by ovoss** [comment]
The correct versions of both updated files are now in the HB. Thanx.

--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages (NEW ADDRESS):
http://www.alaskaroads.com/home.html

**Pull request merged**
