### PR TITLE
Split WA 99 into two sections

### PR DESCRIPTION
**Pull request by compdude**
WA 99 is being split into two sections to reflect the fact that it has a gap in Tukwila. The northern section is going to be called wa.wa099sea.wpt, and the southern section will remain as wa.wa099.wpt. See forum thread: http://tm.teresco.org/forum/index.php?topic=445.0

### CODE REVIEW

**Comment by jteresco** [comment]
This one definitely needs to include a good updates entry.

**Comment by compdude** [comment]
Oh yeah, forgot about that...

**Comment by compdude** [comment]
Okay, how does that update entry look to you?

**Comment by jteresco** [comment]
I'll let others make a final call, but it seems reasonable.

**Comment by jteresco** [comment]
I'll merge this in for tonight's site update, but we can still update the updates entry if deemed necessary.

**Comment by yakra** [comment]
The northern (Seattle) should be the main WA99 segment (no Abbreviation), as it's the longer segment.
The southern segment should be the one with a City/Abbrev. Des Moines, perhaps?

**Comment by jteresco** [comment]
I'm making the change suggested by @yakra, but using Federal Way as the city/abbrev.

**Pull request merged**
