### PR TITLE
sctb

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by jteresco** [comment]
Many pages of errors I don't have a chance to investigate tonight:

`ABORTING due to 1315 errors:
1: Could not find Route matching root sct.b0817 in system gbnb.
2: No roots in _con.csv line [gbnb;B817;;;sct.b0817]
3: Could not parse _con.csv line: [gbnb;B900;;;sct.b0900;] expected 5 fields, found 6
4: Could not find Route matching root sct.b8052 in system gbnb.
5: No roots in _con.csv line [gbnb;B8052;;;sct.b8052]
6: Check FAILED: 35230 routes != 35229 connected route roots.
7: route sct.b8043 not matched by any connected route root.
8: Duplicate list name: SCT B8024
9: Duplicate list name: SCT B8024
10: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/IRL/irln/irl.n018ora.wpt'
11: Route contains fewer than 2 points: irl.n018ora (0 total points)
12: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/SCT/gbnb/sct.b0700.wpt'
13: Route contains fewer than 2 points: sct.b0700 (0 total points)
`

Then about 1300 more similar errors, guessing a directory rename or something.

**Comment by si404** [comment]
This is very odd as I've double checked and the database shouldn't be looking at 'system gbnb' as I commented it out of systems.csv.

 Also 10: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/IRL/irln/irl.n018ora.wpt' 11: Route contains fewer than 2 points: irl.n018ora (0 total points) is most odd as this is unrelated and is a route I took out of .csvs in the same commit where I removed the file.

I'll have a more detailed look later.

**Comment by jteresco** [comment]
You're right - gbnb is commented out.  Maybe somehow I launched the site update before the pull completed or something.  I'll re-run.

**Comment by si404** [comment]
there were a couple of genuine errors that I fixed in the pull request just now made.

**Comment by jteresco** [comment]
OK, good.  Merged in and rerunning.

**Pull request merged**
