### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Bickendan**
Corrected label 'CreCreLp_E' to 'CryCreLp_E'

### CODE REVIEW

**Comment by yakra** [comment]
looks like this is in the *HighwayData/* root directory instead of *hwy_data/OR/usaus/or.us020.wpt*

**Comment by compdude** [comment]
@Bickendan, you still need to fix this... ;)

**Comment by Bickendan** [comment]
Did a pull request 3 nights ago that should have corrected this.

**Comment by compdude** [comment]
Are you sure? I didn't see one...

**Comment by yakra** [comment]
@jteresco, note my comment above. This has resulted in [a file that is where it should not be](https://github.com/TravelMapping/HighwayData/blob/master/or.us020.wpt)

**Comment by michihdeu** [comment]
Something went wrong, Bickendan has corrected it but for any reason his pull request is... hidden or wasn't submitted correctly?!? I think @Bickendan should check again why his pull request wasn't successful and maybe contact Jim if another attempt fails.

The minor issue is that the file should be moved which could be done by anyone of us if Bickendan cannot do it for any reason...

**Comment by jteresco** [comment]
It looks like the file has many changes other than the label fix mentioned.  Is that intentional?  I'll wait until I find out for sure before replacing correctly-located file with the one from this PR.  Here's the diff between the misplaced new file with what's currently in the correct place for the same route:

```
% diff or.us020.wpt ~
21c21
< CreCreLp_E http://www.openstreetmap.org/?lat=44.627932&lon=-123.764967
---
> CryCreLp_E http://www.openstreetmap.org/?lat=44.627932&lon=-123.764967
83c83
< OR228 https://www.openstreetmap.org/?lat=44.397593&lon=-122.735953
---
> OR228 http://www.openstreetmap.org/?lat=44.397593&lon=-122.735953
128,129c128,129
< OR126_W http://www.openstreetmap.org/?lat=44.421398&lon=-122.001200
< OR22 http://www.openstreetmap.org/?lat=44.436752&lon=-121.940088
---
> OR126_W http://www.openstreetmap.org/?lat=44.421674&lon=-122.000985
> OR22 http://www.openstreetmap.org/?lat=44.436568&lon=-121.939788
143c143
< IndForRd https://www.openstreetmap.org/?lat=44.357978&lon=-121.612730
---
> IndForRd http://www.openstreetmap.org/?lat=44.357970&lon=-121.612730
145c145
< OR242 https://www.openstreetmap.org/?lat=44.291580&lon=-121.555395
---
> OR242 http://www.openstreetmap.org/?lat=44.291580&lon=-121.555395
210c210
< +x2(US395) http://www.openstreetmap.org/?lat=43.520965&lon=-119.270024
---
> +x2(US395) http://www.openstreetmap.org/?lat=43.520996&lon=-119.269595
214,216c214,216
< +x5(US395) https://www.openstreetmap.org/?lat=43.523624&lon=-119.099908
< CR128 http://www.openstreetmap.org/?lat=43.525806&lon=-119.084888
< CR127 http://www.openstreetmap.org/?lat=43.546526&lon=-119.084544
---
> +x5(US395) http://www.openstreetmap.org/?lat=43.523531&lon=-119.099908
> CR128 http://www.openstreetmap.org/?lat=43.525993&lon=-119.085060
> CR127 http://www.openstreetmap.org/?lat=43.546713&lon=-119.084716
218,222c218,222
< HinBlvd http://www.openstreetmap.org/?lat=43.579876&lon=-119.069867
< MonSt http://www.openstreetmap.org/?lat=43.585757&lon=-119.061692
< OR78 https://www.openstreetmap.org/?lat=43.586039&lon=-119.054418
< BroAve https://www.openstreetmap.org/?lat=43.594253&lon=-119.054337
< US395_N https://www.openstreetmap.org/?lat=43.614104&lon=-119.020000
---
> HinBlvd http://www.openstreetmap.org/?lat=43.579386&lon=-119.070382
> MonSt http://www.openstreetmap.org/?lat=43.585516&lon=-119.062121
> OR78 http://www.openstreetmap.org/?lat=43.586023&lon=-119.054418
> BroAve http://www.openstreetmap.org/?lat=43.594160&lon=-119.054348
> US395_N http://www.openstreetmap.org/?lat=43.614104&lon=-119.020000
```

**Comment by Bickendan** [comment]
The misplaced US 20 can be disregarded and removed. I forgot to do the pull
request when I uploaded the tweaks I made a few days ago.
Jim, before you merge my incoming pull request, can you back up the OR
I-84? For some reason, it's showing that the new pull is changing every
line, but I don't see any differences... and don't want the lovely
concurrency breakage with US 30 you corrected a bit ago to haunt us again.
This pull should be correcting a missing shapepoint on US 30 along I-84.

**Comment by jteresco** [comment]
I will remove the bad US 20.  See the new PR for a further comment about the conflicts in your new files.

**Pull request merged**
