### PR TITLE
Activate usamt

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by jteresco** [comment]
Looking for general comment: do we want to include new devel systems in the system updates list?  I am not sure we want end users doing much with devel systems, and it might be cluttering the list for the preview and active entries that the average user would be more interested in.

**Comment by si404** [comment]
I'm very happy to not put devel systems in there. It would also be nice to have them as opt-in on the Highway Browser rather than clutter it.

**Comment by si404** [comment]
I've made a pull request removing the devel entries https://github.com/TravelMapping/HighwayData/pull/411

**Comment by michihdeu** [comment]
I absolutely agree that devel systems should not be in the list. I also think that end users should not get in touch with devel systems per default (I think we've already discussed about it on the "old" forum". I'll add an issue that devel systems should not be displayed (per default) in the HB.

**Comment by yakra** [comment]
I agree; let's keep devel systems out of systemupdates.csv

**Comment by michihdeu** [comment]
@yakra, if we show them in the HB, what should "normal end user" do with them? I think Jim has suggested on the AAroads forum that they should not be displayed there.
I don't like that new systems directly appear in the HB without notification in the system update list to avoid confusing "normal end user".

**Comment by si404** [comment]
I've removed the devel lines from systemsupdate.csv

**Pull request merged**
