### PR TITLE
Minor fix for PA US-322 Business (State College).

### PR DESCRIPTION
**Pull request by rickmastfan67**
Fixed location for 'US322_W' to re-sync route with mainline US-322 (and I-99/US-220).  Also added in one additional point at the most logical road that connects to I-99 Exit #71.  See: http://clinched.s2.bizhat.com/viewtopic.php?t=2388&mforum=clinched

### CODE REVIEW

**Comment by jteresco** [comment]
Looks simple enough, going to pull it in.

**Comment by jteresco** [comment]
Note that the new line used a different OSM URL format than the one our wpt file format supports.  Fixed in master copy, so no worries, but something to keep in mind.

**Comment by rickmastfan67** [comment]
Oops, my bad.  Must have striped out that part by accident when taking out the zoom levels.

**Comment by rickmastfan67** [comment]
It doesn't seem that the fix has been added yet to 'master'.  So you want me to submit the fix myself?

**Comment by jteresco** [comment]
You might need to update your copy of the master to match the one on GitHub in the TravelMapping.  If not, let's worry about it next week.

**Comment by rickmastfan67** [comment]
I double checked the 'master' before I submitted #31.  Last commit was the merge of this ticket with the mistake of mine with the URL string.

I even double checked with what changes were missing between my fork and master.  The URL was still the 'messed' up one for the 'VaiBlvd' point.  So, we'll deal with #31 once your back. ;)

**Pull request merged**
