### PR TITLE
ROU A7 & A10 openings

### PR DESCRIPTION
**Pull request by rmihailucian**
@michihdeu please perform datacheck on this one
@jteresco please hold on this one until @michihdeu confirms it's ok

### CODE REVIEW

**Comment by si404** [comment]
In roua_con.csv
roua;A10;;Alba Iulia;rou.a0**03**alb
should be
roua;A10;;Alba Iulia;rou.a0**10**alb

Same issue in updates.csv
2020-12-08;Romania;A10 (Alba Iulia);rou.a0**03**alb;New Route

**Comment by rmihailucian** [comment]
> In roua_con.csv
> roua;A10;;Alba Iulia;rou.a0**03**alb
> should be
> roua;A10;;Alba Iulia;rou.a0**10**alb
> 
> Same issue in updates.csv
> 2020-12-08;Romania;A10 (Alba Iulia);rou.a0**03**alb;New Route

Thank you, corrected.

**Comment by si404** [comment]
Ran a datacheck on it. Works with that fix.

**Comment by michihdeu** [comment]
@rmihailucian I mentioned on the forum that 2 out of 4 open issues are done: https://forum.travelmapping.net/index.php?topic=3949
I think this is also still open: https://forum.travelmapping.net/index.php?topic=3912

**Pull request merged**
