### PR TITLE
Suceava bypass added

### PR DESCRIPTION
**Pull request by rmihailucian**

### CODE REVIEW

**Comment by michihdeu** [comment]
@rmihailucian I'll add the missing csv entries.

**Comment by michihdeu** [comment]
Damn, no. I can't. You've just extended the route. It's not a New route as described in updates.csv. I'll modify the entry....

**Comment by rmihailucian** [comment]
Added it as a new route because I forgot to add it in the updates.csv when the first stage of the road was opened.

**Comment by michihdeu** [comment]
My bad, sorry. Undone.

**Pull request merged**
