### PR TITLE
usaush

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by jteresco** [comment]
I'll hold off on this one until I hear for sure that the changes should be pulled in and go live on site.

**Comment by yakra** [comment]
https://github.com/TravelMapping/HighwayData/pull/1551/files#diff-ebbc96f75e12035e486661c9ef81de01
That's one funky filename. o_O
Isn't the Lincoln Highway outside the scope of the usaush system?

**Comment by si404** [comment]
Re funky filenames - it's a file named so its obvious what its purpose is. IA adds some silly number of points to US30 as the Lincoln Highway meets it something like 41 times, and I felt it a bit overkill to add the 20-something points to US30 now, but I don't want to play 'hunt the places' at some later point.

The Lincoln Highway is outside the scope, but inside the sphere, of usaush. I was interested in where it went and thought 'may as well draft files for it'. It's not in the .csvs, but it's there waiting, should we choose to include it.

**Comment by jteresco** [comment]
Will hold off on this again for tonight's update, I think.  Seems there are others who should weigh in.

**Comment by mapcat** [comment]
I will probably change the US20His_X labels on OH 61 & US 20 to street names eventually, but it's not a priority for me currently. If you want to do it, @si404 , feel free.

**Comment by ovoss** [comment]
Don't wait for me. Entering the last phase of my mega-road trip, I'm not going to have time anytime soon to review all of Si's edits to usaca and usanm files. But the one change I did look at (affecting a file I'm about to edit), I liked Si's change.


Oscar

**Pull request merged**
