### PR TITLE
Watford City ND bypass

### PR DESCRIPTION
**Pull request by yakra**
15-10-06;(USA) North Dakota;US 85;nd.us085;Removed from US 85 Business and relocated onto the southwestern Watford City bypass.
15-10-06;(USA) North Dakota;US 85 Business (Watford City);nd.us085buswat;Added route.
15-10-06;(USA) North Dakota;ND 23;nd.nd023;Removed from ND 23 Business between US 85 Business and the southeastern Watford City bypass, and relocated onto the southeastern Watford City bypass between US 85 and ND 23 Business.
15-10-06;(USA) North Dakota;ND 23 Business (Watford City);nd.nd023buswat;Added route.
15-10-06;(USA) North Dakota;ND 200;nd.nd200;Removed from US 85 Business and relocated onto the southwestern Watford City bypass.

### CODE REVIEW

**Comment by ovoss** [comment]
I'd appreciate your adding points for *OldUS85_N and _S in the US 85 file where the bypass peels off the old alignment, and similar points at the Old US 85 intersections (both seem to be still open) in the US85BusWat file. The way the main and business route junctions were built leaves more than usual stranded old pavement, and in this instance OldUS85 points would best reflect that.

Also,I suggest changing the north endpoint to either ND/SK or USA/Can (hiding the old label), while we're editing this file, for consistency.

**Comment by ovoss** [comment]
I'd appreciate your adding OldUS85_N and _S points to the US85 and US85BusWat files, where both peel away from the old US 85 alignment. The junctions between the mainline and business routes leaves more than usual stranded old pavement, and the extra points would best reflect that.

Also, suggest the north endpoint be renamed from ND/Can to either ND/SK or USA/Can, to be consistent with other international border points.

**Comment by jteresco** [comment]
I think @ovoss closed this by mistake so I'm reopening.  I'm not going to merge it in right now in case @yakra would like to include the @ovoss suggestions.

**Comment by ovoss** [comment]
Thanks, Jim -- my close was indeed by mistake, while I was removing a duplicate comment.

Looking again at US85BusWat, it looks like ND23_E is where an OldUS85_S point would go, so no new point needed there. Still needs an OldUS85_N point, to reflect my travels on former US 85 through Watford City,

**Comment by jteresco** [comment]
Holding off on this one for tonight.  Let me know if all is set and I should merge.

**Comment by yakra** [comment]
If I update the files in my local branch, will merging his request pull in my newest revisions of the files, or just the earlier commits listed above?

**Comment by jteresco** [comment]
@yakra You can add commits to an open pull request, or if it's easier, just open a new one with either all of the changes or just the additional ones.

**Comment by yakra** [comment]
Unsure immediately how to add new commits. How about we merge this one in, and then I add in the *OldUS85 points in in a future pull request?

Oscar, WRT US85BusWat and the usual amount of stranded old pavement:
Is OldUS85 http://www.openstreetmap.org/?lat=47.804421&lon=-103.352278 fine, or
would you prefer *OldUS85 http://www.openstreetmap.org/?lat=47.804674&lon=-103.350229 ?

**Comment by jteresco** [comment]
Sure.  Merging this one in.

**Comment by ovoss** [comment]
The first (oldUS85) seems better to me than the second (*OldUS85), The second is slightly more perfect, but the first is close enough for me, and that it's at an actual intersection makes it better. 

Oscar 

----- Original Message -----

**Comment by yakra** [comment]
I've added OldUS85 to US85BusWat in my repository.

For US85 proper:
For the southern point, the old/new split lines up just about exactly with the new realigned 24th st intersection, so I've added the point there:
24thSt http://www.openstreetmap.org/?lat=47.754351&lon=-103.283178
For the northern point, I'd place it about here:
*OldUS85 http://www.openstreetmap.org/?lat=47.804731&lon=-103.367239
Or, I could slide it a tiny bit west to the actual intersection of 130th Ave. Thoughts?

**Comment by ovoss** [comment]
All of these are fine with me, including using 130thSt instead of the northern OldUS85 point. 

Oscar 

----- Original Message -----

**Comment by yakra** [comment]
I'll use 130thSt, then. Heck, it's what I did with the US54/400 Cunningham KS bypass.

**Comment by yakra** [comment]
https://github.com/TravelMapping/HighwayData/pull/133

**Comment by the-spui-ninja** [comment]
Just to let you know, the concurrency between ND 200 and US 85 is now broken. I think the points need to be added to ND 200's file as well.

**Comment by yakra** [comment]
Derp! Thanks.
Submitted #135.

**Pull request merged**
