### PR TITLE
Batch pull request for NV edits

### PR DESCRIPTION
**Pull request by NickCPDX**

### CODE REVIEW

**Comment by jteresco** [comment]
The main thing we need here are some good updates.csv entries for any changes deemed newsworthy.  I'm tied up a lot this week, but maybe others like @si404, @yakra, @michihdeu or @rickmastfan67 can help you get those updates entries added in an appropriate level of detail if it's not something you've had to do before.

Thanks for all the updates!

**Comment by michihdeu** [comment]
@NickCPDX , have a look at https://github.com/TravelMapping/HighwayData/blob/master/updates.csv

It is sorted by region. Each region is sorted by date (newest first). Every new route, (relevant) realignment, extension or truncation needs an entry.

**Comment by si404** [comment]
Something seems a bit janky with the I-580 file. Are all the points in twice? Certainly there's a stray half-line that will muck things up.

Otherwise, they seem fine (though I think US50Bus ought to have a US50 label, rather than a US395 one)

**Comment by si404** [comment]
I've fixed I-580, which did repeat (copy-paste error).

**Pull request merged**
