### PR TITLE
Activation of Germany split into 16 regions

### PR DESCRIPTION
**Pull request by michihdeu**
Please hold off with the update if there are any objections

### CODE REVIEW

**Comment by jteresco** [comment]
I don't know enough about this to judge whether it's OK to merge this.  Any comment from @si404 or others?

**Comment by yakra** [comment]
My comment is that I have not been paying attention to this process. :)

**Comment by michihdeu** [comment]
Due to a later pull request modifying systems.csv in the line after my modification, I got a conflict. I've fixed it here in the web interface (it was the first time I could manage this). The "This branch has no conflicts with the base branch" appeared here.

Now, I pressed sync in the desktop software again and still got conflicts with systems.csv! It usually takes about 5 minutes till the online changes are detected and can be synced. I modified the csv files and copied about 50 new wpt files into my repository (NW L220-L279n) meanwhile. Well, I cut from a different folder and paste into the repository as usual... I also modified some files (B56n merged into B56, new L47 and L48 files). After > 10..20 minutes, I tried to sync again but still conflict with systems.csv. I've copied the content of systems.csv from GitHub and modified my local file but still had the conflict. I tried to sync (GitHub to local) again and a different option appeared now. I could debug the conflicts (never got this option before) but nothing happened. I pressed "cancel" and all local data on my PC was undone. L220-L279n not available anymore and all modifed wpt files are reset. GitHub desktop software shows 5 changed files only (it was >70 files before). Only the csv files - deub.csv, deub_con.csv, deunwl.csv, deunwl_con.csv and the damn systems.csv are still as after my latest modification...

I cannot find the modified wpt files on my PC. I guess they are gone and the only chance to make a new commit is... Deleting all local data* and download the repository from GitHub again... **Or is it possible that the files are anywhere in my online repository so that I can download them again**

*Of course, I've copied the deub/deunwl csv files. Saves me 15..20 minutes but the major effort - more than 50 wpt files - must be done again.....

**Comment by jteresco** [comment]
If they were committed locally, the changes are there.  It's hard to make git forget anything.  Look at the local history of one of the files ("git log" command) and you should see your old commits and the commit from the merge that reverted them.  You can checkout older revisions but I'd have to investigate further.

**Comment by michihdeu** [comment]
Thanks but I didn't make a commit today. Nothing is shown in the history of the repository. The wpt files were removed when I canceled debugging the conflict on syncing online to local.

It's odd that the csv files are still there and only the wpt file modifications are gone...

**Comment by jteresco** [comment]
git is usually very hesitant to overwrite any uncommitted changes in your local copy when doing a merge.  But I don't use the desktop version so maybe it's more aggressive.

**Comment by jteresco** [comment]
Quick thought: maybe it did a stash operation without your knowledge?

**Comment by michihdeu** [comment]
Sure, anything unintended (and incomplete) happened in the background but where is the data? I also googled but couldn't find anything helpful. I and remember exactly and cannot describe what really happened before this unintended... I guess it's best to draft the routes again but not now..... Have to wait till I'm motivated again.....

**Comment by jteresco** [comment]
Some conflicts were obvious, but a couple were less so.  I made my best guess at resolving them.  I'll start a site update that includes this (and stop it before it can install anything on site) as soon as the real site update for tonight finishes, which should be about 30 minutes.

**Comment by jteresco** [comment]
Remaining errors after a few fixes I could easily handle:

`ABORTING due to 6 errors:
1: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/BEL/deub/bel.b258.wpt'
2: Route contains fewer than 2 points: bel.b258 (0 total points)
3: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/CHE/deub/che.b317.wpt'
4: Route contains fewer than 2 points: che.b317 (0 total points)
5: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/AUT/deub/aut.b999.wpt'
6: Route contains fewer than 2 points: aut.b999 (0 total points)
`

**Comment by michihdeu** [comment]
I forgot changing the folder name for the extraterritorial routes
deubc --> deub in AUT, BEL and CHE

**Comment by si404** [comment]
I've done the deubc --> deub checks #f7e99f5

**Comment by michihdeu** [comment]
Thanks. I think @jteresco can run an update now...

**Pull request merged**
