### PR TITLE
More new systems stuff, and Belgium

### PR DESCRIPTION
**Pull request by si404**
2016-01-12;Belgium;A13;bel.a013;Route extended at west end from exit 17
to R10
2016-01-12;Belgium;A112;bel.a112;Route extended at north end from E34/R1 to N113/R10
2016-01-12;Belgium;E420;bel.e420;Route reentered between exit 27 of the
N54 and the N576
2016-01-12;Belgium;E420 (Charleroi);bel.e420bel;New Route
2016-01-12;Belgium;Péripherique du Charleroi;bel.percha;New Route
2016-01-12;Belgium;Ring Antwerpen Oost;bel.ringante;New Route
2016-01-12;Belgium;Ring Antwerpen West;bel.ringantw;New Route
2016-01-12;Belgium;Ring Bruxelles / Ring Brussels;bel.ringbru;New Route
2016-01-12;Belgium;Ring Charleroi;bel.ringcha;New Route
2016-01-12;Belgium;Ring Gent Oost;bel.ringgento;New Route
2016-01-12;Belgium;Ring Kortrijk;bel.ringkor;New Route
2016-01-12;Belgium;Ring Mons Est;bel.ringmonse;New Route
2016-01-12;Belgium;Ring Mons Ouest;bel.ringmonso;New Route

### CODE REVIEW

**Comment by jteresco** [comment]
Missing myse csv files.

**Comment by jteresco** [comment]
Fixing several file/csv entry mismatches in BEL/eursf - please check after I commit my changes.  (But not until then to avoid conflicts.)

**Comment by jteresco** [comment]
Bigger problem: roudn has a bunch of identical .wpt files which cause my waypoint quadtree refinement to break.  I am commenting it out of systems.csv until the files are removed from roudn's csv files or the files become their real versions.  Any position that contains more than 50 waypoints at that same place will break my code.  I vaguely considered this possibility when I first implemented, but assumed we'd never legitimately even get close to that many points in the same place (that would be quite a concurrency/intersection).

General request: I think it's OK to have placeholder wpt files in the repository, but please don't have entries for them in the csv files until they have at least their initial "real" draft.  Even for devel systems.

**Comment by si404** [comment]
Sorry about all that Jim
* I didn't realise that I had so many roudn files that weren't there (I was copying Oscar's CA practice where a few routes pointed to Russia with the placeholders) nor the limit of 50 routes sharing one waypoint. The placeholders are now all gone, replaced with either full drafts, or with outlines consisting of intersections with other routes in the system and sometimes a few other points. Ah well, I guess these past 4 days were as good an opportunity as any to spend ages making .wpt files!
* I also didn't realise that I left myse's .csv files in the myse folder (there were a handful of placeholders there, now finished drafts of routes, having spent a morning doing that so as to avoid that error), which was easy enough to fix!
 * I changed the names of the Belgian files and forgot to change the .csvs - a classic bonehead Si move.

**Comment by jteresco** [comment]
Thanks - no big deal.  I need to set up a way for all of you to be able to run at least a sanity check on csv and wpt files so those kinds of mistakes can be caught before they get committed.

**Pull request merged**
