### PR TITLE
espvc review, fraidf tweaks, openings, housekeeping

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by jteresco** [comment]
I'm confused.  Failed again and it's midnight.  I'm commenting out fran for tonight's update.

**Comment by michihdeu** [comment]
Si has removed N118 instead of N188 by accident. I'll fix it and run data check

https://github.com/TravelMapping/HighwayData/pull/3031/commits/2a220e1fdb02ed0bc0425f09d940ce460b51e5f5

**Comment by michihdeu** [comment]
I cannot connect from noreaster to Github. I'll try it later again

`Failed to connect to github.com port 443: No route to host`

**Comment by michihdeu** [comment]
@jteresco I could access Github now. Since Github Desktop can connect fine, I guess that the cause might be on noreaster? Your server was also down yesterday - or travelmapping.net was just 'not accessable'.

**Comment by michihdeu** [comment]
Data check successful!

**Pull request merged**
