### PR TITLE
Pennyrile Parkway now a signed part of I-69

### PR DESCRIPTION
**Pull request by si404**
2015-11-17;(USA) Kentucky);I-69;Route extended at north end from exit 106 to exit 77 of the Pennyrile Parkway

### CODE REVIEW

**Comment by si404** [comment]
2015-11-17;(USA) Kentucky);I-69;Route extended at north end from exit 106 to exit 77 of the Pennyrile Parkway
2015-11-17;(USA) Kentucky;I-69 Future (Madisonville);;Route Deleted

**Comment by rickmastfan67** [comment]
I'd advise not merging this just yet.  That section of the Pennyrile Parkway that became I-69 is also getting new exit numbers posted right now.

http://www.aaroads.com/forum/index.php?topic=3518.msg2102134#msg2102134

**Comment by si404** [comment]
Yes, waiting for that is good, I just wanted to make sure the change didn't slip through the cracks!

**Comment by yakra** [comment]
Either the KY425 to Audobon Pkwy segment stays part of I-69Fut, or was erroneously included as USAIF in the first place:
http://route.transportation.org/Documents/05%2014%202015%20Cheyenne,%20WY%20Report/SM%202015%20USRN%20SCOH%20REPORT.pdf
http://route.transportation.org/Documents/05%2014%202015%20Cheyenne%2c%20WY%20Report/I-69_application_Pennyrile.pdf

**Comment by rickmastfan67** [comment]
Yakra, that segment was added in the first place because of the Audubon Parkway being a Future Interstate itself, but didn't have an official number yet.  Plus the final alignment to the new I-69 bridges hadn't been decided yet.  It was just a logical ending point then.

In fact, is there any official documentation that the Audubon Parkway will indeed become I-369?  If so, we should finally add it to the 'Future Interstate' group then.

**Comment by yakra** [comment]
Curious, *has* the final alignment to the new I-69 bridges been decided?

**Pull request closed without merging**
