### PR TITLE
Updates to GA routes (and some concurrent US routes)

### PR DESCRIPTION
**Pull request by ntallyn**

### CODE REVIEW

**Comment by jteresco** [comment]
Not sure what happened here, but git seems to think every line in the usausb CSV files was changed, leading to merge conflicts.

**Comment by yakra** [comment]
CRLF issues?

**Comment by michihdeu** [comment]
git is right. Every line HAS changed. There is each one more ; at the end of both files.

CRLF is no matter of git but I think it was on our end. It's fine now.

**Comment by yakra** [comment]
Drafting some comments to post in the forum.

**Comment by yakra** [comment]
Posting here as it's more of a git-related issue:
Several lock files produced by OpenOffice got caught up in the dragnet and staged for commit.

**Comment by jteresco** [comment]
I think this one will need a do over.  Closing.

**Comment by yakra** [comment]
Currently cloning https://github.com/ntallyn/HighwayData.git
Can have a go at salvaging what we can of the data. Hopefully the edits will be easy. Ish.
If the most recent commit in `ntallyn:master` gets scrapped and there are conflicts (most likely)...
* We can try to resolve them upon merging `TravelMapping:master` back into `ntallyn:master`
* Or, if stuff gets bad, rather than delete the `ntallyn` fork altogether, there's a roundabout but functional way to revert, by creating a branch, changing default, deleting a branch, and renaming a branch...

**Comment by yakra** [comment]
> git is right. Every line HAS changed. There is each one more ; at the end. Both files.

Every comma got changed to a semicolon. I bet when the files were opened up in OOo, both the comma and semicolon boxes were checked off as delimiters. When saving the files, all delimiters became semicolons.
* usausb.csv had a few routes with AltRouteNames, and
* usausb_con.csv had a few routes with 2 roots

all *other* rows had a blank column at the end; resulting in the "extra" `;`
So, a small minority of rows don't have it, e.g.:
`usausb;AR;US67;Bus;Wal;Walnut Ridge; AR;ar.us067buswal;US67BusHox;`
` usausb;US1;Byp;Portsmouth; NH;nh.us001byppor;me.us001byppor `

**Pull request closed without merging**
