### PR TITLE
BW/NOR

### PR DESCRIPTION
**Pull request by michihdeu**

### CODE REVIEW

**Comment by michihdeu** [comment]
@jteresco @yakra data check says:

```
[134.3] Sorting waypoints in Quadtree.
[136.5] Finding unprocessed wpt files.
5217 .wpt files in ../../../HighwayData/hwy_data not processed, see unprocessedwpts.log.
[136.5] Near-miss point log and tm-master.nmp file.
[137.5] Processing waypoint labels and checking for unconnected chopped routes.
Traceback (most recent call last):
  File "./siteupdate.py", line 2965, in <module>
    datacheckerrors.append(DatacheckEntry(r, [point_list[r.pri_label_hash[a]].label], "DUPLICATE_LABEL"))
NameError: name 'point_list' is not defined
Sun Feb 28 09:11:55 EST 2021
datacheck.sh: complete
```

❓ I really don't know what it means. I run data check as usual - as yesterday. The csv files look fine.

**Comment by Markkos1992** [comment]
It may be from the duplicate label created in the updates last night (https://forum.travelmapping.net/index.php?topic=4132.msg22701#msg22701).

**Comment by michihdeu** [comment]
> It may be from the duplicate label created in the updates last night (https://forum.travelmapping.net/index.php?topic=4132.msg22701#msg22701).

I don't think so. There are [many DL errors](https://travelmapping.net/devel/datacheck.php?show=DUPLICATE_LABEL).

The new routes of this pull request are on the site. I wonder how it worked!?

**Comment by yakra** [comment]
> NameError: name 'point_list' is not defined

My first impression is that something should say `self.point_list` or `r.point_list` that just says `point_list` instead. I'll take a closer look shortly.
Weird -- I wanna say I've seen this before with Python -- a missing `self.` that works fine (even though it shouldn't) on Linux, but crashes (as would be expected) on BSD.

Coffee.

**Comment by yakra** [comment]
Missing `r.`, but that alone doesn't solve it:
```
Traceback (most recent call last):
  File "./siteupdate.py", line 2965, in <module>
    datacheckerrors.append(DatacheckEntry(r, [r.point_list[r.pri_label_hash[a]].label], "DUPLICATE_LABEL"))
KeyError: 0
```
Will this also crash the C++ version?

**Coffee.**

**Comment by michihdeu** [comment]
How can a `r` get lost? The code was not changed. Only the execution fails. Could it be an issue on Jim's server? Any OS update that steals `r` `s? 😉

**Comment by yakra** [comment]
This was code I changed 22 days ago:
https://github.com/TravelMapping/DataProcessing/blame/master/siteupdate/python-teresco/siteupdate.py#L2965

In other news, I think I want
`[r.point_list[r.pri_label_hash[w.alt_labels[a]]].label]`
Dang, that's a mouthful. Not sure if I've ever seen that many square brackets in one place...

**Comment by michihdeu** [comment]
I think that I run data check more than 10 times since that change!? And Jim runs it every night with the site update....

**Comment by yakra** [comment]
A new error due to a new data change? I'm testing a fix on noreaster right now, and know what the offending label is shortly.

**Comment by michihdeu** [comment]
I still don't get it. Jim run the same code with last night's update 😕

**Comment by yakra** [comment]
```
[yakra@noreaster /home/michih/HighwayData/hwy_data/NC/usaus]$ git blame nc.us158.wpt | grep US29Bus/87
0efa5ce1497 (Jim Teresco 2021-02-27 20:49:13 -0500  34) US29Bus/87 +US29Bus/NC87 +US29Bus_N +US29Bus http://www.openstreetmap.org/?lat=36.334133&lon=-79.692646
8c35d525806 (Jim Teresco 2017-11-17 19:32:00 -0500  35) US29Bus_S +US29Bus/87 http://www.openstreetmap.org/?lat=36.314952&lon=-79.672036
```

> I still don't get it. Jim run the same code with last night's update 😕 

I don't get it either. @jteresco?
I'll keep digging...

**Comment by michihdeu** [comment]
That's what Markkos mentioned. This DL make in just the day before.

A label with three alt labels.... a long string....

**Comment by yakra** [comment]
> I still don't get it. Jim run the same code with last night's update 😕 

Turns out @jteresco is still using an older version of siteupdate.py:
```
[yakra@noreaster /fast/home/terescoj/travelmapping/DataProcessing/siteupdate/python-teresco]$ git show -s
commit e30cdcf493b0e4897e095b536a0fd73d55589895 (HEAD -> master, origin/master, origin/HEAD)
Author: Jim Teresco <terescoj@gmail.com>
Date:   Wed Jan 20 21:31:37 2021 -0500

    New web server directory.
```

**Comment by jteresco** [comment]
Sorry, I've been tied up all day and off to class in a minute.  I pulled in the latest site update just now, and will try to remember to check for further updates and merge/pull before tonight.

**Comment by yakra** [comment]
New semester?

**Comment by jteresco** [comment]
It's here!  Shouldn't be bad, just an extra busy few days.

**Pull request merged**
