### PR TITLE
Italy systems clean up

### PR DESCRIPTION
**Pull request by si404**
@yakra - hopefully this is fine for you. I've split eure2 into its two functions (bihe and itae). I've renamed eursf to itasf. I've moved all the split-related systems to the bottom of systems.csv for easy access.

(this pull also moves RA16, but does nothing else)

### CODE REVIEW

**Comment by michihdeu** [comment]
@si404 is it compatible with #7809 ?

**Comment by si404** [comment]
Looks like no conflicts with #7809 pulled in.

**Comment by yakra** [comment]
Will review later on.
In the immediate term, strongly suggest *not* merging this just yet.

For now, working on finalizing https://github.com/TravelMapping/DataProcessing/issues/492, which will become important later as we continue validating data for the ITA split.

**Comment by yakra** [comment]
Looking into this now.
There's some technical stuff with `siteupdate --splitregion` I'm trying to understand & get sorted.

**Comment by yakra** [comment]
I've opened a PR for an alternative to this at #7821.

**Pull request closed without merging**
