### PR TITLE
Poland and Spain

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by jteresco** [comment]
@si404 I also commented out two more esp systems, espcl and espct, on recent runs because of non-ascii characters in some wpt files.  Didn't commit and push the systems.csv change, but maybe you can track down the problem files before the next update.

**Comment by si404** [comment]
I've gone through both systems' files and found nothing. I note that you made a change to an espcl one that looks like you did nothing - perhaps you caught that one?

**Comment by jteresco** [comment]
I think I did fix one.  I am traveling today but should be able to see tomorrow if anything is still problematic.

**Comment by jteresco** [comment]
`ABORTING due to 16 errors:
1: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ESP-AN/espan/espan.a092x.wpt'
2: Route contains fewer than 2 points: espan.a092x (0 total points)
3: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ESP-AN/espan/espan.a092nx.wpt'
4: Route contains fewer than 2 points: espan.a092nx (0 total points)
5: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ESP-AN/espan/espan.a092gx.wpt'
6: Route contains fewer than 2 points: espan.a092gx (0 total points)
7: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ESP-AN/espan/espan.a092mx.wpt'
8: Route contains fewer than 2 points: espan.a092mx (0 total points)
9: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ESP-AN/espan/espan.a316x.wpt'
10: Route contains fewer than 2 points: espan.a316x (0 total points)
11: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ESP-AN/espan/espan.a318x.wpt'
12: Route contains fewer than 2 points: espan.a318x (0 total points)
13: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ESP-AN/espan/espan.a381x.wpt'
14: Route contains fewer than 2 points: espan.a381x (0 total points)
15: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ESP-AR/espar/espar.a236.wpt'
16: Route contains fewer than 2 points: espar.a236 (0 total points)
`

**Pull request merged**
