### PR TITLE
Update chngd.ah001.wpt

### PR DESCRIPTION
**Pull request by eeffaann**
Fix per https://forum.travelmapping.net/index.php?topic=6527.0;topicseen

### CODE REVIEW

**Comment by yakra** [comment]
> Suggest G4/G1508 as the label.
https://travelmapping.net/devel/manual/wayptlabels.php#bothroutes

**Comment by jteresco** [comment]
Will await review before merging.

**Comment by michihdeu** [comment]
> > Suggest G4/G1508 as the label.
> > https://travelmapping.net/devel/manual/wayptlabels.php#bothroutes

@yakra what do you mean? I've requested a review from you the other day to clarify it.

**Comment by yakra** [comment]
Sorry, thought my comment in itself was adequate.
`17(G1508)` was deleted, which is good.
`2150(G4)` still exists, but with the same label as before. Suggest changing it to `G4/G1508` as per the manual.

**Comment by jteresco** [comment]
Thanks, I will then wait for that suggested change to come in before merging.

**Comment by eeffaann** [comment]
Updated

**Pull request merged**
