### PR TITLE
Extend WA 103 northward, adding WA 100 Spur

### PR DESCRIPTION
**Pull request by compdude**
WA 103 is being extended northward per this forum post: http://tm.teresco.org/forum/index.php?topic=1791.0

Also, I am adding WA 100 Spur Fort Canby per this forum post: http://tm.teresco.org/forum/index.php?topic=1790.0

### CODE REVIEW

**Comment by jteresco** [comment]
Just to be sure, since @compdude is just staring on highway data management, could one or two of our experienced people take a minute to check this out, and help him put together an appropriate updates entry?  Looked OK to me.

**Comment by compdude** [comment]
Anyone, anyone? Buehler, Buehler??

**Comment by mapcat** [comment]
2017-01-01;(USA) Washington;WA 103;wa.wa103;Extended at northern end from Leadbetter Point SP boundary to end of state highway in park
2017-01-01;(USA)Washington;WA 100 Spur (Fort Canby);wa.wa100sprfor;Route added

**Comment by jteresco** [comment]
This one's now giving conflicts in updates.csv, and not just on the new lines.  I think some kind of formatting change was inadvertently introduced or the edit is based on a badly outdated updates.csv.  I think the best thing is to abandon this pull and start a new one based on the current master, and put in those two file changes and the updates entries.  Thanks.

**Comment by compdude** [comment]
Seems like the current updates.csv file is COMPLETELY messed up. All the dates are out of order, whereas the version I pulled from had all the dates in order, from newest to oldest. This newer updates file jumps around a lot. I don't know what the heck happened!

**Comment by jteresco** [comment]
That was intentional - see http://tm.teresco.org/forum/index.php?topic=1858.0

**Comment by compdude** [comment]
Oh, okay, I see how it's organized. I didn't know that the updates.csv file had been completely redone. I think I will just pull from the newest version of the updates.csv when I get the chance after work.

**Comment by jteresco** [comment]
Closing this one, since a new request will be submitted based on a current version of the master repository.

**Pull request closed without merging**
