### PR TITLE
IN, OH, & TN changes

### PR DESCRIPTION
**Pull request by mapcat**
IN: new waypoints on I-65 and I-90 at complex interchanges
OH: OH 55 truncation and OH 109 reroute
TN: TN 7 truncation and TN 66 (Morristown) reroute

### CODE REVIEW

**Comment by michihdeu** [comment]
@mapcat 

202**0**-07-28;(USA) Ohio;OH 32;oh.oh032;OH220 point moved from old location (now GerRd) to new location approximately 1.5 miles to the west
-->
202**1**-07-28;(USA) Ohio;OH 32;oh.oh032;OH220 point moved from old location (now GerRd) to new location approximately 1.5 miles to the west

**Comment by mapcat** [comment]
@michihdeu why did you change my updates entry from last July?

**Comment by michihdeu** [comment]
@mapcat I only added a comment to the pull request. But I was wrong. It should be read:

2020-**07-28**;(USA) Ohio;OH 32;oh.oh032;OH220 point moved from old location (now GerRd) to new location approximately 1.5 miles to the west
-->
2020-**12-24**;(USA) Ohio;OH 32;oh.oh032;OH220 point moved from old location (now GerRd) to new location approximately 1.5 miles to the west

**You** obviously changed an old entry by accident. Please revert.

**Comment by mapcat** [comment]
Okay, sorry for the misunderstanding

**Pull request merged**
