### PR TITLE
canab fixes for AB8xx routes

### PR DESCRIPTION
**Pull request by yakra**

### CODE REVIEW

**Comment by yakra** [comment]
I may add some more commits to this.
No problem if it gets merged in before I do so, though.

**Comment by jteresco** [comment]
I'll probably run the site update tonight around 10 PM EST.

**Comment by yakra** [comment]
> No problem if it gets merged in before I do so, though.
Actually it'd be a problem if it's merged after I commit either AB16 or TCHYel, but before I commit the other. This should be ready in a couple minutes.

**Comment by yakra** [comment]
Ready to rock.

**Pull request merged**
