### PR TITLE
Reorder updates.csv by region (ignore parentheses)

### PR DESCRIPTION
**Pull request by yakra**
Per discussion in [this thread](http://tm.teresco.org/forum/index.php?topic=1858.new#new), mostly beginning at [this post](http://tm.teresco.org/forum/index.php?topic=1858.msg4649#msg4649).

Submitting this more for discussion purposes, not necessarily to have it merged in straight away.

### CODE REVIEW

**Comment by yakra** [comment]
**Oddities:**
"(FRA) France" vs "France"
One "(France) Corsica" whereas otherwise France doesn't seem ti be divided into subregions
A few entries for "Kazakhstan" with no subregions
Entries for "Ukraine" with & without subregions, including "(Ukraine) Ukraine"

**Comment by jteresco** [comment]
I agree with the idea of ignoring parens and fixing the oddities.  Let's hold off any new updates entries until this is merged.

**Comment by michihdeu** [comment]
> 2016-05-01;Sweden;Malmo Inre Ringvagen;swe.inreringvag; with no actual description provided

Please add `New Route`. Thanks.

**Comment by yakra** [comment]
> Please add `New Route`. Thanks.

Done.

**Pull request merged**
