### PR TITLE
BEL/NLD

### PR DESCRIPTION
**Pull request by michihdeu**

### CODE REVIEW

**Comment by jteresco** [comment]
We have two entries in systems.csv for belr, one active and one devel.  Which one is correct?

**Comment by jteresco** [comment]
BTW, can't run a site update with both since it loads the csv twice and that causes all kinds of trouble.

**Comment by jteresco** [comment]
I now see there's a beln directory - assuming that's what the devel entry should be.  Let me know if that's incorrect.  That's what I'll do for the site update a little later unless I hear otherwise.

**Comment by michihdeu** [comment]
Sorry and thanks for the fixes.

I think an automated check should be a priority for 2017/18: https://github.com/TravelMapping/DataProcessing/issues/22.

**Pull request merged**
