### PR TITLE
roudj csvs

### PR DESCRIPTION
**Pull request by rmihailucian**
@michihdeu please perform datacheck on this.
@jteresco please hold on with this one, until @michihdeu confirms it's ok.

### CODE REVIEW

**Comment by michihdeu** [comment]
I've merged-in both pull requests but the 2nd merge failed (tur). I've recognized it when everything was done offline - including tur fixes blvd -> bul and cad -> cd. I've merged the 2nd pull again and got a conflicts. I've fixed them manually but it was still not working (had the same issue many times before but long ago). I've deleted offline data and my online hwydata repository. Forked again and downloaded. Copied the modified roudj csv files into the right place and made the tur changes again. Everything is fine now.
However, I cannot run data check because of the same conflicts I had before. I've started deleting my hwydata repository on noreaster but it's damn slow. About 10% is deleted now - after about 15 minutes. Sorry, it will still take a little bit.

**Comment by michihdeu** [comment]
csv fixes were not that hard. roudj_con.csv had an additional column I had to remove, 2 typos and an unprocessed wpt file (dj666.wpt).

**Comment by michihdeu** [comment]
Okay, `rm -rf HighwayData/` made it in less than 1 second

**Comment by michihdeu** [comment]
I've cloned my hwydata repository to noreaster but couldn't run data check. "fatal". I've deleted it again, cloned again, and it works now.
DATA CHECK SUCCESSFUL!

**Comment by rmihailucian** [comment]
Thank you!

**Pull request merged**
