### PR TITLE
let's try this again

### PR DESCRIPTION
**Pull request by neroute2**

### CODE REVIEW

**Comment by jteresco** [comment]
Getting closer.  I'm not sure how @si404 and @michihdeu dealt with these issues when there were overlapping systems in the European countries they split into regions.  Remaining datacheck errors follow.

<pre>
ABORTING due to 376 errors:
1: Duplicate root in route lists: mexbcs.mex001d
2: Duplicate root in route lists: mexbc.mex001d
3: Duplicate root in route lists: mexbc.mex002d
4: Duplicate root in route lists: mextam.mex002d
5: Duplicate root in route lists: mexmich.mex014d
6: Duplicate root in route lists: mexemex.mex015dmex
7: Duplicate root in route lists: mexemex.mex015dmac
8: Duplicate root in route lists: mexmich.mex015dmac
9: Duplicate root in route lists: mexemex.mex015d
10: Duplicate root in route lists: mexmich.mex015d
11: Duplicate root in route lists: mexjal.mex015d
12: Duplicate root in route lists: mexjal.mex015dteq
13: Duplicate root in route lists: mexnay.mex015d
14: Duplicate root in route lists: mexnay.mex015desc
15: Duplicate root in route lists: mexsin.mex015d
16: Duplicate root in route lists: mexson.mex015dobr
17: Duplicate root in route lists: mexson.mex015d
18: Duplicate root in route lists: mexson.mex015dnog
19: Duplicate root in route lists: mexchih.mex016d
20: Duplicate root in route lists: mexmich.mex037dlaz
21: Duplicate root in route lists: mexgro.mex037d
22: Duplicate root in route lists: mexmich.mex037d
23: Duplicate root in route lists: mexsin.mex040d
24: Duplicate root in route lists: mexdgo.mex040d
25: Duplicate root in route lists: mexcoah.mex040dmat
26: Duplicate root in route lists: mexcoah.mex040d
27: Duplicate root in route lists: mexnl.mex040d
28: Duplicate root in route lists: mexmich.mex043d
29: Duplicate root in route lists: mexgto.mex043d
30: Duplicate root in route lists: mexqro.mex045d
31: Duplicate root in route lists: mexgto.mex045d
32: Duplicate root in route lists: mexgto.mex045dleo
33: Duplicate root in route lists: mexzac.mex045d
34: Duplicate root in route lists: mexzac.mex045dvic
35: Duplicate root in route lists: mexzac.mex045dfre
36: Duplicate root in route lists: mexchih.mex045d
37: Duplicate root in route lists: mexchih.mex045dchi
38: Duplicate root in route lists: mexchih.mex045dvil
39: Duplicate root in route lists: mexmich.mex048d
40: Duplicate root in route lists: mexdgo.mex049dgom
41: Duplicate root in route lists: mexdgo.mex049d
42: Duplicate root in route lists: mexchih.mex049d
43: Duplicate root in route lists: mexcol.mex054d
44: Duplicate root in route lists: mexjal.mex054d
45: Duplicate root in route lists: mexemex.mex055d
46: Duplicate root in route lists: mexdf.mex057d
47: Duplicate root in route lists: mexemex.mex057d
48: Duplicate root in route lists: mexhgo.mex057d
49: Duplicate root in route lists: mexemex.mex057dsju
50: Duplicate root in route lists: mexslp.mex057d
51: Duplicate root in route lists: mexslp.mex057dmat
52: Duplicate root in route lists: mexcoah.mex057dsal
53: Duplicate root in route lists: mexcoah.mex057d
54: Duplicate root in route lists: mexnay.mex068d
55: Duplicate root in route lists: mexslp.mex070d
56: Duplicate root in route lists: mextam.mex070d
57: Duplicate root in route lists: mexjal.mex080d
58: Duplicate root in route lists: mexemex.mex085d
59: Duplicate root in route lists: mexhgo.mex085d
60: Duplicate root in route lists: mexnl.mex085d
61: Duplicate root in route lists: mexjal.mex090d
62: Duplicate root in route lists: mexgro.mex095daca
63: Duplicate root in route lists: mexgro.mex095dtax
64: Duplicate root in route lists: mexgro.mex095digu
65: Duplicate root in route lists: mexmor.mex095digu
66: Duplicate root in route lists: mexgro.mex095d
67: Duplicate root in route lists: mexmor.mex095d
68: Duplicate root in route lists: mexmor.mex115d
69: Duplicate root in route lists: mexpue.mex117d
70: Duplicate root in route lists: mextlax.mex117d
71: Duplicate root in route lists: mextlax.mex119d
72: Duplicate root in route lists: mexpue.mex119d
73: Duplicate root in route lists: mexhgo.mex119d
74: Duplicate root in route lists: mexpue.mex129d
75: Duplicate root in route lists: mexemex.mex132d
76: Duplicate root in route lists: mexhgo.mex132d
77: Duplicate root in route lists: mexpue.mex132d
78: Duplicate root in route lists: mexver.mex132d
79: Duplicate root in route lists: mexoax.mex135d
80: Duplicate root in route lists: mexpue.mex135d
81: Duplicate root in route lists: mexemex.mex136d
82: Duplicate root in route lists: mexpue.mex140d
83: Duplicate root in route lists: mextlax.mex140d
84: Duplicate root in route lists: mexpue.mex140dmax
85: Duplicate root in route lists: mextlax.mex140dmax
86: Duplicate root in route lists: mexpue.mex140dori
87: Duplicate root in route lists: mextlax.mex140dori
88: Duplicate root in route lists: mexpue.mex140dper
89: Duplicate root in route lists: mexver.mex140d
90: Duplicate root in route lists: mexver.mex140dgua
91: Duplicate root in route lists: mexver.mex140depl
92: Duplicate root in route lists: mexver.mex145d
93: Duplicate root in route lists: mextlax.mex150d
94: Duplicate root in route lists: mexpue.mex150d
95: Duplicate root in route lists: mexver.mex150d
96: Duplicate root in route lists: mexver.mex180d
97: Duplicate root in route lists: mexver.mex180dver
98: Duplicate root in route lists: mextab.mex180d
99: Duplicate root in route lists: mexcam.mex180d
100: Duplicate root in route lists: mexyuc.mex180d
101: Duplicate root in route lists: mexqroo.mex180d
102: Duplicate root in route lists: mexchis.mex190d
103: Duplicate root in route lists: mexcol.mex200d
104: Duplicate root in route lists: mexgro.mex200d
105: Duplicate root in route lists: mexhgo.mexm040d
106: Duplicate root in route lists: mexemex.mexm040dsma
107: Duplicate root in route lists: mexhgo.mexm040dsma
108: Duplicate root in route lists: mexemex.mexm040dsfr
109: Duplicate root in route lists: mexhgo.mexm040dsfr
110: Duplicate root in route lists: mexemex.mexm040dsah
111: Duplicate root in route lists: mexhgo.mexm040dsah
112: Duplicate root in route lists: mextlax.mexm040dsah
113: Duplicate root in route lists: mexhgo.mexm040demi
114: Duplicate root in route lists: mextlax.mexm040demi
115: Duplicate root in route lists: mextlax.mexm040d
116: Duplicate root in route lists: mexpue.mexm040d
117: Duplicate root in route lists: mexchih.chih007d
118: Duplicate root in route lists: mexchih.chih048d
119: Duplicate root in route lists: mexchih.chih056d
120: Duplicate root in route lists: mexemex.emex005d
121: Duplicate root in route lists: mexmor.pue438d
122: Duplicate root in route lists: mexpue.pue438d
123: Duplicate root in route lists: mexsin.sinae001
124: Duplicate root in route lists: mexslp.slp075d
125: Duplicate root in route lists: mexslp.slp080d
126: Duplicate root in con_route lists: mexbcs.mex001d
127: Duplicate root in con_route lists: mexbc.mex001d
128: Duplicate root in con_route lists: mexbc.mex002d
129: Duplicate root in con_route lists: mextam.mex002d
130: Duplicate root in con_route lists: mexmich.mex014d
131: Duplicate root in con_route lists: mexemex.mex015dmex
132: Duplicate root in con_route lists: mexemex.mex015dmac
133: Duplicate root in con_route lists: mexmich.mex015dmac
134: Duplicate root in con_route lists: mexemex.mex015d
135: Duplicate root in con_route lists: mexmich.mex015d
136: Duplicate root in con_route lists: mexjal.mex015d
137: Duplicate root in con_route lists: mexjal.mex015dteq
138: Duplicate root in con_route lists: mexnay.mex015d
139: Duplicate root in con_route lists: mexnay.mex015desc
140: Duplicate root in con_route lists: mexsin.mex015d
141: Duplicate root in con_route lists: mexson.mex015dobr
142: Duplicate root in con_route lists: mexson.mex015d
143: Duplicate root in con_route lists: mexson.mex015dnog
144: Duplicate root in con_route lists: mexchih.mex016d
145: Duplicate root in con_route lists: mexmich.mex037dlaz
146: Duplicate root in con_route lists: mexgro.mex037d
147: Duplicate root in con_route lists: mexmich.mex037d
148: Duplicate root in con_route lists: mexsin.mex040d
149: Duplicate root in con_route lists: mexdgo.mex040d
150: Duplicate root in con_route lists: mexcoah.mex040dmat
151: Duplicate root in con_route lists: mexcoah.mex040d
152: Duplicate root in con_route lists: mexnl.mex040d
153: Duplicate root in con_route lists: mexmich.mex043d
154: Duplicate root in con_route lists: mexgto.mex043d
155: Duplicate root in con_route lists: mexqro.mex045d
156: Duplicate root in con_route lists: mexgto.mex045d
157: Duplicate root in con_route lists: mexgto.mex045dleo
158: Duplicate root in con_route lists: mexzac.mex045d
159: Duplicate root in con_route lists: mexzac.mex045dvic
160: Duplicate root in con_route lists: mexzac.mex045dfre
161: Duplicate root in con_route lists: mexchih.mex045d
162: Duplicate root in con_route lists: mexchih.mex045dchi
163: Duplicate root in con_route lists: mexchih.mex045dvil
164: Duplicate root in con_route lists: mexmich.mex048d
165: Duplicate root in con_route lists: mexdgo.mex049dgom
166: Duplicate root in con_route lists: mexdgo.mex049d
167: Duplicate root in con_route lists: mexchih.mex049d
168: Duplicate root in con_route lists: mexcol.mex054d
169: Duplicate root in con_route lists: mexjal.mex054d
170: Duplicate root in con_route lists: mexemex.mex055d
171: Duplicate root in con_route lists: mexdf.mex057d
172: Duplicate root in con_route lists: mexemex.mex057d
173: Duplicate root in con_route lists: mexhgo.mex057d
174: Duplicate root in con_route lists: mexemex.mex057dsju
175: Duplicate root in con_route lists: mexslp.mex057d
176: Duplicate root in con_route lists: mexslp.mex057dmat
177: Duplicate root in con_route lists: mexcoah.mex057dsal
178: Duplicate root in con_route lists: mexcoah.mex057d
179: Duplicate root in con_route lists: mexnay.mex068d
180: Duplicate root in con_route lists: mexslp.mex070d
181: Duplicate root in con_route lists: mextam.mex070d
182: Duplicate root in con_route lists: mexjal.mex080d
183: Duplicate root in con_route lists: mexemex.mex085d
184: Duplicate root in con_route lists: mexhgo.mex085d
185: Duplicate root in con_route lists: mexnl.mex085d
186: Duplicate root in con_route lists: mexjal.mex090d
187: Duplicate root in con_route lists: mexgro.mex095daca
188: Duplicate root in con_route lists: mexgro.mex095dtax
189: Duplicate root in con_route lists: mexgro.mex095digu
190: Duplicate root in con_route lists: mexmor.mex095digu
191: Duplicate root in con_route lists: mexgro.mex095d
192: Duplicate root in con_route lists: mexmor.mex095d
193: Duplicate root in con_route lists: mexmor.mex115d
194: Duplicate root in con_route lists: mexpue.mex117d
195: Duplicate root in con_route lists: mextlax.mex117d
196: Duplicate root in con_route lists: mextlax.mex119d
197: Duplicate root in con_route lists: mexpue.mex119d
198: Duplicate root in con_route lists: mexhgo.mex119d
199: Duplicate root in con_route lists: mexpue.mex129d
200: Duplicate root in con_route lists: mexemex.mex132d
201: Duplicate root in con_route lists: mexhgo.mex132d
202: Duplicate root in con_route lists: mexpue.mex132d
203: Duplicate root in con_route lists: mexver.mex132d
204: Duplicate root in con_route lists: mexoax.mex135d
205: Duplicate root in con_route lists: mexpue.mex135d
206: Duplicate root in con_route lists: mexemex.mex136d
207: Duplicate root in con_route lists: mexpue.mex140d
208: Duplicate root in con_route lists: mextlax.mex140d
209: Duplicate root in con_route lists: mexpue.mex140dmax
210: Duplicate root in con_route lists: mextlax.mex140dmax
211: Duplicate root in con_route lists: mexpue.mex140dori
212: Duplicate root in con_route lists: mextlax.mex140dori
213: Duplicate root in con_route lists: mexpue.mex140dper
214: Duplicate root in con_route lists: mexver.mex140d
215: Duplicate root in con_route lists: mexver.mex140dgua
216: Duplicate root in con_route lists: mexver.mex140depl
217: Duplicate root in con_route lists: mexver.mex145d
218: Duplicate root in con_route lists: mextlax.mex150d
219: Duplicate root in con_route lists: mexpue.mex150d
220: Duplicate root in con_route lists: mexver.mex150d
221: Duplicate root in con_route lists: mexver.mex180d
222: Duplicate root in con_route lists: mexver.mex180dver
223: Duplicate root in con_route lists: mextab.mex180d
224: Duplicate root in con_route lists: mexcam.mex180d
225: Duplicate root in con_route lists: mexyuc.mex180d
226: Duplicate root in con_route lists: mexqroo.mex180d
227: Duplicate root in con_route lists: mexchis.mex190d
228: Duplicate root in con_route lists: mexcol.mex200d
229: Duplicate root in con_route lists: mexgro.mex200d
230: Duplicate root in con_route lists: mexhgo.mexm040d
231: Duplicate root in con_route lists: mexemex.mexm040dsma
232: Duplicate root in con_route lists: mexhgo.mexm040dsma
233: Duplicate root in con_route lists: mexemex.mexm040dsfr
234: Duplicate root in con_route lists: mexhgo.mexm040dsfr
235: Duplicate root in con_route lists: mexemex.mexm040dsah
236: Duplicate root in con_route lists: mexhgo.mexm040dsah
237: Duplicate root in con_route lists: mextlax.mexm040dsah
238: Duplicate root in con_route lists: mexhgo.mexm040demi
239: Duplicate root in con_route lists: mextlax.mexm040demi
240: Duplicate root in con_route lists: mextlax.mexm040d
241: Duplicate root in con_route lists: mexpue.mexm040d
242: Duplicate root in con_route lists: mexchih.chih007d
243: Duplicate root in con_route lists: mexchih.chih048d
244: Duplicate root in con_route lists: mexchih.chih056d
245: Duplicate root in con_route lists: mexemex.emex005d
246: Duplicate root in con_route lists: mexmor.pue438d
247: Duplicate root in con_route lists: mexpue.pue438d
248: Duplicate root in con_route lists: mexsin.sinae001
249: Duplicate root in con_route lists: mexslp.slp075d
250: Duplicate root in con_route lists: mexslp.slp080d
251: Duplicate list name: MEX-DGO MEX40D
252: Duplicate list name: MEX-SLP MEX70D
253: Duplicate list name: MEX-EMEX MEXM40DSah
254: Duplicate list name: MEX-HGO MEX57D
255: Duplicate list name: MEX-YUC MEX180D
256: Duplicate list name: MEX-HGO MEXM40DEmi
257: Duplicate list name: MEX-VER MEX140D
258: Duplicate list name: MEX-EMEX MEX15DMac
259: Duplicate list name: MEX-VER MEX132D
260: Duplicate list name: MEX-CHIH MEX45D
261: Duplicate list name: MEX-GRO MEX95DAca
262: Duplicate list name: MEX-PUE MEX140DMax
263: Duplicate list name: MEX-TAM MEX2D
264: Duplicate list name: MEX-NAY MEX15DEsc
265: Duplicate list name: MEX-EMEX MEX57D
266: Duplicate list name: MEX-ZAC MEX45D
267: Duplicate list name: MEX-TLAX MEX140DOri
268: Duplicate list name: MEX-GRO MEX95DTax
269: Duplicate list name: MEX-DF MEX57D
270: Duplicate list name: MEX-COL MEX200D
271: Duplicate list name: MEX-SLP SLP80D
272: Duplicate list name: MEX-MICH MEX14D
273: Duplicate list name: MEX-GTO MEX43D
274: Duplicate list name: MEX-BC MEX2D
275: Duplicate list name: MEX-CHIH MEX45DChi
276: Duplicate list name: MEX-PUE MEX119D
277: Duplicate list name: MEX-PUE MEX140DPer
278: Duplicate list name: MEX-EMEX MEX55D
279: Duplicate list name: MEX-EMEX MEX15D
280: Duplicate list name: MEX-NL MEX85D
281: Duplicate list name: MEX-CHIH MEX16D
282: Duplicate list name: MEX-GRO MEX95DIgu
283: Duplicate list name: MEX-MOR MEX95D
284: Duplicate list name: MEX-MICH MEX15D
285: Duplicate list name: MEX-TLAX MEXM40DEmi
286: Duplicate list name: MEX-DGO MEX49DGom
287: Duplicate list name: MEX-ZAC MEX45DVic
288: Duplicate list name: MEX-HGO MEXM40DSah
289: Duplicate list name: MEX-COL MEX54D
290: Duplicate list name: MEX-PUE MEX140D
291: Duplicate list name: MEX-JAL MEX54D
292: Duplicate list name: MEX-MICH MEX48D
293: Duplicate list name: MEX-MICH MEX15DMac
294: Duplicate list name: MEX-MICH MEX37DLaz
295: Duplicate list name: MEX-EMEX MEXM40DSFr
296: Duplicate list name: MEX-QRO MEX45D
297: Duplicate list name: MEX-NAY MEX15D
298: Duplicate list name: MEX-PUE MEX132D
299: Duplicate list name: MEX-GTO MEX45DLeo
300: Duplicate list name: MEX-CHIH CHIH7D
301: Duplicate list name: MEX-JAL MEX80D
302: Duplicate list name: MEX-BC MEX1D
303: Duplicate list name: MEX-SLP MEX57DMat
304: Duplicate list name: MEX-VER MEX150D
305: Duplicate list name: MEX-SON MEX15D
306: Duplicate list name: MEX-EMEX MEXM40DSMa
307: Duplicate list name: MEX-COAH MEX40DMat
308: Duplicate list name: MEX-PUE MEX135D
309: Duplicate list name: MEX-JAL MEX15D
310: Duplicate list name: MEX-VER MEX140DGua
311: Duplicate list name: MEX-TLAX MEXM40DSah
312: Duplicate list name: MEX-CHIH CHIH48D
313: Duplicate list name: MEX-HGO MEXM40D
314: Duplicate list name: MEX-HGO MEX119D
315: Duplicate list name: MEX-EMEX MEX136D
316: Duplicate list name: MEX-JAL MEX15DTeq
317: Duplicate list name: MEX-PUE MEX140DOri
318: Duplicate list name: MEX-MOR PUE438D
319: Duplicate list name: MEX-TLAX MEXM40D
320: Duplicate list name: MEX-SLP SLP75D
321: Duplicate list name: MEX-SON MEX15DNog
322: Duplicate list name: MEX-GTO MEX45D
323: Duplicate list name: MEX-GRO MEX95D
324: Duplicate list name: MEX-MICH MEX43D
325: Duplicate list name: MEX-EMEX MEX57DSJu
326: Duplicate list name: MEX-VER MEX145D
327: Duplicate list name: MEX-ZAC MEX45DFre
328: Duplicate list name: MEX-BCS MEX1D
329: Duplicate list name: MEX-VER MEX180D
330: Duplicate list name: MEX-COAH MEX57DSal
331: Duplicate list name: MEX-CHIH CHIH56D
332: Duplicate list name: MEX-PUE PUE438D
333: Duplicate list name: MEX-EMEX MEX85D
334: Duplicate list name: MEX-SIN SINAE1
335: Duplicate list name: MEX-JAL MEX90D
336: Duplicate list name: MEX-OAX MEX135D
337: Duplicate list name: MEX-TLAX MEX140DMax
338: Duplicate list name: MEX-QROO MEX180D
339: Duplicate list name: MEX-COAH MEX57D
340: Duplicate list name: MEX-PUE MEXM40D
341: Duplicate list name: MEX-DF MEX15DMex
342: Duplicate list name: MEX-EMEX MEX132D
343: Duplicate list name: MEX-CAM MEX180D
344: Duplicate list name: MEX-HGO MEXM40DSMa
345: Duplicate list name: MEX-HGO MEX85D
346: Duplicate list name: MEX-VER MEX180DVer
347: Duplicate list name: MEX-SON MEX15DObr
348: Duplicate list name: MEX-MOR MEX95DIgu
349: Duplicate list name: MEX-TLAX MEX150D
350: Duplicate list name: MEX-VER MEX140DEPl
351: Duplicate list name: MEX-GRO MEX200D
352: Duplicate list name: MEX-TLAX MEX117D
353: Duplicate list name: MEX-EMEX MEX15DMex
354: Duplicate list name: MEX-NL MEX40D
355: Duplicate list name: MEX-MICH MEX37D
356: Duplicate list name: MEX-CHIH MEX45DVil
357: Duplicate list name: MEX-SIN MEX40D
358: Duplicate list name: MEX-HGO MEXM40DSFr
359: Duplicate list name: MEX-HGO MEX132D
360: Duplicate list name: MEX-PUE MEX150D
361: Duplicate list name: MEX-SIN MEX15D
362: Duplicate list name: MEX-SLP MEX57D
363: Duplicate list name: MEX-DGO MEX49D
364: Duplicate list name: MEX-EMEX EMEX5D
365: Duplicate list name: MEX-PUE MEX129D
366: Duplicate list name: MEX-CHIS MEX190D
367: Duplicate list name: MEX-TAB MEX180D
368: Duplicate list name: MEX-MOR MEX115D
369: Duplicate list name: MEX-TAM MEX70D
370: Duplicate list name: MEX-PUE MEX117D
371: Duplicate list name: MEX-TLAX MEX140D
372: Duplicate list name: MEX-COAH MEX40D
373: Duplicate list name: MEX-CHIH MEX49D
374: Duplicate list name: MEX-NAY MEX68D
375: Duplicate list name: MEX-GRO MEX37D
376: Duplicate list name: MEX-TLAX MEX119D
</pre>

**Comment by neroute2** [comment]
They probably didn't have the problem because they changed from [country].[route] to [country-region].[route]. I don't know how to handle it here.

**Comment by jteresco** [comment]
Let's see what they have for ideas.  It seems silly to have to rename a bunch of files and list name entries only to rename them back once these replace the existing systems, but maybe that's what's needed.

**Comment by michihdeu** [comment]
http://forum.travelmapping.net/index.php?topic=3436

The route names of the new systems could get a "x" at the end like we did in Spain for eursf routes and do in France for eursf routes (freeways which are now part of a new tier 5 system). This must be undone when the systems are getting active.

**Comment by yakra** [comment]
What exactly is going on here?

**Comment by michihdeu** [comment]
Just a complete revision of active Mexican systems 😉

**Comment by neroute2** [comment]
yakra: https://github.com/TravelMapping/HighwayData/pull/3460

**Comment by yakra** [comment]
OK, so at #3460, I see a link to http://forum.travelmapping.net/index.php?topic=3165.msg16362#msg16362.

If I get this right, is it making new temp systems just for the sake of editing existing active systems? Why not just edit the active systems?

**Comment by neroute2** [comment]
The active systems have no maintainer, and my proposed changes have been stuck in limbo for more than four months: https://github.com/TravelMapping/HighwayData/pulls (this is only a small portion of the total changes)

**Comment by jteresco** [comment]
Given that the systems in Mexico were developed before many of our current guidelines were established, that they have been unmaintained for years, and that they are so lightly traveled, I'd be in favor of a clean start, bringing these back to devel/preview with the understanding that travelers will likely need to reenter most if not all of their entries.

**Comment by neroute2** [comment]
Most entries will probably not need to be reentered, since I kept alt names where they were in use. A few wpt files were renamed though.

**Comment by jteresco** [comment]
I'm going to comment out the new mexdn and mexedn lines for tonight to get an update to run, but hopefully we can move forward on this very soon.

Am I correct that it makes sense to close #3073, #3074, #3093, and #3115 as the intent is to use these new systems?

**Comment by neroute2** [comment]
Yes, the old pull requests are part of this one.

**Pull request merged**
