### PR TITLE
update regions.csv

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by michihdeu** [comment]
Thanks. What's about continents.csv, countries.csv and regions_countries_continents.csv?

**Comment by si404** [comment]
The other csvs are mostly superfluous, and I've got the continents and multi-region countries in this one.

**Comment by michihdeu** [comment]
Exactly. That's why I asked. I think if they are not used, they should be deleted.

**Comment by jteresco** [comment]
I use countries.csv and continents.csv.  I have not used the regions_countries_continents.csv file and have no plans to do so.

**Comment by jteresco** [comment]
At this point, the new information in regions.csv is used only for graph generation, but does open up the possibility of country and continent based stats.  Any effort on my part to do that will have to wait a bit, though.  My focus needs to be on the graph stuff for the paper I plan to submit next week.

**Comment by michihdeu** [comment]
> I use countries.csv and continents.csv.

Where are they used? I can't see them on TM front-end. Are they used for the academical project only?

**Comment by jteresco** [comment]
I load them into the site update code and use the information in various places.  The information also populates DB tables.  For example, the HB does a join on the countries table to look up country names based on codes stored in other tables.

**Comment by michihdeu** [comment]
Ok. But is it really necessary to have redundant information or could it be changed in the code one day? If it's not possible to drop these files, they should be updated like regions.csv.

**Comment by jteresco** [comment]
I'm no database expert, but I do know that we want to avoid redundant information.  Which is exactly why things like the country name for USA or GBR and the continent name for NA or EUR should be kept in one place and not repeated over and over in regions.csv.

**Comment by si404** [comment]
OK - feel free to remove again, but ASI, GBR and EUR were in regions.csv before today as elsewise it displayed the systems like eure wrong, not knowing what region it was in. I don't know how CAN and USA worked, but somehow they did.

**Comment by jteresco** [comment]
An issue to think about this and a potentially more radical change: https://github.com/TravelMapping/HighwayData/issues/1336

**Comment by jteresco** [comment]
Re: @si404 my reply about redundancy was to @michihdeu 's last comment here.  I think it's fine to have the countries and continents in for now at least.  I just didn't want to eliminate something like countries.csv and have to put "North America" over and over in the other files.

**Comment by jteresco** [comment]
I'm going to pull this in and see what happens.  I don't anticipate any problems.

**Comment by jteresco** [comment]
I don't think they caused any immediate problems, but the site update with the new csv files produced some error messages:

ERROR: Could not find country matching regions.csv line: AFR;Africa;AFR;AFR;Continent

ERROR: Could not find country matching regions.csv line: IOT;British Indian Ocean Territory;IOT;ASI;Overseas Territory

ERROR: Could not find country matching regions.csv line: NA;North America;NA;NA;Continent

ERROR: Could not find country matching regions.csv line: OCE;Oceania;OCE;OCE;Continent

ERROR: Could not find country matching regions.csv line: PCN;Pitcairn;PCN;OCE;Overseas Territory

ERROR: Could not find country matching regions.csv line: SA;South America;SA;SA;Continent

ERROR: Could not find country matching regions.csv line: SGS;South Georgia and the South Sandwich Islands;SGS;ATA;Overseas Territory

ERROR: Could not find country matching regions.csv line: SHN;Saint Helena, Ascension and Tristan da Cunha;SHN;AFR;Overseas Territory

ERROR: Could not find country matching regions.csv line: TCA;Turks and Caicos Islands;TCA;NA;Overseas Territory

ERROR: Could not find country matching regions.csv line: VGB;Virgin Islands (British);VGB;NA;Overseas Territory

**Pull request merged**
