### PR TITLE
BIH, NSW, ENG, JPN, CYP

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by jteresco** [comment]
Not sure I'm liking that site update now fails from a malformed systemupdates.csv entry...

**Comment by si404** [comment]
That's weird - I can see the entry screw ups, but it passed the datacheck.sh. Unless the change of that file wasn't quite synced in when I started the process.

**Comment by jteresco** [comment]
I bet you need to update your DataProcessing repository to include @yakra's latest changes to the site update program.

**Comment by michihdeu** [comment]
Mine was automatically updated.

I always run:
`cd ~/DataProcessing/siteupdate/python-teresco`
`git pull`
`sh datacheck.sh`

**Comment by michihdeu** [comment]
I'll make my change to systems.csv again which was undone by this pull request......

**Comment by michihdeu** [comment]
I hate that I need to check 158 changed files to figure out what happens.... Anything was also added to Japan...

**Comment by michihdeu** [comment]
No idea what will happen to BIH.... made screen shots so that I can reconstruct the active system from scratch if required..... one day....

**Comment by si404** [comment]
> Mine was automatically updated.
> 
> I always run:
> `cd ~/DataProcessing/siteupdate/python-teresco`
> `git pull`
> `sh datacheck.sh`

That what I did - I think the systemsupdate.csv change was still syncing in.

**Pull request merged**
