### PR TITLE
unused .wpts

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by jteresco** [comment]
Need to put hwy_data/WY/usawy/wy.wy051condou.wpt back - it still has a .csv entry.

**Comment by si404** [comment]
That was me making a stupid typo - it's WY59 Connector (Douglas). Fixed it locally, so can readd with next pull request.

**Comment by jteresco** [comment]
I got it locally as well.  No need for a pull request.

**Comment by jteresco** [comment]
Pushed back to master.

**Comment by si404** [comment]
Thanks (he said sarcastically), that just screwed me over, giving me a non-existent conflict that I can't fix, so I can't sync between local and my branch.

Now I can't do the pull request that I was 5 minutes from finishing that was much much more than just fixing that typo.

**Comment by jteresco** [comment]
Sorry about that - was hoping I got it in quickly enough that you wouldn't have had any other changes yet.  Can you remove just the commits of usawy.csv and usawy_con.csv from your pull request?

**Comment by si404** [comment]
I tried that. I tried changing the file in TM to match mine. I closed and reopened the Github for Windows program several times. Neither worked as the issue was with Github for Windows, rather than the existence of a conflict or not.

I've ended up grabbing the regions unmerged changes and moving them outside the local GitHub repository, grabbing a zip of TM/Highway Data, deleting all the files in my local repository and then putting the .zip in there. Hopefully then it should work.

**Comment by jteresco** [comment]
https://xkcd.com/1597/

**Pull request merged**
