### PR TITLE
Update ms.i055.wpt

### PR DESCRIPTION
**Pull request by ajfroggie**
Correction for a missing waypoint along the I-20/55 concurrency in Jackson.

### CODE REVIEW

**Comment by yakra** [comment]
880d15f745d2fc880652dc99e9994d160fb79e47: why the label change? I-55 is an exit-numbered route, so 44(20) etc. are the correct syntax.

**Comment by ajfroggie** [comment]
http://tm.teresco.org/forum/index.php?topic=1793.0

**Comment by yakra** [comment]
That doesn't explain the label syntax change though.

**Comment by ajfroggie** [comment]
This is how the MS lists have always been, and before I realized Tim had implemented a change to CHM labeling.  At this point, given their use, I'm just going to leave it as-is.

**Comment by yakra** [comment]
> This is how the MS lists have always been

[It's not though.](https://github.com/TravelMapping/HighwayData/blob/master/chm_final/usai/ms.i055.wpt#L31-L33) If it had been, there'd be nothing to change!
Tim didn't change anything; Interstates have always used ["Interchanges on exit-numbered highways"](http://travelmapping.net/devel/manual/wayptlabels.php) style labeling.
Canonical exmple: [IA I-35](https://github.com/TravelMapping/HighwayData/blob/b1e1296c93fd22dbad7107ae3e3f96cadb45da6d/hwy_data/IA/usai/ia.i035.wpt#L20-L28)

**Pull request merged**
