### PR TITLE
TUR O5 new openings

### PR DESCRIPTION
**Pull request by rmihailucian**

### CODE REVIEW

**Comment by michihdeu** [comment]
On the other hand, TUR O5 has no traveler. That means, the `altRouteNames` are not required.

**Comment by rmihailucian** [comment]
> On the other hand, TUR O5 has no traveler. That means, the `altRouteNames` are not required.

I have just added them. Should I keep the alt Label or remove them?

**Comment by michihdeu** [comment]
Leave them but remove the blank

**Comment by rmihailucian** [comment]
Improved updates.csv, adding the exit numbers of the new routes.

**Comment by michihdeu** [comment]
Data check successful!

**Pull request merged**
