### PR TITLE
ESP boundaries csv fixes

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by jteresco** [comment]
Closer this time:

```
Sun Jun 18 15:01:53 EDT 2017
testsiteupdate.sh: launching siteupdate.py
[0.0] Reading region, country, and continent descriptions.
[0.0] Reading systems list in ../../../HighwayData/railsystems.csv.  cantch.englu.engcc.engch.engdlr.enghc.enghx.englo.engtfl.usamnmt.espab.ERROR: System mismatch parsing line [], expected espab
ERROR: System mismatch parsing line [], expected espab
ERROR: System mismatch parsing line [], expected espab
ERROR: System mismatch parsing line [], expected espab
ERROR: System mismatch parsing line [], expected espab
ERROR: System mismatch parsing line [], expected espab
ERROR: System mismatch parsing line [], expected espab
ERROR: Could not find Route matching root espvc.a007val in system espab.
ERROR: No roots in _con.csv line [espab;A7;;Valencia;espvc.a007val]
eursfb.eureb.ERROR: Could not find Route matching root esppv.e5arm in system eureb.
espnb.ERROR: Could not find Route matching root espan.n004ele in system espnb.
ERROR: Could not find Route matching root espri.n232pan in system espnb.
ERROR: Could not find Route matching root espar.n232afue in system espnb.
ERROR: No roots in _con.csv line [espnb;N232a;;Fuentes de Ebro;espar.n232afue]
ERROR: Could not find Route matching root espmc.n301 in system espnb.
ERROR: Could not find Route matching root espan.n420 in system espnb.

Ignored comment in railsystems.csv: # one must exist in the update code
[0.1] Checking for duplicate list names in routes, roots in routes and connected routes.
Check FAILED: 880 routes != 872 connected route roots, see datacheck.
Added 8 ROUTE_NOT_IN_CONNECTED datacheck entries.
Found 1 DUPLICATE_LIST_NAME cases.
Added 2 DUPLICATE_LIST_NAME datacheck entries.
[0.1] Finding all .wpt files. 34327 files found.
[0.4] Reading waypoints for all routes.
cantch.................................!
englu........................!
engcc....!
engch.....!
engdlr......!
enghc.!
enghx.!
englo.............!
engtfl.!
usamnmt..!
espab.......................Exception in thread Thread-1:
Traceback (most recent call last):
  File "/sw/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "./siteupdate.py", line 2075, in run
    read_wpts_for_highway_system(h)
  File "./siteupdate.py", line 2047, in read_wpts_for_highway_system
    r.read_wpt(all_waypoints,all_waypoints_lock,datacheckerrors,args.highwaydatapath+"/hwy_data")
  File "./siteupdate.py", line 702, in read_wpt
    with open(path+"/"+self.region + "/" + self.system.systemname+"/"+self.root+".wpt", "rt",encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ESP-MD/espab/espmd.r003.wpt'
```

**Comment by jteresco** [comment]
Here's a slightly more useful one.  One of the error printouts was omitting the actual offending line.

`testsiteupdate.sh: launching siteupdate.py
[0.0] Reading region, country, and continent descriptions.
[0.0] Reading systems list in ../../../HighwayData/railsystems.csv.  cantch.englu.engcc.engch.engdlr.enghc.enghx.englo.engtfl.usamnmt.espab.ERROR: System mismatch parsing line [eure;ESP-PV;AP68;;;;esppv.ap068;], expected espab
ERROR: System mismatch parsing line [eure;ESP-CL;AP68;;;;espcl.ap068;], expected espab
ERROR: System mismatch parsing line [eure;ESP-RI;AP68;;;Logrono;espri.ap068;], expected espab
ERROR: System mismatch parsing line [eure;ESP-NC;AP68;;Sar;Sartaguda;espnc.ap068sar;], expected espab
ERROR: System mismatch parsing line [eure;ESP-RI;AP68;;Cal;Calahorra;espri.ap068cal;], expected espab
ERROR: System mismatch parsing line [eure;ESP-NC;AP68;;;Tudela;espnc.ap068;], expected espab
ERROR: System mismatch parsing line [eure;ESP-AR;AP68;;;;espar.ap068;], expected espab
ERROR: Could not find Route matching root espvc.a007val in system espab.
ERROR: No roots in _con.csv line [espab;A7;;Valencia;espvc.a007val]
eursfb.eureb.ERROR: Could not find Route matching root esppv.e5arm in system eureb.
espnb.ERROR: Could not find Route matching root espan.n004ele in system espnb.
ERROR: Could not find Route matching root espri.n232pan in system espnb.
ERROR: Could not find Route matching root espar.n232afue in system espnb.
ERROR: No roots in _con.csv line [espnb;N232a;;Fuentes de Ebro;espar.n232afue]
ERROR: Could not find Route matching root espmc.n301 in system espnb.
ERROR: Could not find Route matching root espan.n420 in system espnb.

Ignored comment in railsystems.csv: # one must exist in the update code
[0.0] Checking for duplicate list names in routes, roots in routes and connected routes.
Check FAILED: 880 routes != 872 connected route roots, see datacheck.
Added 8 ROUTE_NOT_IN_CONNECTED datacheck entries.
Found 1 DUPLICATE_LIST_NAME cases.
Added 2 DUPLICATE_LIST_NAME datacheck entries.
[0.1] Finding all .wpt files. 34327 files found.
[0.2] Reading waypoints for all routes.
cantch.................................!
englu........................!
engcc....!
engch.....!
engdlr......!
enghc.!
enghx.!
englo.............!
engtfl.!
usamnmt..!
espab.......................Exception in thread Thread-1:
Traceback (most recent call last):
  File "/sw/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "./siteupdate.py", line 2075, in run
    read_wpts_for_highway_system(h)
  File "./siteupdate.py", line 2047, in read_wpts_for_highway_system
    r.read_wpt(all_waypoints,all_waypoints_lock,datacheckerrors,args.highwaydatapath+"/hwy_data")
  File "./siteupdate.py", line 702, in read_wpt
    with open(path+"/"+self.region + "/" + self.system.systemname+"/"+self.root+".wpt", "rt",encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/ESP-MD/espab/espmd.r003.wpt'
`

**Comment by si404** [comment]
Thanks Jim, those error messages have been a real help in fixing it all.

**Comment by jteresco** [comment]
Good to hear.  I can't believe I left that out for so long.  Or maybe it got cut out by mistake somewhere recently.

**Pull request merged**
