### PR TITLE
Finish usatn

### PR DESCRIPTION
**Pull request by mapcat**

### CODE REVIEW

**Comment by mapcat** [comment]
@jteresco the usatn.csv file I'm submitting in this pull is different from the one in the master since you edited it after I submitted the last pull. Sorry for not updating my fork...I didn't think I would be submitting anything that had a conflict since none of the files I updated this time would typically be edited by someone else.

**Comment by jteresco** [comment]
@mapcat Disregard my email.  I should be able to resolve the conflict easily enough on my end.

**Comment by mapcat** [comment]
Thanks!

**Comment by jteresco** [comment]
Well, this is much messier than any I've tried to resolve before.  It's showing a ton of other changes in the branch, including a bunch of things in usaky5 and usaky4.  Let me see if I can figure out what's up.

**Comment by jteresco** [comment]
How long ago was  mapcat-master  last updated to include other changes to the master on GitHub?

**Comment by mapcat** [comment]
Last week? I don't see how you would have gotten any usaky4 or usaky5 in
there since they don't exist in my master.

**Comment by rickmastfan67** [comment]
Only conflict I see on the web site pull is the 'usatn.csv' file.  No mention of usaky4 or usaky5 here.

**Comment by mapcat** [comment]
Last update to my fork was the 14th.

**Comment by rickmastfan67** [comment]
Did you 'delete' the usaky4 or usaky5 on your master mapcat?

**Comment by mapcat** [comment]
Yes, back when all of them were merged in last year.

**Comment by rickmastfan67** [comment]
That could be the problem then.  You might want to completely delete your 'master' and create a brand new 'fork'.

**Comment by mapcat** [comment]
I had to do that once before, but I think it was after usaky was finished. I'll check.

**Comment by rickmastfan67** [comment]
That or work from a 'branch' of the main database.

**Comment by mapcat** [comment]
I trashed my old fork on 11/2 and recreated that day. All the usaky* were merged together on 11/5. But I've successfully submitted well over a dozen pull requests from my fork's master since then. What did I do?

**Comment by jteresco** [comment]
I think it's not as bad as I thought - let me try something here.  The other file that had major conflicts was datacheckfps.csv.

**Comment by mapcat** [comment]
I know I didn't edit datacheckfps this time and haven't since last year.

**Comment by rickmastfan67** [comment]
As I mentioned Jim, there is only one conflict showing here on my end, and it's this:


Conflicting files
hwy_data/_systems/usatn.csv

Don't know why you have others showing on your end to be honest.

**Comment by jteresco** [comment]
Please have a look at the usatn stuff now in the master on GitHub.  I think it might all be in.

**Comment by mapcat** [comment]
@rickmastfan67 That's exactly what I see.
@jteresco Thanks. Still wondering what happened.

**Comment by mapcat** [comment]
@jteresco the master looks good...all the new files I added and the edits I made to the older files are all showing.

**Comment by jteresco** [comment]
I'm also wondering how the old usaky4 and usaky5 files (and just a handful of them it turns out, not all as I first thought) and datacheckfps.csv got involved in this.

**Comment by mapcat** [comment]
@jteresco It was still messed up when I tried to update my fork so I nuked it. New fork makes no mention of usaky4 etc.

**Comment by jteresco** [comment]
OK, so hopefully this will resolve remaining issues.

**Pull request merged**
