### PR TITLE
opening Braila Danube bridge

### PR DESCRIPTION
**Pull request by rmihailucian**
@michihdeu please perform datacheck on this one

### CODE REVIEW

**Comment by michihdeu** [comment]
btw, I think about traveling the bridge at the end of September @rmihailucian 😉

**Comment by michihdeu** [comment]
I fail to sync the changes to my local machine 😢 I don't get it....

What needs to be changed:
- roudn22s.wpt -> roudn02s.wpt _(rename file name)_
- roudn.dn22j.wpt DN22S -> DN2S _(rename wp label)_
- roudn.csv DN22S -> D2S _(rename route name and reorder)_
- roudn_con.csv DN22S -> D2S _(rename route name and reorder)_
- updates.csv DN22S -> DN2S _(rename route name)_
- updates.csv rou.dn22s -> rou.dn02s _(rename root)_

@jteresco could you make the modifications, please?

**Comment by michihdeu** [comment]
It finally worked now. I do the changes now.

**Comment by michihdeu** [comment]
All fine. Data check successful.

**Comment by rmihailucian** [comment]
@michihdeu thanks a lot!

**Pull request merged**
