### PR TITLE
WA and ID updates

### PR DESCRIPTION
**Pull request by compdude**
Various updates to WA and ID:
-Fixing NMPs at border waypoints
-Removing some unused alt labels
-Renaming waypoint at west end of I-90 (old waypoint kept as alt label)
-Truncating ID 71 at northern end and adding updates entry for this change

### CODE REVIEW

**Comment by yakra** [comment]
Where does AtlSt come from? I see 4th Ave and Edgar Martinez Dr.
Everything else looks excellent.

Zoinks - I just had to check out the 2-state US195Spr in GMSV, and it appears to only be signed TO 95 / TO 195. Looks like this may not be a keeper... :(

**Comment by compdude** [comment]
Oops, for some reason I forgot that it's called Edgar Martinez Drive there.

As for the US 195 spur route, I'm surprised that was even added to CHM/TM
in the first place. The Google Street view along the spur route dates from
~2008-9, and even that has a TO 195 sign on the Idaho side and no US 195
Spur signs. I guess this is not unlike Washington's other short spur routes
that aren't signed.

I will make these changes when I get home from work tonight.

**Comment by yakra** [comment]
We went pretty heavy on the unsigned/apocryphal US Routes *(ME US1 AltBus (Bangor), anyone?)* in CHM's early days, then removed many of them. No big surprise that there are still a few kicking around.

**Comment by jteresco** [comment]
Good to go?

**Comment by compdude** [comment]
Not quite yet. Give me another hour or so.

**Comment by jteresco** [comment]
No rush, I'll have it go in tomorrow instead.  Tonight's update has completed.

**Comment by compdude** [comment]
Okay, it should be good to go now for tomorrow's update.

**Comment by compdude** [comment]
Okay, _now_ it should be all good to go for the next update. Forgot to do the change to I-90.

**Pull request merged**
