### PR TITLE
Fix OR-US26 NMP with OR-US97

### PR DESCRIPTION
**Pull request by eeffaann**

### CODE REVIEW

**Comment by michihdeu** [comment]
@eeffaann have you agreed with Bickendan to edit routes of his region?

**Comment by michihdeu** [comment]
Learn more:

https://forum.travelmapping.net/index.php?topic=42
https://travelmapping.net/participate.php#hwydatamanager

**Comment by rickmastfan67** [comment]
@Bickendan

**Comment by eeffaann** [comment]
Thanks for adding @Bickendan in. Caught a NMP in my travels and METAL also indicates this is an NMP. Otherwise please review/comment/reject the PR as appropriate.

**Comment by michihdeu** [comment]
We have a (still open) forum thread for it: https://forum.travelmapping.net/index.php?topic=4984

**Comment by jteresco** [comment]
https://github.com/TravelMapping/HighwayData/commit/933f97e10c7b323d711feeb5e30ae22f30663b79

**Pull request closed without merging**
