### PR TITLE
usaky4 & usaky5 fixes

### PR DESCRIPTION
**Pull request by mapcat**
**Please do not change the datacheckfps.csv file.** I was unable to remove it from the pull request. I need to edit it but can't do that until I can update it in my fork, which I'm unable to do until this pull request is completed. Thanks.

### CODE REVIEW

**Comment by jteresco** [comment]
I'm not going to merge this one in, since it deletes 10,000+ lines from the datacheckfps.csv.  I'm investigating how best to bring the other parts in.  Probably won't happen until Sunday some time.

**Comment by yakra** [comment]
@mapcat, can you copy the file currently in TravelMapping/master, then paste that into the file in yiour fork?

**Comment by mapcat** [comment]
> @mapcat, can you copy the file currently in TravelMapping/master, then paste that into the file in yiour fork?

Already tried that. Didn't help unfortunately.

**Comment by jteresco** [comment]
I was able to "cherry pick" (that's an actual command-line git option) the commits from this pull request and have pushed them to the master.  That should take care of the changes (minus any to datacheckfps.csv).

As for getting the fork back to a good place, the easiest thing to do might be to create a new fork for future changes.  There are some things I think we could try on the command line but I don't know that they'll be possible through the web interface.

**Comment by jteresco** [comment]
Closing this pull request now that the intended parts have been merged to the master.

**Pull request closed without merging**
