### PR TITLE
Part 1 of 2024 GA updates

### PR DESCRIPTION
**Pull request by ntallyn**
Part 1 of 2024 GA updates

### CODE REVIEW

**Comment by rickmastfan67** [comment]
@ntallyn, did you see my comments in the fourm about the I-75 Business
routes?  You might want to comment on it before this is pulled in.

Same goes for GA-201.

Thanks.

**Comment by jteresco** [comment]
I'll hold off on this for now, then.

**Comment by ntallyn** [comment]
Patch submitted. Re-added I-75 BL Valdosta; renamed US41_S point on GA201. Added minor realignment of US84/GA38 in Bainbridge (was in my queue before I saw these comments).

**Comment by rickmastfan67** [comment]
Those GA fixes look good to me now.

However, I'm not sure what the heck is happening with the 'updates' csv
file. Several non-Georgia updates are marked for deletion, like 25+!

Not sure how we want to fix that issue.

**Comment by ntallyn** [comment]
I merged into my branch before I started, but forgot to do the same before I pushed. I think it's fixed now.

**Comment by rickmastfan67** [comment]
Just checked it again. Still 25+ entries marked for deletion. Mostly stuff
that was added in the last few days sadly.

**Comment by ntallyn** [comment]
I think I have it fixed now.

**Comment by rickmastfan67** [comment]
Looks good on my end now. :)

Jim, I think we're now safe to have this pulled in tonight when you're
ready to do the update.

**Comment by rickmastfan67** [comment]
@ntallyn new issue with GA-201 discovered.  A point that should have been removed with the reroute wasn't, and thus causing a jump back to the 'old' alignment.

Just deleting the 'VarRd_S' point should fix this issue in a separate PR.  But it's something that should be addressed ASAP.

**Comment by ntallyn** [comment]
Looks like I fixed it in the waypoint editor but failed to copy it back to the .wpt file. It's in a separate pull request.

Incidentally, I think the updates.csv issue was that I had the file open in the editor when I merged from upstream/master, so when it said that another file had modified the file, I ignored it. Oops on me.

**Pull request merged**
