### PR TITLE
systems to preview

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by si404** [comment]
2016-03-11;Jamaica;T3;jam.t003;Route extended at south end from the A1 at Angels to the A1 at Caymanas

**Comment by yakra** [comment]
Do you have any more updates entries forthcoming? I can add the lines to updates.csv in my pull request.

**Comment by si404** [comment]
just that one

**Comment by jteresco** [comment]
I won't make any updates.csv changes, then.  I plan to merge these in a bit later tonight, assuming all updates.csv entries made it in.

**Comment by si404** [comment]
The update for Jamaica isn't (currently) in updates.csv due to my email checker being slow and thus two hours between Eric's post seeking a quick response and my response. You will need to add it Jim (unless Eric makes a new commit).

**Comment by yakra** [comment]
I'm away from my computer now, using the mobile site. (Which I didn't think would be the case.) Probably best to have Jim add it in.

**Comment by jteresco** [comment]
I'll add it - easy enough.

**Comment by jteresco** [comment]
Renaming AZE/armm/arm.m012.wpt to AZE/armm/aze.m012.wpt, please verify that this is what was intended.

**Comment by jteresco** [comment]
No file WY/usawy/wy.031sprman.wpt, removing from usawy's csv files.  Please restore those entries and provide the wpt file if this is supposed to be included.

**Pull request merged**
