### PR TITLE
Create co.co110.wpt

### PR DESCRIPTION
**Pull request by chrislwillers**
Adding in Highway 110 in Silverton.

### CODE REVIEW

**Comment by michihdeu** [comment]
@chrislwillers why do you want to add it?

**Comment by jteresco** [comment]
@chrislwillers Thanks for the contribution, but instead, please discuss over in the forum, and the maintainer of Colorado State Highways will add this if deemed appropriate.

**Comment by chrislwillers** [comment]
Because the road exists, yet isn't in the database.

Also, as an aside, there is a .wpt file for CO 57, but in the table on the
highway browser, it is not listed.  Not sure if you can help with that.

**Comment by chrislwillers** [comment]
Gotcha.  Was unaware that's how it worked.  Was just flipping through the
Github repository.

**Comment by jteresco** [comment]
Let me know if you have trouble getting a forum account set up.  Some email systems do not accept the auto-generated emails that are needed during registration.  terescoj@gmail.com

**Comment by chrislwillers** [comment]
I just attempted to sign up a couple of minutes ago but haven't gotten the
registration email.

**Comment by jteresco** [comment]
I just activated your account.

**Comment by jteresco** [comment]
Thread: http://forum.travelmapping.net/index.php?topic=3574.0

**Pull request closed without merging**
