### PR TITLE
usapr to preview

### PR DESCRIPTION
**Pull request by mapcat**

### CODE REVIEW

**Comment by jteresco** [comment]
I can run a site update now.  Should I wait for further activity on this pull request?

**Comment by mapcat** [comment]
Please go ahead whenever you're ready. Sorry for missing your comment.

**Comment by jteresco** [comment]
No problem - I'm grading all afternoon and a site update is a nice diversion.

**Comment by mapcat** [comment]
I know the feeling! Have fun wrapping up the semester.

**Pull request merged**
