### PR TITLE
Add new devel system: CHN-GD Guangdong Provincial Expressways

### PR DESCRIPTION
**Pull request by eeffaann**

### CODE REVIEW

**Comment by michihdeu** [comment]
@eeffaann did you run data check after your latest Systems.csv modification? No file of your PR was included before….

**Comment by eeffaann** [comment]
> @eeffaann did you run data check after your latest Systems.csv modification? No file of your PR was included before….

Does datacheck check against your non-master branch? I thought it only does that, so I haven't put done it yet, but will do once the other PR merges.

**Comment by michihdeu** [comment]
Fine. I just wanted to be sure that we won't face a failed site update. I have only one branch. I have no need for more.

**Comment by eeffaann** [comment]
!!! DATA CHECK SUCCESSFUL !!!

**Comment by yakra** [comment]
> Does datacheck check against your non-master branch

It works on whatever the currently checked-out branch is.
So to run DC directly on this branch, first you could `git checkout eeffaann-chngds-new`, then do a `/fast/tm/datacheck` normally.

Afterward, to reset the checked-out commit to whatever it was before (whether master or something else), you can do
`git checkout HEAD@{1}`

**Comment by eeffaann** [comment]
OK Data check successful for both my master and the branch i was working on.

**Comment by michihdeu** [comment]
> > Does datacheck check against your non-master branch
> 
> It works on whatever the currently checked-out branch is. So to run DC directly on this branch, first you could `git checkout eeffaann-chngds-new`, then do a `/fast/tm/datacheck` normally.
> 
> Afterward, to reset the checked-out commit to whatever it was before (whether master or something else), you can do `git checkout HEAD@{1}`

Thanks. I think it's worth to extend the [manual](https://github.com/TravelMapping/DataProcessing/blob/master/SETUP.md) @yakra could you do it?

**Comment by yakra** [comment]
Before doing that:
#618 Option on datacheck to do a git checkout of a branch

**Comment by yakra** [comment]
Before doing that:
https://github.com/TravelMapping/DataProcessing/issues/618

**Pull request merged**
