### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by michihdeu** [comment]
If you merge it, I could run a data check......

**Comment by si404** [comment]
go for it.

**Comment by michihdeu** [comment]
1: Route contains fewer than 2 points: pol.dw264 (1 total points)

**Comment by si404** [comment]
dealt with

**Comment by michihdeu** [comment]
```
[329.8] Processed 297 highway systems.
Processed 46589 routes with a total of 756288 points and 709699 segments.
Data check successful!
Total run time: [329.9]
Wed Aug 15 13:37:07 EDT 2018
datacheck.sh: complete
```

**Pull request merged**
