### PR TITLE
PEI 2015-09-03

### PR DESCRIPTION
**Pull request by yakra**
15-09-03;(Canada) Prince Edward Island;PE 116;pe.pe116;Extended East from PE 1 to PE 246
15-09-03;(Canada) Prince Edward Island;PE 121;pe.pe121;Route added
15-09-03;(Canada) Prince Edward Island;PE 125;pe.pe125;Extended East 0.15 mi. from PE 2 to end of pavement
15-09-03;(Canada) Prince Edward Island;PE 146;pe.pe146;Extended West from PE 148 to PE 14
15-09-03;(Canada) Prince Edward Island;PE 156;pe.pe156;Extended North from Back Settlement Road to PE14
15-09-03;(Canada) Prince Edward Island;PE 162;pe.pe162;Truncated east end approx. 0.6 mi. from the Gulf of Saint Lawrence to PE 12
15-09-03;(Canada) Prince Edward Island;PE 168;pe.pe168;Truncated north end from 46.732224°, -64.015950° to an unnamed road junction at 46.713234°, -64.033191°
15-09-03;(Canada) Prince Edward Island;PE 183;pe.pe183;Route added
15-09-03;(Canada) Prince Edward Island;PE 212;pe.pe212;Extended South approx. 1 mi. from PE 1 to change in pavement/centerline striping
15-09-03;(Canada) Prince Edward Island;PE 236;pe.pe236;Extended South from Royalty Road to Brighton Road
15-09-03;(Canada) Prince Edward Island;PE 241;pe.pe241;Extended West from New London Road to PE 224
15-09-03;(Canada) Prince Edward Island;PE 343;pe.pe343;Extended North from PE 3 to PE 342
15-09-03;(Canada) Prince Edward Island;PE 344;pe.pe344;Extended South from Portage Road to PE 311

### CODE REVIEW

**Comment by yakra** [comment]
I'm unsure how that Merge pull request #2, merge Arkansas 2015-09-03 to yakra/master got in here. I merged that into yakra/master before I split this branch *from* yakra/master. What the...

**Comment by rickmastfan67** [comment]
That's why you don't merge into your own master from your branches.  I personally only update my master after a few days, that's when my branch fixes get pulled in via the Master.

**Comment by yakra** [comment]
Right. Grumble. I can accept that's how I should[n't] do it. But I'd love to understand the how and why.
Shouldn't git be intelligent enough to see that the commits in that branch/merge have already been merged into the TravelMapping master?
And it doesn't seem completely intuitive to me how a merged pull request, something containing a bunch of commits, it listed as a commit in its own right...

**Comment by jteresco** [comment]
This is something I need to get better at also and hope to be able to write out in an easily understandable way.  Last weekend I had two branches for two separate fixes, and the second contained all of the changes from the first.  It's possible my second branch was a branch off the first branch instead of directly from my fork's master.

**Comment by jteresco** [comment]
But anyway... if this one's ready to go, I'm planning to pull it in this evening, gather up all of the new updates entries, and run a site update.

**Comment by ovoss** [comment]
I'm still belatedly assembling the pull request for jeffm's IL/MO/SD/WI 
changes. Since yakra's Arkansas changes modified four of the csv files 
affected by jeffm's changes, I'll wait for the yakra's changes to hit the 
master, so I can add jeffm's changes to the latest csv files.

Oscar

----- Original Message -----

**Comment by jteresco** [comment]
This is pulled in and I've added the updates entries to my local copy to be pushed up later.

**Pull request merged**
