### PR TITLE
cansf preview -> active

### PR DESCRIPTION
**Pull request by mapcat**

### CODE REVIEW

**Comment by yakra** [comment]
ping @rickmastfan67

**Comment by jteresco** [comment]
Holding off pending review.

**Comment by rickmastfan67** [comment]
Looks ok to me, sans needing separate news entries for the rename of the DVP & Gardner files for the normal updates area IMO since they were active routes.

**Comment by mapcat** [comment]
@rickmastfan67 Is that really necessary, since I added them as alt names? No one needs to change their .list.

**Comment by jteresco** [comment]
Looks to me like the AltRouteName is sufficient here.

**Comment by yakra** [comment]
Still worth an updates entry IMO.
I've done then for redesignated routes. It's helpful if someone clinches some more mileage on the Creek Turnpike, goes looking for the Creek Turnpike in the HB and can't find it anymore. "Oh, it's OK364 now."

Maybe something as simple as "Moved from Ontario Provincial Freeways to Canada Select Named Freeways".
Might not be worth the bother of mentioning a new .list name or any of that; people can see that in their userlogs.

**Comment by mapcat** [comment]
How's that look now?

**Comment by rickmastfan67** [comment]
Looks good to me now. ;)

**Pull request merged**
