### PR TITLE
turd corrections (prepare for preview)

### PR DESCRIPTION
**Pull request by rmihailucian**

### CODE REVIEW

**Comment by michihdeu** [comment]
@rmihailucian before preview you should create csv files and bring it to devel first. Let me know if you need help

**Comment by si404** [comment]
The .csvs exist, but haven't been updated since the recent development began. The system is currently at devel status.
https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/turd.csv
https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/turd_con.csv

**Comment by rmihailucian** [comment]
Did yesterday the csvs locally, but didn't manage to do the datacheck. I hope to find some time today for it.

**Comment by michihdeu** [comment]
@si404 sorry, I forgot that csv exist but bringing all routes to devel should be the step before putting the system to preview

**Pull request merged**
