### PR TITLE
roudn overhaul

### PR DESCRIPTION
**Pull request by rmihailucian**
DN1

### CODE REVIEW

**Comment by michihdeu** [comment]
@rmihailucian 

Why have you renamed DJ100 to Dj100 in dn001.wpt?
DJ107R in dn001.wpt is a [waypoint in use](http://travelmapping.net/logs/pointsinuse.log) and must be kept as alt label!

I've not checked all changes. Please make sure that no user list files will be broken by your changes!

**Comment by michihdeu** [comment]
@jteresco please don't merge in before @rmihailucian has revised his changes. Thanks.

**Comment by michihdeu** [comment]
You also missed:
- DN1 BulDac_W
- E60 BulDac_W
- E60 DN1A_W
- E60 DN73A

If you have rerouted anything (I think you have) you need to notify it in updates.csv

**Comment by michihdeu** [comment]
You could do it like Si does. He usually keeps **all** renamed labels as alt labels and removes them later.

You could check `unusedaltlabels.log` on your noreaster space after running data check. Then, you could remove the unused alt labels before opening the pull request.

**Comment by jteresco** [comment]
OK, so holding off on this one.

**Comment by rmihailucian** [comment]
Now it should be ok. I didn't changed the route, just repositioned, added or renamed WPs.

**Comment by michihdeu** [comment]
dn001.wpt: `DN7H +http://www.openstreetmap.org/?lat=45.788475&lon=24.077911` "+" is odd

**Comment by rmihailucian** [comment]
DN1T has been rededicated as DN7H, according to the official list of the national highways of Romania. 
http://dpiis.gov.ro/new_dpiis/wp-content/uploads/2014/06/47.-ANEXA-1-540.pdf

**Comment by michihdeu** [comment]
sure but the "+" is not necessary (**+**http....)

**Comment by rmihailucian** [comment]
Corrected, I guess I wanted to put an alt Label but then saw nobody needs it...

**Comment by michihdeu** [comment]
I work with Github Desktop and usually check all changed files (red/green) - minimum the "critial changes" before sync and pull request, and once again after being published here (I think the online comparsion is a little bit better).

**Comment by rmihailucian** [comment]
Sure, but it's quite easy to miss something, if there are a lot of changes. For Romania, I would like to work 1-2-3 Routes/day, then look for NMPs/errors, then do another few Routes and so on. Where I should be more sensitive about are the alt Labels, a missed one gives no error, and you cannot detect it afterwards, unless someone cries out loud.

**Comment by michihdeu** [comment]
> a missed one gives no error, and you cannot detect it afterwards

You can. Run data check and diff pointsinuse.log before/after.
Or keep all as alt labels and remove them after data check or after the next site update.

It's software - and it's possible 😃

**Pull request merged**
