### PR TITLE
Beach Drive deletion

### PR DESCRIPTION
**Pull request by Duke87ofST**

### CODE REVIEW

**Comment by jteresco** [comment]
Holding off just a bit as it seems there is some ongoing debate on the forum.

**Comment by Duke87ofST** [comment]
Added DC section south of Broad Branch Rd back per forum discussion

**Comment by Markkos1992** [comment]
Just wanted to note the following typos in the updates entries:

2022-11-10;(USA) District of Columbia;Beach Drive;;Truncated from DC/MD line to Broad Branch Road as road north of this point has been **permanently** closed to motorized traffic.

2022-11-10;(USA) Maryland;Beach Drive;;Deleted route, no longer meets inclusion criteria due to permanent closure to motorized **traffic** south of DC/MD line.

**Comment by Duke87ofST** [comment]
> 

Oh so I can use my motorized traiffc to clinch it after all? Score!

<_< >_>

Fixed

**Pull request merged**
