### PR TITLE
Quinlan Bypass, Victoria AccRd

### PR DESCRIPTION
**Pull request by yakra**
https://www.heraldbanner.com/news/highway-276-bypass-project-finally-opening-to-traffic/article_6a2904de-b3aa-11ed-9306-973aec87ef33.html
https://www.heraldbanner.com/news/local_news/highway-276-bypass-opens-jpg/image_bca4dfee-b3aa-11ed-afa9-83722950959e.html

### CODE REVIEW

**Comment by yakra** [comment]
Oops. That 2nd link is just for the image used in the first, apparently.
[The change will not happen until Monday.](https://www.facebook.com/cityofquinlan/posts/pfbid02AuDxGBfxubQbfQsYrWqucFHFUdxreRSzJYmZVXwx4YHZqyPtvwbd92gqa2zqismpl?__cft__[0]=AZVZKTQgIqthhPdtceCqx7pM9CBa-yQzEyYUbV5f93SPvwMYk_cRZJQ6LYr3JnCVbOUje9G7cxDvOXS_b_HETIjm9xvwR0vXatbNcFlJjsKAFpcGX6m-z_XgnwrOZC76YeNJovwMO5mSITBkcssIzgM9z1Y_fQ8OEfBhR3qj_l6Bg2XshIErx_qFY64jxr-eduhhfUE9n2_quMoXVihFjdCg5oKJ0MDgXU3ur2t8C3ezbZdStjzqx72E6o5HXnMrfnY)

**Comment by yakra** [comment]
Ping @Duke87ofST @mrpoodlepants

**Comment by Duke87ofST** [comment]
276Bus is missing a point for Spur 264

**Comment by yakra** [comment]
Thanks. Staged for commit.

**Pull request merged**
