### PR TITLE
Ohio

### PR DESCRIPTION
**Pull request by mapcat**
[oh072.wpt](https://github.com/TravelMapping/HighwayData/files/83963/oh072.wpt)
[oh002.wpt](https://github.com/TravelMapping/HighwayData/files/83964/oh002.wpt)
[oh011.wpt](https://github.com/TravelMapping/HighwayData/files/83965/oh011.wpt)
[oh041.wpt](https://github.com/TravelMapping/HighwayData/files/83966/oh041.wpt)
[oh117.wpt](https://github.com/TravelMapping/HighwayData/files/83967/oh117.wpt)
[oh143.wpt](https://github.com/TravelMapping/HighwayData/files/83968/oh143.wpt)
[oh183.wpt](https://github.com/TravelMapping/HighwayData/files/83969/oh183.wpt)
[oh237.wpt](https://github.com/TravelMapping/HighwayData/files/83970/oh237.wpt)
[oh366.wpt](https://github.com/TravelMapping/HighwayData/files/83971/oh366.wpt)
[us050trkcin.wpt](https://github.com/TravelMapping/HighwayData/files/83972/us050trkcin.wpt)
[us052.wpt](https://github.com/TravelMapping/HighwayData/files/83974/us052.wpt)
[us068.wpt](https://github.com/TravelMapping/HighwayData/files/83973/us068.wpt)

### CODE REVIEW

**Comment by jteresco** [comment]
I'm going to hold off on this, as I think more files are intended to be included.

**Comment by yakra** [comment]
Hm. Again, it's a single-file pull request.
(Notwithstanding merging in the OH72 pull request from from mapcat/mapcat-patch-1 -- GitHub's info says only 1 file is changed.)
It looks like the others are just attachments, to the... pull request comment? I'm not sure how that's done...

**Comment by yakra** [comment]
I'll send a PM on AARoads to try to continue to figure things out & get branches, the submission & pull request process down, etc.

**Comment by mapcat** [comment]
Ignore this one. It did not work the way I thought it might. I'll go back to reading documentation.

**Pull request closed without merging**
