### PR TITLE
whole boatload of Colorado updates (per forum and per personal field-checks)

### PR DESCRIPTION
**Pull request by the-spui-ninja**

### CODE REVIEW

**Comment by the-spui-ninja** [comment]
let me know if there are any issues

**Comment by Markkos1992** [comment]
Is CR90_W a correct label for the west end of CO90Mon?

**Comment by the-spui-ninja** [comment]
Yeah, the sign at the end of the route says “End State Highway 90, begin County Road 90”

**Comment by yakra** [comment]
So CR90 begins there, rather than continuing?

**Comment by the-spui-ninja** [comment]
oh yeah fair point; should have that taken care of now

**Pull request merged**
