### PR TITLE
usatn -> active

### PR DESCRIPTION
**Pull request by mapcat**

### CODE REVIEW

**Comment by jteresco** [comment]
Just verifying - ok to activate before the relabeling TNs -> TN relabeling? @yakra @mapcat

**Comment by yakra** [comment]
> Just verifying - ok to activate before the relabeling TNs -> TN relabeling? @yakra @mapcat

http://tm.teresco.org/forum/index.php?topic=106.msg7540#msg7540

[HighwayData-master.zip](https://github.com/TravelMapping/HighwayData/archive/master.zip) downloaded 2017-08-22 17:32:28.
[pointsinuse.log](http://tm.teresco.org/logs/pointsinuse.log) downloaded 2017-08-22 11:33:36.

@mapcat, take a gander...
• [Files are here.](https://github.com/yakra/HighwayData/tree/TNsRelabel/hwy_data/TN)
• [Comparison & DIFFs vs. master.](https://github.com/yakra/HighwayData/compare/TNsRelabel)
• [ChangeLog](https://github.com/yakra/HighwayData/blob/TNsRelabel2/hwy_data/TN/label_changelog.csv) of TNs points detected, and their fates.
  *(Nota bene: This file is contained in a different branch from that in the first two links. That way, you can pull the TNsRelabel branch into master, or your own branch, without dragging label_changelog.csv along.)*

Of particular note:
>System;Route;Point;Fate
usaus;tn.us011e.wpt;TNs66;NeedsManualCheck
usaus;tn.us070.wpt;TNs155;NeedsManualCheck
usaus;tn.us070s.wpt;TNs155;NeedsManualCheck
usaus;tn.us321.wpt;TNs67_W;NeedsManualCheck
usausb;tn.us041altnas.wpt;TNs155;NeedsManualCheck

Meaning US11E already has a TN66, US70 already has a TN155 (AltLabel in this case), etc.

**Comment by jteresco** [comment]
I'll hold off pulling this one in until that's all resolved unless I hear otherwise.

**Comment by yakra** [comment]
OK. I know I've made some edits to *usansf* files in situ in my branch.
I haven't looked too closely at mapcat's branch, but I presume these files have been moved to *usatn*, so we probably can't merge in automatically. Nonetheless, the files are all online for inspection.

**Comment by mapcat** [comment]
Well I was assuming that the TNs->TN adjustments would only affect files that were already active (usaus, usausb, usansf). I did not touch the usansf files since I thought @yakra might be working on them. This can certainly wait until @yakra is finished.

**Comment by yakra** [comment]
In addition to usaus, usausb, and usasf, changes were also made to 3 usaif and 2 usatn routes.
In the latter case, I don't believe you had any pending edits to the files, and merge conflicts should not be a problem.
Give the DIFFs & changes a look over and make sure everything checks out.

**Comment by mapcat** [comment]
@yakra re: NeedsManualCheck
 
I will create new labels for these files. Do you think any more need checking besides those 5?

**Comment by yakra** [comment]
> I will create new labels for these files. Do you think any more need checking besides those 5?

I don't think there should be any others. This check was designed to detect any potential label collisions that would result from automatic relabeling/demoting (even for AltLabels on the same point, E.G. **TNs42 +TN42 http://YaddaYadda...*), and not make those changes. It appears to have worked in this regard.

Hmm... now seeing all the new commits come in, I'm a bit nervous about merge conflicts with my edits. Should probably be OK, as we're editing different parts of the files. Those [terminal CRLFs](http://tm.teresco.org/forum/index.php?topic=106.msg7537#msg7537) make me nervous, though. If we both edit *those* files...

**Comment by yakra** [comment]
> Those [terminal CRLFs](http://tm.teresco.org/forum/index.php?topic=106.msg7537#msg7537) make me nervous, though. If we both edit *those* files...

Should be OK. There's no overlap between the files that had the terminal CRLF missing, and those flagged as *NeedsManualCheck*

**Comment by mapcat** [comment]
I'm editing your version of the files, in case that matters...

**Comment by yakra** [comment]
Hm. Copying the ones in my branch, and pasting into the web editor in yours, I presume?
I don't see a commit notification here saying you merged my branch into yours.
This could mean merge conflicts, then, but still, no big deal.
Jim could just work some commandline magic and use your commits instead of mine for these 5 files.

**Comment by mapcat** [comment]
No, I just copy-pasted the file from your branch into the editor, made the changes, and saved in my fork.

I've changed/demoted the problematic points...want to do a quick check?

**Comment by yakra** [comment]
Doing now :)

**Comment by mapcat** [comment]
I'll check on your progress tomorrow. Thanks for streamlining the process @yakra

**Comment by yakra** [comment]
The new labels look good.

@mapcat & @jteresco, here's what I'm thinking...
1.) Go ahead and merge this branch in.
2.) I follow up with a pull request from my *TNsRelabel* branch, anticipating some merge conflicts, noting which of my files Jim should ignore in favor of mapcat's commits.
3.) mapcat takes care of moving the last *usansf* routes into *usatn*

Shall we go ahead and merge this in; is it ready?

**Comment by yakra** [comment]
D'AH! Moments too late! :)

**Comment by yakra** [comment]
OK, this is weird. I happened across a glitch in my code after this was all done...

The following code *shouldn't* have worked...
> void demote(char *NewPriLbl)
{	char **NewLblArray = new char*[NumLabels+1];
	NewLblArray[0] = NewPriLbl;
	for (unsigned short index=0; index < NumLabels; index++)
		NewLblArray[i+1] = label[index];
	label = NewLblArray;
	NumLabels++;
	char *FirstAlt = new char[strlen(label[1])];
	strcpy(FirstAlt, "+");
	strcat(FirstAlt, label[1]);
	delete label[1];
	label[1] = FirstAlt;
}

(I'd think I'd have wanted to do this instead:)
> void demote(char *NewPriLbl)
{	char **NewLblArray = new char*[NumLabels+1];
	NewLblArray[0] = NewPriLbl;
	for (unsigned short index=0; index < NumLabels; index++)
		NewLblArray[i+1] = label[index];
	label = NewLblArray;
	NumLabels++;
	char *FirstAlt = new char[strlen(label[1])**_+1_**];
	strcpy(FirstAlt, "+");
	strcat(FirstAlt, label[1]);
	delete label[1];
	label[1] = FirstAlt;
}

...but it did work. *(Was I just smashing the stack without realizing it, with no ill effects?)*
From what I saw of the diffs, I saw no glitches at the end of the demoted labels (former primary labels, now the first AltLabels).

But let's keep our eyes peeled, eh?
If bad comes to worse and we *do* find glitches, I can just fix my code and rerun the program.
*(And the advantage to that would be, no need to worry about merge conflicts. :D)*

**Comment by jteresco** [comment]
I'll merge this in before the next update, which I hope will happen tomorrow, unless you guys want me to wait.  Today's was run remotely from my spot in the passenger seat while on the Indiana Toll Road.

**Comment by yakra** [comment]
I just gave the DIFFs a closer look over, and all the demoted labels look fine, despite the foregoing.
Thankfully, the way GitHub highlights the DIFFs made this an easy task.

**Comment by yakra** [comment]
@jteresco, I no longer see any reason to wait.
Let's see what @mapcat has to say.

**Comment by yakra** [comment]
Merging in #1552 introduced a conflict, which I used the web-based "resolve conflict" too, well, resolve. That was easy enough, though I left the entries out of order by their listed dates. Oh well. That's easy enough to fix with a future commit.
```<<<<<<< master
2017-08-22;(USA) Tennessee;usatn;Tennessee State Highways;active
=======
2017-08-23;(USA) Florida;usafl;Florida State Highways;preview
>>>>>>> master
```
I'm going to create another yakra/TNsRelabel branch, open a pull request, and see what I can do for resolving conflicts there.

**Comment by mapcat** [comment]
Seems that this is in good shape, then? I have no objections to merging.

**Comment by yakra** [comment]
https://github.com/TravelMapping/HighwayData/pull/1552/#issuecomment-324201626

@mapcat & @jteresco, conflicts appearing to be resolved, here's my updated plan of attack:
1.) @mapcat merges in https://github.com/mapcat/HighwayData/pull/54/
2.) One of us merges this in.
3.) mapcat takes care of moving the last usansf routes into usatn.

@mapcat, are you OK with my pull request to merge my edits into mapcat:master?

**Comment by yakra** [comment]
w0ot!
Shall I go ahead and merge this in?

**Comment by yakra** [comment]
Yeah, why not include that in this pull too.

**Comment by mapcat** [comment]
OK, should take about 15 min as I'm currently multitasking :)

**Comment by yakra** [comment]
oh, and systemupdates.csv has usafl & usatn entries out of order. usatn could be changed to 2017-08-23, I suppose.

**Comment by mapcat** [comment]
I think that's everything, so merge as soon as you're ready. Thanks!

**Comment by mapcat** [comment]
I'll check everything again tonight after the site update.

**Comment by jteresco** [comment]
Errors from usatn when I tried the site update.  I'm going to comment the system out until these can be resolved:

`ABORTING due to 12 errors:
1: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/TN/usatn/tn.tn111.wpt'
2: Route contains fewer than 2 points: tn.tn111 (0 total points)
3: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/TN/usatn/tn.tn153.wpt'
4: Route contains fewer than 2 points: tn.tn153 (0 total points)
5: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/TN/usatn/tn.tn155.wpt'
6: Route contains fewer than 2 points: tn.tn155 (0 total points)
7: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/TN/usatn/tn.tn385.wpt'
8: Route contains fewer than 2 points: tn.tn385 (0 total points)
9: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/TN/usatn/tn.tn386.wpt'
10: Route contains fewer than 2 points: tn.tn386 (0 total points)
11: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/TN/usatn/tn.tn396.wpt'
12: Route contains fewer than 2 points: tn.tn396 (0 total points)
`

**Comment by mapcat** [comment]
Files have all been moved now. Please go ahead and resume the update.

**Comment by yakra** [comment]
Now how did I miss that? ):

**Pull request merged**
