### PR TITLE
Operation Texas

### PR DESCRIPTION
**Pull request by yakra**
15-09-08;(USA) Texas;I-30;tx.i030;Removed from a demolished freeway and relocated onto a new parallel freeway to the immediate southeast in Fort Worth, between points labeled *OldI-30_W and *OldI-30_E.
15-09-08;(USA) Texas I-69 (Houston);tx.i069;Extended southward from I-610 Exit 20A along US 59 to I-610 Exit 8A, and continuing over the Sugar Land section between I-610 Exit 8A and TX Spur 529.
15-09-08;(USA) Texas I-69 (Sugar Land);;Merged with I-69 (Houston).
15-09-08;(USA) Texas;I-69W;tx.i069w;Added route.
15-09-08;(USA) Texas;I-169;tx.i169;Added route.
15-09-08;(USA) Texas;I-35 BL (Round Rock);;Deleted route.
15-09-08;(USA) Texas I-35 Business Loop (Alvarado);tx.i035blalv;Moved waypoint US67Bus_N from a closed roadway (now labeled *OldUS67Bus) about 0.1 mi north of College Street to College Street. 
15-09-08;(USA) Texas US 190;tx.us190;Removed from US 190 Business and relocated onto the new southern bypass of Copperas Cove, between the western and eastern US 190 Business junctions.
15-09-08;(USA) Texas US 271;tx.us271;Removed from US 271 Business and TX 49, and relocated onto the new southwestern bypass of Mount Pleasant, between the southern US 271 Business junction and TX 49.
15-09-08;(USA) Texas US 377;tx.us377;Removed from a demolished freeway and relocated onto a new parallel freeway to the immediate southeast in Fort Worth, between points labeled *OldI-30_W and *OldI-30_E. Moved waypoint I-30(13) from Summit Avenue (now labeled I-30(13A)) to Chisholm Trail Parkway.
15-09-08;(USA) Texas US 67 Business (Alvarado);tx.us067busavr;Removed from a closed roadway in the northeast quadrant of the I-35 BL / College Street intersection, between points labeled *OldUS67Bus_S and *OldUS67Bus_N, and relocated onto I-35 BL and College Street.
15-09-08;(USA) Texas;US 190 Business (Copperas Cove);tx.us190buscop;Added route.
15-09-08;(USA) Texas;US 271 Business (Mount Pleasant);tx.us271busmtp;Extended southward from TX 49 to the US 271 Mount Pleasant bypass.
15-09-08;(USA) Texas;Chisholm Trail Parkway;tx.chitrlpkwy;Added route.
15-09-08;(USA) Texas;Fort Bend Parkway Toll Road;tx.fbptollrd;Added route.
15-09-08;(USA) Texas;Fort Bend Toll Road;tx.fbtollrd;Added route.

### CODE REVIEW

**Comment by jteresco** [comment]
Excellent.  Let's give this a day or so for a little looking over before I pull it in.

By the way, I think it's nice how you have separate commits for each route within your branch.  I am not sure we want to require that, but it does allow a specific commit message on each file, which will go into that file's history.

**Comment by yakra** [comment]
Agreed. With an update this large, it should get some review to make sure everything's tickety-boo before pushing it on it.

The separate commits are an outgrowth of the fact that I'm using the github.com web interface to edit the files, pasting in my changes. If doing so, why not give a rundown of changes for each file...
Require it? Nay -- Like the act of copy-pasting into 77 files on the web, it'd be a bit of a pain in the botty. If it's easier and more natural for collaborators to do larger batch commits, why not leave them to it.
It something I'm going to want to learn to do soon. Texas State Highways, Loops and Spurs will have over 700 files to upload between the three systems.

**Comment by si404** [comment]
I've viewed all the files with major changes in the .wpt editor, as well as looked at the text of all the files on Github in-browser. All seems fine.

**Comment by jteresco** [comment]
For something like an initial import of a large new system, I definitely would not to encourage, let alone require, individual commits.  But I do think if I was going to submit some NY changes that fix 3 issues, each of which touched 2 or 3 .wpt files, I think it would be nice to have a separate commit for each issue, even if they're combined into a single pull request.

Things to work out as the project matures...  What we're doing now, though, is working amazingly well.

**Comment by ovoss** [comment]
A few things for business routes in Alvarado:

tx.US67busavr: While we're messing with this route file, rename it 
tx.US67busalv, with old name kept as alternate name? (Mystery to me why the 
route file got its original name.)

Also, the relocated point I-35BL_S is in use for that file, but rather than 
relocate it, mention it in Updates, and make at least one user fix his 
broken list file, instead:
  -- rename the relocated point I-35BL
  -- make I-35BL_S an alternate label for *OldUS67Bus_S, to keep and hide 
the old point label

tx.I-35blalv: The relocated point is not in use (even though someone used 
the corresponding point in tx.US67busavr), so not necessary to have an 
Updates item?

I didn't see any similar situations in the other route file changes in this 
pull request.

--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages (NEW ADDRESS):
http://www.alaskaroads.com/home.html

**Comment by yakra** [comment]
Re US67BusAvr -> US67BusAlv:
There are a few other highways that have similar root/abbrev oddities (e.g. Whb for Whitesboro). I decided to just get the backlogged updates in and working, and then handle that with my next pull request.

**Comment by jteresco** [comment]
I'm going to bring this in, with the understanding that there might be some tweaks needed.

**Comment by yakra** [comment]
WRT Oscar's other points:

US67BusAvr I-35BL_S:
In my mind, breaking a .list file is what happens when a .list line is no longer parsed, and instead just produces an error.
I see having the correct label at the correct point, and having .list file lines map to a slightly different point, as being the lesser evil as opposed to having an inaccurate label at a given point in order to maintain 100% backward compatibility.
There have been other cases of an in-use waypoint label being relocated, with the old waypoint receiving a new label, listed in the old CHM hwyupdates.php.

I-35BLAlv US67Bus_N:
Ah! I thought for a moment that maybe the point was in use by someone on cmap.m-plex, but nope. Normally I'd not make an updates entry for such a case, but this one fell through the cracks. Ah well, no harm done.

**Pull request merged**
