### PR TITLE
Preston Western Distributor

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by michihdeu** [comment]
@si404 the A582 (Cottam) update link does not work. You missed the leading zero.

**Comment by si404** [comment]
Already fixed locally

**Comment by michihdeu** [comment]
@si404 I think you missed an update entry for A583 in this pull or in #6706, or you simply forgot checking labels in use.

I got a log error:
`Waypoint label A5072 not found in line: ENG A583 M55 A5072`

I figured out my updated list file entry:
`ENG A583 A5072_S M55`

Dunno if a) more users are affected nor b) you missed any other update entry too.

**Comment by si404** [comment]
I accidentally removed that label when cleaning up unused alt labels in #6707. Sorry.

**Pull request merged**
