### PR TITLE
start out naca (Central American routes)

### PR DESCRIPTION
**Pull request by neroute2**

### CODE REVIEW

**Comment by michihdeu** [comment]
@neroute2 sorry, but CAM is not a valid region name, see [regions.csv](https://github.com/TravelMapping/HighwayData/blob/master/regions.csv). This pull request cannot be merged in @jteresco

**Comment by jteresco** [comment]
More needed than changing the CAM to NA?

**Comment by neroute2** [comment]
Given that cism and cisa exist, camca (or caca?) should be an appropriate system name. So yes, I will change CAM to NA in systems.csv.

**Comment by michihdeu** [comment]
> More needed than changing the CAM to NA?

I've never drafted an international system. @si404 should know best how to deal with it.

**Comment by si404** [comment]
camca;NA;Rutas Centroamericanas;red;3;devel

this is fine, and fits the pattern of other systems.

**Comment by yakra** [comment]
While the system name doesn't *need* to start with a region code, I would still consider it best practice

**Comment by jteresco** [comment]
> While the system name doesn't _need_ to start with a region code, I would still consider it best practice

nacar for "Central America Routes" in the North America continent?

**Comment by neroute2** [comment]
> 
> 
> > While the system name doesn't _need_ to start with a region code, I would still consider it best practice
> 
> nacar for "Central America Routes" in the North America continent?

Most systems drop the 'r' for route. I'm not sure why na is better than ca, since the routes are only in Central America.

**Comment by michihdeu** [comment]
>  I'm not sure why na is better than ca, since the routes are only in Central America.

Because there is no Central America! https://github.com/TravelMapping/HighwayData/blob/master/continents.csv

And that's correct: https://en.wikipedia.org/wiki/Continent#Area_and_population
We also don't have Middle East and Far East but just Asia.

**Comment by neroute2** [comment]
Whatever. I don't feel like arguing so I'll change it to naca.

**Comment by michihdeu** [comment]
> Whatever. I don't feel like arguing so I'll change it to naca.

👍

**Pull request merged**
