### PR TITLE
Fix UK Tourist Routes

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by jteresco** [comment]
I don't have a strong opinion, but should the "valley" abbreviations be "val" instead of "vly" in both route names for .lists and file names for .wpts?

**Comment by jteresco** [comment]
So far just minor fixes needed.  Seeing if I can get the update through now.

**Comment by yakra** [comment]
I'd prefer Val over Vly. Just my 2c.

**Comment by si404** [comment]
OK, I'll get around to changing that some time soon.

**Comment by jteresco** [comment]
Thanks.  No rush as far as I'm concerned.

**Pull request merged**
