### PR TITLE
TX: US87 Big Spring bypass, and US59/69 N split reconfiguration in Lufkin

### PR DESCRIPTION
**Pull request by yakra**
2016-12-06;(USA) Texas;US 87;tx.us087;Removed from US 87 Business (Big Spring) and relocated onto William B. Crooker Memorial Highway and I-20
2016-12-06;(USA) Texas;US 87 Business (Big Spring);tx.us087busbig;Route added

### CODE REVIEW

**Comment by jteresco** [comment]
Am I correct that the first updates entry above should only have tx.us087, not both that and tx.us087busbig?

**Comment by yakra** [comment]
Correct. I've edited the comment to fix that.

Unrelated: I'll be adding 4 more commits to address an updated interchange complex in Lufkin.

**Comment by jteresco** [comment]
No rush - I won't be merging and pulling until tonight when I'm ready to run a site update (after 9 PM EST).

**Comment by yakra** [comment]
Ready to rock.

**Comment by yakra** [comment]
...or am I? What happened to my US69 commit?

**Comment by yakra** [comment]
OK, there it is! Ready to rock.

**Pull request merged**
