### PR TITLE
ENG + BIH

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by michihdeu** [comment]
@si404 @jteresco This pull removes a lot of updates.csv entries of the last days!

Croatia, France. Ohio, Romania,....

**Comment by jteresco** [comment]
Glad you notices, I won’t merge it in until this gets resolved.

**Comment by jteresco** [comment]
Looks like it’s already merged.  Not sure how best to proceed.

**Comment by jteresco** [comment]
It's not too many entries - I'll restore them manually with another commit before running the update for tonight.

**Comment by si404** [comment]
Sorry, I saw that I'd removed updates entries (bad sync) seconds after. I sought to make a commit reinstating these on the Travel Mapping/master branch so it was all fixed immediately, but it made the commit on my branch instead, even though I was on the TM/master branch...

**Pull request merged**
