### PR TITLE
this should be correct

### PR DESCRIPTION
**Pull request by neroute2**

### CODE REVIEW

**Comment by jteresco** [comment]
Still no good:

<pre>
ABORTING due to 4 errors:
1: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/MEX-NAY/mexf/mexnay.mex040.wpt'
2: Route contains fewer than 2 points: mexnay.mex040 (0 total points)
3: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/MEX-COAH/mexsf/mexcoah.blvdnazort.wpt'
4: Route contains fewer than 2 points: mexcoah.blvdnazort (0 total points)
</pre>

**Comment by jteresco** [comment]
Commenting out mexf and mexsf for tonight so I can get an update through.

**Comment by neroute2** [comment]
Oh well. Hopefully tomorrow it will work. Is there an easy way to test it in puTTY, given that I have it in a branch rather than my main master?

**Comment by jteresco** [comment]
I'll defer to the others for now who might run datacheck on changes in a branch.  @michihdeu?  @si404?

**Comment by michihdeu** [comment]
@neroute2 I don't use branches but [my master](https://github.com/michihdeu/HighwayData) only. I don't see any reason to use branches for managing my work. I use Github Desktop which makes dealing with hwy data more easily compared to the limited Github web interface.

I think that Si also works with master and yakra runs data check locally.

**Pull request merged**
