### PR TITLE
Merge UT007 and UT007 San

### PR DESCRIPTION
**Pull request by NickCPDX**
The two routes are now connected.

### CODE REVIEW

**Comment by NickCPDX** [comment]
Awesome, thank you!

**Comment by yakra** [comment]
WarValRd is in use and should be retailed as an AltLabel for exit 10.

**Comment by yakra** [comment]
WarValRd is in use and should be retained as an AltLabel for exit 10.

**Comment by NickCPDX** [comment]
Not sure how to do that?

**Comment by mapcat** [comment]
Add +WarValRd after the waypoint label (10).

**Comment by jteresco** [comment]
I'll add that also, since I have changes in progress here.

**Pull request merged**
