### PR TITLE
TX:  TXLp49 extension, odds, ends

### PR DESCRIPTION
**Pull request by yakra**

### CODE REVIEW

**Comment by yakra** [comment]
TXLp49 has been extended. Going to add that in.

**Comment by yakra** [comment]
Ready to go.

**Comment by rickmastfan67** [comment]
Um @yakra, you missed the interchange on Loop-49 with TX-110. Been open since at least Dec '18 per StreetView: https://goo.gl/maps/hs3JyMukwsjFg1Dm8

**Comment by yakra** [comment]
Whoops. Didn't look at the existing route at all. #2786

**Pull request merged**
