### PR TITLE
Update roudn.csv

### PR DESCRIPTION
**Pull request by rmihailucian**
Corrected some incorrect city names.

### CODE REVIEW

**Comment by jteresco** [comment]
@michihdeu do you agree on the changes here?

**Comment by michihdeu** [comment]
http://cmap.m-plex.com/tools/manual_syshwylist.php

> The City should be spelled as the locals spell it and using international characters as needed. 

We had the English version of București and a wrong spelling of Brăila (lucian's hometown).
We support unicode and I don't think that "ă" and "ș" need to be replaced. We do also use special characters for other countries, e.g. nor.

@rmihailucian Thanks for your change but please use correct Romanian spelling. Just make another commit to the same file.

**Comment by michihdeu** [comment]
@rmihailucian roudn**_con**.csv needs to be updated too.

**Comment by michihdeu** [comment]
@rmihailucian _con.csv file?

**Comment by rmihailucian** [comment]
Done also _con.csv file.

**Comment by michihdeu** [comment]
thanks, saw it just some seconds later.

I've run a data check and both csv files are fine - do not crash siteupdate.py

**Pull request merged**
