### PR TITLE
UnprocessedWPTs, batch 2

### PR DESCRIPTION
**Pull request by yakra**

### CODE REVIEW

**Comment by yakra** [comment]
I added a bunch of additional commits after initially opening the request. Done now; this should take care of everything I'm responsible for.

When I deleted the last file from AB/cansph, GitHub automatically removed the empty directory for me. Nice; I was wondering how I was going to do that.

I'm ready to have this merged in.

**Comment by yakra** [comment]
Remaining stuff:

* AB/cannf/ [6 files]
* NS/cannf/ns.bedbyp.wpt
Left in place as part of in-dev cannf system.

* TX/usanm/tx.nm028ant.wpt
Oscar? Jim?

* TX/usatx/ [2 files]
* TX/usatxl/ [2 files]
* TX/usatxs/tx.sp348.wpt
Left in place pending migration of usansf routes into their respective state systems upon activation

**Comment by jteresco** [comment]
Re: TX/usanm/tx.nm028ant.wpt

At least when I plotted them initially a few years back, NM 28 briefly crossed into Texas but remained designated NM 28.  Hence that one.

**Comment by ovoss** [comment]
tx.nm028ant.wpt appears to be the same as tx.nm028can.wpt, which is part of 
the USANM route set and included in its .csv files. tx.nm028ant.wpt is 
probably delete-worthy, but as a two-line file <1 KB, no harm in keeping it 
around.

Oscar

----- Original Message ----- 
From: Eric Bryant
.
TX/usanm/tx.nm028ant.wpt
Oscar? Jim?

--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages (NEW ADDRESS):
http://www.alaskaroads.com/home.html

**Comment by yakra** [comment]
If that's the only part of NM28 in TX, then it doesn't need an abbrev and probably shouldn't have one. JMO.

**Pull request merged**
