### PR TITLE
Redo Add I-5 truck route to usai

### PR DESCRIPTION
**Pull request by ovoss**
Adds I-5 truck route in Newhall CA to usai, per forum discussion.

Also updates SK 7 for new Vanscoy bypass.

Updates table items for above will be in separate pull request.

Also included are several usaca preview routes, updated in first phase of peer review.

### CODE REVIEW

**Comment by ovoss** [comment]
Datacheck successful. Problem is that not all file changes seem to have made it into the pull request, probably because of how my first attempt at a pull request (which failed datacheck) was closed.

Jim, what we might need to do is for me to email you all the changed files, to bypass my GitHub client and its apparent problem with assembling my pull request. Then after that is all merged in and a site update is done, re-synch my client with the master, and hope that sets things right at my end.

One alternative -- if my original pull request (Add I-5 truck route to usai) is still in the GitHub system, take that, manually fix the problem that appears to have caused its datacheck failure, and re-run that closed pull request. The offending line in usai_con.csv included an extra field:

usai;I-5;Trk;New;Newhall, CA;ca.i005trknew

The New; field should not have been there.

A third choice is if I could retrieve and reopen the closed pull request, fix usai_con.csv myself, and re-submit. I don't know how to do that without further screwing things up.

Oscar

**Comment by jteresco** [comment]
I am not sure how any of this got merged in, but I'll see what I can do to fix it on my end.

**Comment by yakra** [comment]
> I am not sure how any of this got merged in, but I'll see what I can do to fix it on my end.

51f5b1868a7154e114321ea3f83aae9788cce46d committed directly to travelmapping:master 10/11/2019 @ 9:38 AM.

What gets me about the commit in this PR is...
* there are a few relevant label changes to CA25, and the addition to usai_con.csv
* one whitespace character on the header line in usai.csv; ok whatever...
* The I-5Trk / CA14Trk coordinates changed a tiny bit.
* coords-wise, one other point changes by 0.000001.
* **A bunch of shaping point labels differ by 1.** *Even 6-digit ones that are obviously randomly generated by wptedit, such as `X456189` -> `X456188`.*

That is is just too damn weird. It almost looks more like a computer somehow going haywire than something @ovoss did intentionally...

**Comment by ovoss** [comment]
> On October 13, 2019 at 11:13 AM Eric Bryant <notifications@github.com> wrote:
> 
> 
>         > > 
> >         I am not sure how any of this got merged in, but I'll see what I can do to fix it on my end.
> > 
> >     > 
>     51f5b18 https://github.com/TravelMapping/HighwayData/commit/51f5b1868a7154e114321ea3f83aae9788cce46d committed directly to travelmapping:master 10/11/2019 @ 9:38 AM.
> 

It was my intention to create a pull request to make those changes, rather than commit directly to master. Once datacheck.sh picked up the usai_con.csv error (extra field in the new line for I-5trknew), I tried to close that pull request, so I could start over. I don't know how the initial pull request went directly to the master.

> 
>     What gets me about the commit in this PR is...
> 
>         * there are a few relevant label changes to CA25, and the addition to usai_con.csv
>         * one whitespace character on the header line in usai.csv; ok whatever...
>         * The I-5Trk / CA14Trk coordinates changed a tiny bit.
>         * coords-wise, one other point changes by 0.000001.
>         * A bunch of shaping point labels differ by 1. Even 6-digit ones that are obviously randomly generated by wptedit, such as X456189 -> X456188.
> 
>     That is is just too damn weird. It almost looks more like a computer somehow going haywire than something @ovoss https://github.com/ovoss did intentionally....
> 

The last four items were intentional. I was having trouble getting my GitHub client to recognize the changes in files other than CA25 and usai_con.csv. So I decided to make completely trivial and non-substantive changes to the other files, to make my GitHub client recognize them as changed files for a new pull request. Only the new request only picked up the trivial changes, and not the substantive ones that, it turned out, were already erroneously directly added to the master.


I hope Jim was able to pull in the (corrected) usai_con.csv changes, and leave the other files as they were in the master. It seemed the only change he made manually to the master was to correct usai_con.csv, and the other stuff was discarded. I know Jim didn't add the CA25 edits on October 11, and only added them (plus a label change in CA13) after I submitted a followup pull request on October 12.


What went right here was that I used datacheck.sh, which picked up the glitch in my first submission of the revised usai_con.csv file, so I could try to start over with a fixed csv file.

**Comment by yakra** [comment]
From what I'm able to see it looks like everything's okay.

**Pull request closed without merging**
