### PR TITLE
China regions

### PR DESCRIPTION
**Pull request by eeffaann**
Removed designated minority name from the autonomous region names in CHN regions.csv

NM,GX,XZ,NX, the 2nd "word" refers to the minority peoples that are the designated minority in these autonomous regions, and are not a part of the actual region name.

Fixed various spelling mistakes.

### CODE REVIEW

**Comment by michihdeu** [comment]
@jteresco I was just about to check this. I'm not sure that it should be merged

**Comment by michihdeu** [comment]
we go with ISO 3166-3 codes. I'm quite sure that @si404 made it right. Dunno if there was a recent change?

**Comment by jteresco** [comment]
Sorry @michihdeu, I already merged and ran a site update with the new names.  Fortunately, it should be pretty painless to revert if that's the decision.

**Comment by si404** [comment]
The minority names are in the official names (along with a description), plus I used the transliteration 'Nei Mongol' rather than the translation 'Inner Mongolia', but I did make a spelling mistake for Hebei, and these changes match the English names at https://en.wikipedia.org/wiki/ISO_3166-2:CN 

I say keep these changes per site standards for English names.

**Pull request merged**
