### PR TITLE
US 220 Recentering (I-80 to PA/NY) Part 2

### PR DESCRIPTION
**Pull request by Markkos1992**
Also Includes: I-86 (South Waverly, I-86 FUTURE (South Waverly), I-99 FUTURE (Lock Haven), NY 17 (South Waverly) (@yakra) , PA 42, PA 42 TRUCK (Eagles Mere), PA 49, PA 118, PA 199, PA 249, PA 287, PA 328, PA 349, PA 362, PA 414, PA 442, PA 477, PA 514, PA 549, and PA 660.

Other Changes:
I-99 FUTURE (Lock Haven): Added +X115, +X116, +X117, and +X118. Fixed OldHwy220 label to OldUS220.
US 6: Added Loucks Mills Rd (LouMilRd), Phoenix Rd (PhoRd), *OldPA287, Charleston St (ChaSt), Bullock Rd (BulRd), Schodac Rd (SchRd), Cole St, Strange Rd (StrRd), and Mud Creek Rd (MudCreRd). Replaced ChaSt with Dewey Ave (DewAve) and +X1D. Replaced GrayCemRd with Elk Run Rd. Replaced GulfRd with Leona Rd (LeoRd). Replaced +X3B with Madigan Rd (MadRd) and Sugar Creek Rd (SugCreRd). Replaced +X3CA with McEwen Rd (McERd).
US 11: Added Quarry Dr (QuaDr), Deussen Dr (DeuDr), and Valley Rd (ValRd_B).
US 15 BUS (Mansfield): Added Canoe Camp Creek Rd (CanCCRd), Decker St (DecSt), and Kellytown Rd (KelRd).
US 220: Lined up with PA 414 and PA 199. Added +X115, +X116, +X117, +X118, Spook Hollow Rd (SpoHolRd), Beaver Lake Rd (BeaLakeRd), Edkin Hill Rd (EdkHillRd), Michelle Rd (MicRd), +X200A, Snyder Rd (SnyRd), Karge Rd (KarRd), Old Bernice Rd (OldBerRd), +X106, Marsh Rd (MarRd), Heath Hill Rd (HeaHillRd), Burlington Turnpike (BurTpk), Franklin Rd (FraRd), Hemlock Run Rd (HemRun Rd), Mountain Rd, +X1101, +X1102, and +X1102A. Fixed OldHwy220 label to OldUS220. (http://forum.travelmapping.net/index.php?topic=3246.0) Replaced +X103 with Holmes Hollow Rd (HolHolRd). Replaced +X107 with Blacks Rd (BlaRd). Replaced +X108 with Kellogg Rd (KelRd). Fixed MilESmiRd label (http://forum.travelmapping.net/index.php?topic=3246.0).
PA 14: Added Liberty St (LibSt), Pleasant Stream Rd (PleStrRd), Mill Hill Rd, Spencer Rd (SpeRd), McMurray Rd (McMRd), Tennessee Gas Rd (TenGasRd), Mud Creek Rd (MudCreRd), Havens Rd (HavRd), and Roaring Run Rd (RoaRunRd). Replaced GreSt with Thompson St (ThoSt). Replaced +X02 with Roaring Branch Rd (RoaBraRd). Replaced +X04 with McNett Hill Rd (McNHillRd). Replaced +X7 with Snedekerville Rd (SneRd). Replaced ReeLn with +X7A.
PA 42: Realigned between OldPA42_A and OldPA42_C, including a new brief concurrency with PA 118. (http://forum.travelmapping.net/index.php?topic=3421.0) Added +X00, +X03A, Comarnitsky Ln (ComLn), Ringtown Mountain Rd (RinMouRd), Ridge Rd (RidRd), +X03B, Ebner Dr (EbnDr), Legion Rd (LegRd_B), Moreland Baptist Rd (MorBapRd), and Muncy St (MunSt). Replaced OldEagMRd with Edkin Hill Rd (EdkHillRd)(http://forum.travelmapping.net/index.php?topic=3246.0). Replaced LinLn with +X11A.
PA 42 TRUCK (Eagles Mere): Added Michelle Rd (MicRd), +X200A, and Nordmont Rd (NorRd).
PA 44: Added Ants Hill Rd, Katys Church Rd (KatChuRd), Howell Dr (HowDr), and +X4A.
PA 49: Added Dwight Creek Rd (DwiCreRd), Fork Rd, Austinburg Rd (AusRd), Rose Valley Rd (RoseValRd), Merrick Hill Rd (MerHillRd), +X3R, Bliss Rd (BliRd), Thornbottom Rd (ThoRd), Cummings Creek Rd (CumCreRd), and +X3RA. Replaced +X0 with Baker Creek Rd (BakCreRd). Replaced +X2 with Andrews Hill Rd (AndHillRd). Replaced +X2A with Potter Brook Rd (PotBroRd).
PA 118: Added PA 42 Concurrency (http://forum.travelmapping.net/index.php?topic=3421.0). Added +X1, Dairy Farm Rd (DaiFarmRd), Funston Rd (FunRd), Whitenight Rd (WhiRd), Keller Hollow Rd (KelHolRd), Camp Lavigne Rd (CampLavRd), Bethel Hill Rd (BetHillRd), Maransky Rd (MarRd), Harris Pond Rd (HarPondRd), Loyalville Rd (LoyRd), Old PA 115, and Outlet Rd (OutRd). Replaced +X1 with Clarkstown Rd (ClaRd). Replaced +X2 with Beaver Run Rd (BeaRunRd).
PA 184: Added *OldPA184.
PA 187: Fixed NewAlbRd Label to match US 6.
PA 199: Lined up with US 220. Added +X2, Pine St, and Lockhart St (LocSt). Replaced ThuRd with +X1.
PA 239: Added Andy's Hill Rd (AndHillRd), Bradley Rd (BraRd), and Old Tioga Turnpike (OldTioTpk). Replaced +X5 with Mordan Hollow Rd (MorHolRd).
PA 249: Added Locey Creek Rd (LocCreRd), Glenn Rd (GleRd), Merrick Hill Rd (MerHillRd), Short Hill Rd (ShoHillRd), Rose Valley Rd (RoseValRd), and Austinburg Rd (AusRd).
PA 254: Added Spruce Run Rd (SprRunRd) and +X0.
PA 287: Realigned between *OldPA287_A and OldPA287_B (due to realignment of US6_W intersection). Added Canoe Run Rd (CanRunRd), Dam Run Rd, *OldPA184, Frenchtown Rd (FreRd), Hughes Rd (HugRd), Lick Run Rd, Oregon Hill Rd (OreHillRd), Dixie Run Rd (DixRunRd), Nauvoo Rd (NauRd), Hurley Hill Rd (HurHillRd), Rattler Rd (RatRd), +X6A, Sand Run Rd, Sweetbriar Rd (SweRd), Shumway Hill Spur Rd (SHSpurRd), +X1L, Charleston St (ChaSt), Catlin Hollow Rd (CatHolRd), Hills Creek Rd (HilCreRd), +X7A, Ives Run Ln, +X2L, +X1R, +X2R, and Lawrence Rd (LawRd). Replaced BraRd with Mitchell Creek Rd (MitCreRd). Fixed LPCreRd and BearCreRd labels (http://forum.travelmapping.net/index.php?topic=3246.0).
PA 328: Added White Rd (WhiRd), Jackson Center Rd (JacCenRd), and North Rd (NorRd).
PA 349: Added Scott Rd (ScoRd), +X1, and Boulio Rd (BouRd).
PA 362: Added Forest Rd (ForRd)(access to trail) and Airport Rd (AirRd).
PA 414: Fixed NMP at US 220. Added Sinking Springs Rd (SinSprRd), Truman Run Rd (TruRunRd), Rim Rd, +X7A, Dixie Run Rd (DixRunRd), Plank Rd (PlaRd), +X7B, Nauvoo Rd (NauRd), Old US 15, Old Mill Rd, Farm Rd, Union Rd (UniRd), Canton Rd (CanRd), Windfall Rd (WinRd), Baileys Corner Rd (BaiCorRd), +X7C, Sharcana Rd (ShaRd), Canton Ave (CanAve), and Burlington Turnpike (BurTpk). Replaced +X8 and WLerRd with Jennings Rd (JenRd) and Vanfleet Rd (VanRd). Replaced +X9 with Brocktown Rd (BroRd).
PA 442: Added Fogeltown Rd (FogRd), Maple Ln (MapLn), Clarkstown Rd (ClaRd), Wallis Rd (WalRd), Moreland Township Rd (MorTowRd), Bill Sones Rd (BillSonRd), and Funston Rd (FunRd). Replaced +X0 with Deer Rd. Replaced MapRidRd with Pine Summit Rd (PineSumRd). Replaced +X1 with Shingle Run Rd (ShiRunRd).
PA 477: Added Brungard Rd (BruRd) and Davy Rd.
PA 487: Added McIntyre Rd (McIRd), Camp Lavigne Rd (CampLavRd), Main St, Schlock Rd (SchRd), Connells Dam Rd (ConDamRd_N), and Horseshoe Rd (HorRd). Fixed SR1002_S and SR1002_N labels (http://forum.travelmapping.net/index.php?topic=3246.0).
PA 514: Replaced +X1 with Cowley Rd (CowRd).
PA 549: Added Newtown Hill Rd (NewHillRd), +X1, Elk Run Rd, Dunkelberger Rd (DunRd), Pumpkin Hill Rd (PumHillRd), +X2, +X2A, and Eighmey Rd (EigRd). Replaced +X1 with Ashley Hill Rd (AshHillRd). Replaced +X2 with Bailey Creek Rd (BaiCreRd). Replaced WoodRd with Hickory Rd (HicRd). Replaced +X3 with Coryland Rd (CorRd).
PA 660: Added Snyder Point Rd (SnyPoiRd_W), Hazelton Rd (HazRd), Morral Rd (MorRd), Kelsey St (KelSt), Bullock Rd (BulRd), and Mack Rd. Replaced +X1 with Spencer Rd (SpeRd). Fixed SFSchRd label (http://forum.travelmapping.net/index.php?topic=3246.0).

### CODE REVIEW

**Comment by yakra** [comment]
> Also Includes: I-86 (South Waverly, I-86 FUTURE (South Waverly), I-99 FUTURE (Lock Haven), NY 17 (South Waverly) (@yakra)

I don't see any changes to the NY section of these routes, just the nmpfps.log entries. If this what you meant to indicate?

Re PA US220: Now that I-86 proper intersects here, it may be time to change `NY17` to `I-86` or `I-86/17`.

If making the amount of changes to routes in NY that I've seen recently, it may be better to coordinate beforehand in the forum.

**Comment by Markkos1992** [comment]
It is just border points for the most part as I had done for many PA routes.  

Anyway I knew that the US 220/NY 17/I-86 area could get confusing as US 220 and PA 199 are truly my routes. I did not touch the NY 17/NY 34 point either, but I did slightly relocate the NY 34/PA 199 border point.

**Comment by yakra** [comment]
> I also want to note that the NY17 points on **NY 427** and **NY 13** should be changed also. I am unsure if you could find any other relevant ones.

I did some grep-fu, and only found those two.

> Also I recommend that you relook at Horseheads while you are at it as I am unsure what NY 13 is actually doing. (NY 14 is not much better as it looks like it may be missing a graph connection with I-86/NY 17 to start.)

Hm. I see both OSM & ESRI have NY13 marked on the frontage road. Looks dubious. No signage; shapefiles, TDV and TDR don't support it. Leaving as-is, apart from the label change.

**Comment by Markkos1992** [comment]
Agreed.  Minus the signage on the [frontage road here](https://www.google.com/maps/@42.1556087,-76.8142865,3a,75y,306.45h,82.32t/data=!3m6!1e1!3m4!1s1jFl8SgFTmVUNRNQL1O0Ew!2e0!7i13312!8i6656) there is just not enough evidence to extend it.

**Pull request merged**
