### PR TITLE
More NM deletions, northern NV cleanup

### PR DESCRIPTION
**Pull request by ovoss**
Deletes unsigned/decommissioned NM 355 and NM 461.

Also rest of NMP cleanup along I-80 corridor in Nevada.

Updates entries for NM deletions to be in separate pull request, once this one clears Datacheck.

### CODE REVIEW

**Comment by ovoss** [comment]
I forgot to add revised csv files to reflect the two NM route deletions. How can I add them to this PR, without screwing things up? I tried to copy and paste the files into the PR, didn't work.

**Comment by Markkos1992** [comment]
@ovoss, just edit the branch you put these changes in and they should show up here.

**Comment by ovoss** [comment]
> @ovoss, just edit the branch you put these changes in and they should show up here.

So how do I do that? I tried and failed to add the files to this PR.

I use a GitHub desktop client. Changes made to my local copy of the HighwayData repository don't show up in GitHub, unless included in a pull request.

**Comment by Markkos1992** [comment]
Oh, I did not know that.  Usually I just make further edits in my branch if the pull request has not been put in yet.

You could always add another one I guess.

**Comment by ovoss** [comment]
> You could always add another one I guess.

I could make a second pull request, just for the csv files. But I don't know if I can run Datacheck for two pull requests at once. And if I ran Datacheck just on my first pull request, I expect it would fail, since it deletes two route files referenced in the csv files in the GitHub master.

Close, revert, and retry is another option. But I think I tried that on another occasion, and made a mess of things.

I have a dentist appointment at 2:30 ET, but can get back to this afterwards to try a fix, well before Jim would usually do this evening's site update.

**Comment by michihdeu** [comment]
> I could make a second pull request, just for the csv files. But I don't know if I can run Datacheck for two pull requests at once.

You run data check for your branch and your commits are in your branch. The pull request(s) are just to sync your branch with the master branch.

**Comment by ovoss** [comment]
> > I could make a second pull request, just for the csv files. But I don't know if I can run Datacheck for two pull requests at once.
> 
> You run data check for your branch and your commits are in your branch. The pull request(s) are just to sync your branch with the master branch.

But if I tried to pull in new files with my GitHub desktop client, I think it would create a new branch for the new files.

**Comment by michihdeu** [comment]
> But if I tried to pull in new files with my GitHub desktop client, I think it would create a new branch for the new files.

I also use the desktop client and always have ONE branch but I know that the way you do it, you have several branches. If it really happens with the pull request (odd!), you are right....

**Comment by michihdeu** [comment]
There is a note: "Add more commits by pushing to the More-NM-deletions,-northern-NV-cleanup" branch on TravelMapping/HighwayData.

And, when I just press the "commit to master" button and "sync", I always add the commits to the very same pull request as long as it is not yet merged in to master - and it is not!

**Comment by michihdeu** [comment]
https://github.com/TravelMapping/HighwayData/pull/4855 had two commits. It should work.....

**Comment by ovoss** [comment]
I tried to upload three missing files (including both usanm csv files) to the branch. They seem to be in the branch, somewhere. But datacheck.sh FAILED, reports two errors, as if it didn't recognize the two csv files that removed nm.nm355.wpt and nm.nm461.wpt from the HB:

[355.1] ABORTING due to 2 errors:
1: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/NM/usanm/nm.nm355.wpt'
2: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/NM/usanm/nm.nm461.wpt'

I don't know what to do next, but we can't pull this PR into the master as is.

**Comment by jteresco** [comment]
Sorry, I just pulled everything in without looking at the discussion here.  The site update failed (as I would have known had I read this).

**Comment by michihdeu** [comment]
@ovoss what's the purpose of usanm.csv + usanm_con.csv in the root directory?

https://github.com/TravelMapping/HighwayData

Move or delete?

**Comment by ovoss** [comment]
I just deleted the files. They were remnants of an unsuccessful attempt to fix my broken pull request. Jim fixed the problem another way.

**Pull request merged**
