### PR TITLE
usafl: FL-9B new extention to CR2209

### PR DESCRIPTION
**Pull request by rickmastfan67**
https://www.news4jax.com/traffic/northbound-lanes-of-state-road-9b-open-in-st-johns-county?__vfz=medium%3Dsharebar

Not sure if the I-95 will now gain an exit number, but I'll cross that bridge once somebody checks out the new alignment.

### CODE REVIEW

**Comment by rickmastfan67** [comment]
Also, not sure if this part will become I-795 in the future, so, not extending that file.  But I have a feeling that I-795 will just be the I-95 -> I-295 segment.

**Comment by rickmastfan67** [comment]
NM, just found a video that somebody took back on 05/21/17 that clearly shows an exit number for I-95 painted on the ground (no gore signage yet).  It's Exit 4.  https://youtu.be/qVplSYgmnRs?t=2m13s

I'm sure that FDOT updated the signage since then and posted it for all to see, so I'll edit both FL-9B's & I-795 (Future)'s files to have I-95 listed as '4'.

**Comment by jteresco** [comment]
Should 9B now be just "FL9B" instead of "FL9BJac"?

**Comment by jteresco** [comment]
It doesn't look like we're consistent elsewhere.  The first two I looked at were NY and MA, both of which I initially developed but relinquished a few years back.  usany doesn't include a city or suffix for any except NY120A (which has 4 segments) while usama includes them for every route with a letter suffix.

**Comment by rickmastfan67** [comment]
Well, as I said above, I can make FL consistent (I know I did a few without the name without realizing it) in a separate changeset later since usafl is still in 'preview' and would not have to push an 'update' log entry for the changelog file.

**Pull request merged**
