### PR TITLE
Texas activation

### PR DESCRIPTION
**Pull request by yakra**

### CODE REVIEW

**Comment by yakra** [comment]
@si404 merged 33 commits into TravelMapping:master from yakra:Texas 12 days ago.
Yet, when I look at [my TX branch of the repo](https://github.com/yakra/HighwayData/tree/Texas), I see that "This branch is 33 commits ahead, 158 commits behind TravelMapping:master."

[Clicking on Compare](https://github.com/TravelMapping/HighwayData/compare/master...yakra:Texas) starts me on the process of creating a pull request (of the "Can’t automatically merge" variety -- probably because of f7f7852), consisting of the same 33 commits that Si already merged.

Not a Big Deal (I'm OK with deleting this branch and creating a new one), but... any ideas what's going on?

**Comment by yakra** [comment]
@si404, was this a squash-and-commit merge?

**Comment by si404** [comment]
Yes. Seems this new feature isn't great if you want to keep the branch open as it confuses Github.

Seems fine for merging branches where the branch is for a set of related commits that don't need to be different ones (eg every individual file change as one commit, as the web editor makes) that then can be merged as one commit, rather than (say) 33, and then deleted (which I thought this one is).

**Comment by yakra** [comment]
Aah yes. I had a feeling it was a Squash thing. Makes sense now. "The *n* commits from this branch will be combined into one commit in the base branch." So it's a new, squashed, commit that gets merged, rather than my original commits. So GitHub thinks they're unmerged (as they ARE unmerged, I guess), hence the wacky hijinks in my previous comment. Yeah. OK, I get it.

**Pull request merged**
