### PR TITLE
removing non-existent business loop

### PR DESCRIPTION
**Pull request by the-spui-ninja**

### CODE REVIEW

**Comment by Markkos1992** [comment]
The route still needs to be deleted from the usaib files.  I am pretty sure that this will not pass datacheck at the moment.

**Comment by michihdeu** [comment]
yep, this will not work! @the-spui-ninja @jteresco

**Comment by ovoss** [comment]
> The route still needs to be deleted from the usaib files. I am pretty sure that this will not pass datacheck at the moment.

And also from both usaib .csv files, if not done already.

**Comment by Markkos1992** [comment]
I was implying the usaib csv files.  I apologize if I was not clear on that.

**Comment by jteresco** [comment]
I'll remove it from the `.csv` files when I run tonight's update.

**Comment by the-spui-ninja** [comment]
I got it, sorry I missed the first email been running around the hospital for my kid all afternoon

**Pull request merged**
