### PR TITLE
in-dev usaky4 & other bits

### PR DESCRIPTION
**Pull request by yakra**
adds in-dev usaky4
fixes for the changes I made on @rickmastfan67's turf in #364

### CODE REVIEW

**Comment by jteresco** [comment]
Need TN/usaky3/tn.ky1076.wpt to be able to complete a site update with this merged in.

Let me know if I should just comment out that entry for now.

**Comment by mapcat** [comment]
I'm going to be looking over the existing usaky4 and intend to add the rest of the highways up to 1999. If anyone has drafted files for any of the highways not included in this update, it would be good to know in order to avoid any duplication.

**Comment by yakra** [comment]
Jim, I filed it under Kentucky by accident:
hwy_data/KY/usaky3/tn.ky1076.wpt

**Comment by jteresco** [comment]
Thanks, I'll move it.

**Pull request merged**
