### PR TITLE
TX peer review

### PR DESCRIPTION
**Pull request by yakra**

### CODE REVIEW

**Comment by yakra** [comment]
Discussion:
http://www.aaroads.com/forum/index.php?topic=16776.0
http://www.aaroads.com/forum/index.php?topic=16777.0
http://www.aaroads.com/forum/index.php?topic=16778.0

**Comment by jteresco** [comment]
@yakra Please grab a copy from here for your local files before the next update to this file - looks like yours is missing a semicolon on each line, thanks.

**Comment by yakra** [comment]
Whoops. Got it.

**Comment by jteresco** [comment]
No harm done - just had to run a quick fix, but might as well not have to do it every time, thanks.

**Comment by yakra** [comment]
Just checked my local copies of usatxl.csv & usatxs.csv -- not only were they missing the semicolons, but I'd not made the other changes in this pull request either. Fixed`em. Yikes. That coulda gotten pretty nasty if I updated from my local files in the future.

**Pull request merged**
