### PR TITLE
Corrected errors from #2641

### PR DESCRIPTION
**Pull request by rmihailucian**
Corrected errors from #2641, now it should be ok. I would bring the system to preview in the next step, if everything goes well.

### CODE REVIEW

**Comment by si404** [comment]
I'm going to check this - looks like the errors are fixed.

**Comment by si404** [comment]
Yep, this works!

**Comment by rmihailucian** [comment]
Perfect, then I will also bring it to preview.

**Comment by si404** [comment]
That's already there with the previous pull - no need to do anything.

**Comment by michihdeu** [comment]
No, it wasn't.

**Pull request merged**
