### PR TITLE
CA US101 truncation, other CA and NM changes

### PR DESCRIPTION
**Pull request by ovoss**
Truncation and NM changes discussed on forum. Other fixes to usaca routes.

Updates items to be in separate pull request, once this one clears Datacheck.

### CODE REVIEW

**Comment by ovoss** [comment]
Datacheck failed: [356.9] ABORTING due to 1 errors:
1: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/NM/usanm/nm.nm572.wpt'

Closing pull request while I figure out what I did wrong. Might've been I didn't copy local changes to usanm .csv files. Will try again later.

**Comment by ovoss** [comment]
Indeed, it was the missing usanm .csv files. How do I add them to the branch, reopen the pull request, and do a new Datacheck run?

**Comment by rickmastfan67** [comment]
@ovoss there's the 'reopen and comment' button right below this text box beside the 'comment' button.  That's how you reopen a pull request.

As for fixing the usanm*,csv files, up at the top of this pull request, there's a link to the branch on the same line as the 'closed/open' icon.  Click the branch name there, and go into it and manually edit the files.  The changes will automatically show up in this request then.

**Comment by ovoss** [comment]
> As for fixing the usanm*,csv files, up at the top of this pull request, there's a link to the 
> branch on the same line as the 'closed/open' icon. Click the branch name there, and go into > it and manually edit the files. The changes will automatically show up in this request then.

But the usanm* files aren't in the branch at all, which is why Datacheck failed. Could try a drag and drop, but that didn't work the time I tried it, since it didn't put the files in the right folder (which isn't in the branch, either).

**Comment by jteresco** [comment]
It looks like the files are in the branch here on GitHub.  It sounds like it's easiest to make the needed fix within your branch right on GitHub.

**Comment by ovoss** [comment]
> It looks like the files are in the branch here on GitHub. It sounds like it's easiest to make the needed fix within your branch right on GitHub.

Unless I'm missing something, the usanm*.csv files aren't in the branch, only in the GitHub master, or my local copy of the master, or my desktop.

**Comment by rickmastfan67** [comment]
@ovoss the files are there.  I just loaded up the system section and did 'ctrl+f' and found them.

But if you're still having issues, here's the dirrect links to them:

[usanm.csv](https://github.com/TravelMapping/HighwayData/blob/CA-US101-truncation%2C-other-CA-and-NM-changes-/hwy_data/_systems/usanm.csv)
[usanm_con.csv](https://github.com/TravelMapping/HighwayData/blob/CA-US101-truncation%2C-other-CA-and-NM-changes-/hwy_data/_systems/usanm_con.csv)

**Comment by ovoss** [comment]
This seems to do the trick. Datacheck successful, ready to merge pull request for next site update.

I'll make separate pull request for corresponding Updates table entries.

**Comment by rickmastfan67** [comment]
Glad I was able to help you get that CSV issue dealt with @ovoss. :)

**Pull request merged**
