### PR TITLE
Serbia A4 and MT secondary routes

### PR DESCRIPTION
**Pull request by si404**
2016-02-02;Serbia;E80;Removed from B44 (now R259) and relocated onto A4
between 'BelaPal_W' and 'BelaPal_E'

### CODE REVIEW

**Comment by yakra** [comment]
Si, can you add a commit to systems.csv to change the line:

canab;CAN;Alberta Primary Provincial Highways;brown;4;preview
to
canab;CAN;Alberta Provincial Highways 1-216;brown;4;preview

I don't want to put in my own pull request and risk creating conflicts with the commits you have pending.

**Comment by si404** [comment]
@yakra - done

**Comment by yakra** [comment]
Thanks!

**Comment by mapcat** [comment]
hwy_data/KY/usaif/ky.i565fut.wpt

Don't think so. Just a governor's plan so far.

And can we leave the KY stuff to me for now?

Thanks.

**Comment by si404** [comment]
Re:KY I-565Fut
1) It was (I've removed it) just a placeholder file, with no connection to the HB database, and thus was doing no harm
2) I'm so used to KY having had no collaborator that it's become force of habit to see something KY and then act if I can
3) A Governor's plan is fairly official - I'd expect an AASHTO/FHWA application ASAP

I won't do it again.

**Comment by mapcat** [comment]
Cool. Thanks.

As I mentioned in the forum, I think signs are essential to calling it official. But I'll keep an eye on this and add the file when (if) necessary.

**Comment by jteresco** [comment]
Temporarily commenting out usamts from systems.csv because of 2 errors that prevent a site update from completing:

Route contains fewer than 2 points: mt.sr328 (1 total points)

No such file or directory: '../../../HighwayData/hwy_data/MT/usamts/mt.sr461.wpt

**Comment by jteresco** [comment]
BTW, I'd normally be able to track these down, but no time this evening and I wanted to get a site update with the other data chances and several list updates to go through before I call it a night.

**Pull request merged**
