### PR TITLE
Poland changes

### PR DESCRIPTION
**Pull request by si404**
I haven't checked to whether this would give a successful update as I still have no access to more than a web browser. It should work, but I can't say it for certain - I've made a few csv changes (pols, poldk)

### CODE REVIEW

**Comment by michihdeu** [comment]
I've synced hwy + user data and run data check since last night's update failed. However `DATA CHECK SUCCESSFUL`.

**Comment by jteresco** [comment]
Looks like the failure was from a change here.

<pre>ABORTING due to 2 errors:
1: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/POL/poldk/pol.dk016bar.wpt'
2: Route contains fewer than 2 points: pol.dk016bar (0 total points)</pre>

**Comment by jteresco** [comment]
Misnamed file, fixed.

**Comment by si404** [comment]
Thanks Jim and sorry. Odd that it didn't come up with michih's datacheck!

**Comment by michihdeu** [comment]
> Odd that it didn't come up with michih's datacheck!

I've started data check to early when syncing was not yet finished. However, I've waited till Github Desktop button did indicate being finshed. That's odd.

**Pull request merged**
