### PR TITLE
ENG

### PR DESCRIPTION
**Pull request by michihdeu**

### CODE REVIEW

**Comment by michihdeu** [comment]
@si404 

btw: Concurrency A1 with E road is broken in Scotland just east of Edinburgh b/n junction 115 and 116.

**Comment by si404** [comment]
Sure. I'll sort the concurrency break.

Also, how did you travel ENG M60 A626 14? 14 is westbound only. And also how did you jump to the M61 there without getting any of the A580. I think you travelled M60 A626 15, KeaSpr 1 2 and M61 2 M6. Yes it's a weird junction complex!

And how did you not clinch any M42 having turned off the M6Tol at (7A)M42? Yes, I am stalking you!

**Comment by michihdeu** [comment]
> Also, how did you travel ENG M60 A626 14? 14 is westbound only. And also how did you jump to the M61 there without getting any of the A580. I think you travelled M60 A626 15, KeaSpr 1 2 and M61 2 M6. Yes it's a weird junction complex!

yep, you're right! I was quite confused when browsing the points... I drove M60 clockwise.

> And how did you not clinch any M42 having turned off the M6Tol at (7A)M42? Yes, I am stalking you!

I stopped here because I didn't wanna add temorary points for one or two days only. I just stopped at this point. The next points are in today

**Comment by michihdeu** [comment]
btw: I've clinched irlm, nirm, niram, gbnm in sct, gbnam in sct - all motorways - but I won't clinch all motorways in England! Well, not now. LOL!

**Pull request merged**
