### PR TITLE
BiH

### PR DESCRIPTION
**Pull request by si404**
2016-09-08;Bosnia and Herzegovina;Gradski Autoput Sarajevo;bih.graautsar;New Route

### CODE REVIEW

**Comment by si404** [comment]
2016-09-08;Poland;;Drogowa Trasa Średnicowa;pol.dw902;New Route

**Comment by michihdeu** [comment]
:+1: I was about complain that the DW902 update entry is missing...

**Comment by michihdeu** [comment]
I agree that DTS is the only Polish eursf road.

**Comment by michihdeu** [comment]
@jteresco : DW902 line is wrong. There are 2 ";" b/n Poland and Dorgowa....
The line is currently not displayed on the update site.

**Pull request merged**
