### PR TITLE
Update and rename from chngd.g04w3.wpt to chngd.g0423.wpt

### PR DESCRIPTION
**Pull request by eeffaann**

### CODE REVIEW

**Comment by jteresco** [comment]
@eeffaann Be sure to discuss this over on the TM forum, thanks!

**Review by si404 — APPROVED** [review]
As far as I can see, changes look reasonable

**Comment by eeffaann** [comment]
I guess this is good to merge then @si404?

**Comment by jteresco** [comment]
I'm good to bring it in as long as datacheck has been run.

**Comment by eeffaann** [comment]
> I'm good to bring it in as long as datacheck has been run.

Oh how do you run it for a preview system & route, without updating it? Am I missing something...

**Comment by jteresco** [comment]
@eeffaann drop me an email (terescoj@gmail.com) and I will send more info (likely not today/tonight though).

**Comment by yakra** [comment]
I'll give it a go here on my laptop. Cloning; receiving objects 23% ..

**Comment by yakra** [comment]
`!!! DATA CHECK SUCCESSFUL !!!`

**Comment by michihdeu** [comment]
> > I'm good to bring it in as long as datacheck has been run.
> 
> Oh how do you run it for a preview system & route, without updating it? Am I missing something @jteresco ...

Are you aware of our [manual](https://travelmapping.net/devel/devel.php)? The rules and procedures are described there. You'll also find a link to the [data check](urlhttps://github.com/TravelMapping/DataProcessing/blob/master/SETUP.md)

**Pull request merged**
