### PR TITLE
czer deletion DO NOT MERGE UNTIL 2016-01-01

### PR DESCRIPTION
**Pull request by si404**
DO NOT MERGE until the new year.

Czechia is getting rid of it's R road (expressway) class, with most routes becoming D road (motorway).

2016-01-01;Czechia;R1 ((South) Praha;cze.d000;Route renamed D0 ((South) Praha)
2016-01-01;Czechia;R1 ((East) Praha;cze.d000epr;Route renamed D0 ((East) Praha)
2016-01-01;Czechia;R4 (Dobríš);cze.d004;Route renamed D4
2016-01-01;Czechia;R4 (Predotice);cze.d004pre;Route renamed D4Pre
2016-01-01;Czechia;R6 (Kladno);cze.d006;Route renamed D6
2016-01-01;Czechia;R6 (Bošov);cze.d006bos;Route renamed D6 (Bošov)
2016-01-01;Czechia;R6 (Karlovy Vary);cze.d006kar;Route renamed D6 (Karlovy Vary)
2016-01-01;Czechia;R7 (Slaný);cze.d007;Route renamed D7 (Slaný)
2016-01-01;Czechia;R7 (Chomutov);cze.d007cho;Route renamed D7 (Chomutov)
2016-01-01;Czechia;R10;cze.d010;Route truncated east end from I10/I35 junction to exit 71 and renamed D10
2016-01-01;Czechia;R35 (Liberec);;Route deleted
2016-01-01;Czechia;R35 (Opatovice nad Labem);cze.d035opa;Route renamed D35 (Opatovice nad Labem)
2016-01-01;Czechia;R35 (Mohelnice);cze.d035moh;Route renamed D35 (Mohelnice)
2016-01-01;Czechia;R35 (Olomouc);cze.d035;Route renamed D35 (Olomouc)
2016-01-01;Czechia;R43;;Route deleted
2016-01-01;Czechia;R46;cze.d046;Route renamed D46
2016-01-01;Czechia;R48 (Belotín);cze.d048bel;Route renamed D48 (Belotín)
2016-01-01;Czechia;R48 (Chlebovice);cze.d048chl;Route renamed D48 (Chlebovice)
2016-01-01;Czechia;R48 (Frýdek-Místek);cze.d048;Route renamed D48 (Frýdek-Místek)
2016-01-01;Czechia;R52;cze.d052;Route renamed D52
2016-01-01;Czechia;R55;cze.d055;Route renamed D55
2016-01-01;Czechia;R56;cze.d056;Route renamed D56
2016-01-01;Czechia;R63;;Route deleted

### CODE REVIEW

**Comment by si404** [comment]
Will need to remove the czer system entry in https://github.com/TravelMapping/HighwayData/blob/master/systems.csv but won't do that yet, as I don't want to create a conflict.

**Comment by si404** [comment]
Oscar, why did you delete this branch?

**Comment by ovoss** [comment]
It for some reason showed up in my GitHub desktop client as one of "my" 
branches, and it was swept up in my deleting all the dozens of branches (all 
but that one created by me) hanging off and cluttering up my local copy of 
the master. My client pointed out the branches that weren't only on my PC, 
and gave me the option of deleting non-local copies of those. I routinely 
did that, per a previous decluttering request.

My questions:

-- How in heck did "czer deletion" wind up in my desktop client in the first 
place, when it appears to have nothing to do with my work, and no other 
branches created by you or other users showed up in my desktop client's 
branch list? If it hadn't shown up as one of "my" branches, I wouldn't have 
included it in my branch decluttering.

-- Is there a reason why I shouldn't delete "czer deletion" locally on my 
PC, without removing the branch anywhere else? Now that I'm down to just 
that one branch, there's no pressing need for me to remove it even locally 
(especially with its probable disappearance in a few weeks), but still nice 
for me to clean the slate.

----- Original Message -----

**Comment by jteresco** [comment]
As a member of highway data managers, you have the ability to change pretty much anything.  We can all end up with copies of each others' branches and normally that's just fine - they're very lightweight and harmless.  In this case, I think you just were in a place that you were working directly on the master instead of your own copy/fork/whatever.

In any case, no harm done.

**Comment by si404** [comment]
This can be merged now! Note that I have added GBNA activation to it. I guess I need to write an update for that:

2016-01-01;United Kingdom;Great Britain A Roads;gbna;Added routes beginning with a 1, 6, 8 and 9.

I've also added to the system list the files added recently.

**Comment by jteresco** [comment]
I merged this and it's mostly file deletions.  Is that correct?

**Comment by si404** [comment]
Yes that's correct - it is mostly deletions of files moved elsewhere (which were added at previous dates to the new folders).

**Comment by jteresco** [comment]
Lots of errors here.  I have removed lots of extraneous blank lines in _con.csv files, no big deal at all.  The errors that might need some attention:

The wlft csv files have routes with wrft in the first column and routes begin wrf.  I have a check to make sure the first column matches the system name, so I need to know which is correct.

Others are likely missing files, extra/missing/malformed csv lines, or misspellings:

Could not find Route matching root cze.d006 in system czed.
No roots in _con.csv line [czed;D6;;Kladno;cze.d006]
Could not find Route matching root cze.d006bos in system czed.
No roots in _con.csv line [czed;D6;;Bošov;cze.d006bos]
Could not find Route matching root reu.n004a in system reun.
No roots in _con.csv line [reun;N4A;;;reu.n004a]
srba.spmn.Could not find Route matching root spm.n005 in system spmn.
No roots in _con.csv line [spmn;N5;;;spm.n005]
Could not find Route matching root spm.n006 in system spmn.
No roots in _con.csv line [spmn;N6;;;spm.n006]
Could not find Route matching root maf.n007 in system spmn.
No roots in _con.csv line [spmn;N7;;;maf.n007]
Could not find Route matching root spm.n008 in system spmn.
No roots in _con.csv line [spmn;N8;;;spm.n008]
Could not find Route matching root spm.n009 in system spmn.
No roots in _con.csv line [spmn;N9;;;spm.n009]
Could not find Route matching root spm.n010 in system spmn.
No roots in _con.csv line [spmn;N10;;;spm.n010]
Could not find Route matching root spm.n011 in system spmn.
No roots in _con.csv line [spmn;N11;;;spm.n011]
Could not find Route matching root spm.n2001 in system spmn.
No roots in _con.csv line [spmn;N2001;;;spm.n2001]
Could not find Route matching root spm.n2002 in system spmn.
No roots in _con.csv line [spmn;N2002;;;spm.n2002]
Could not find Route matching root spm.n2003 in system spmn.
No roots in _con.csv line [spmn;N2003;;;spm.n2003]
Could not find Route matching root spm.n2004 in system spmn.
No roots in _con.csv line [spmn;N2004;;;spm.n2004]
Could not find Route matching root spm.n2005 in system spmn.
No roots in _con.csv line [spmn;N2005;;;spm.n2005]

**Comment by jteresco** [comment]
I'm going to commit my blank line fixes.

**Comment by jteresco** [comment]
My blank line fixes are in.

**Comment by si404** [comment]
I've made a few other fixes that should have sorted it out.

**Comment by jteresco** [comment]
OK, good.  Are these pushed to master?

**Comment by si404** [comment]
I've redone them on master.

**Comment by jteresco** [comment]
Good, got much further.  Next error is that system frht is looking for files with a frht. prefix, but files in hwy_data/FRH/frht are all prefixed with fra.

**Comment by jteresco** [comment]
I'll be out for a couple hours - if there are further fixes I can try them out when I get back.

**Comment by jteresco** [comment]
Renaming the fra. files to frh. in hwy_data/FRH/frht

**Comment by jteresco** [comment]
It looks like the update will complete after those renames.  Should all be online in 20-30 minutes, barring other problems.

**Pull request merged**
