### PR TITLE
W end NH119

### PR DESCRIPTION
**Pull request by yakra**
ping @ajfroggie

### CODE REVIEW

**Comment by jteresco** [comment]
Seems I should wait for the corresponding change on the VT side, assuming VT 119 is moving to connect to the new bridge also.

**Comment by yakra** [comment]
It will be, yes, but I figure it's not like there'd be a DISCONNECTED_ROUTE to worry about.

**Comment by ajfroggie** [comment]
I'm waiting until I can get down there (hopefully later this month) to
verify whether 119 ends at 142 or if it'll be signed up to 5 as it ended at
5 before.  Haven't seen photos one way or the other and the literature is
unclear.

**Comment by yakra** [comment]
...Which is fine.

IMO this isn't a dealbreaker for changing the NH side now.
There's NH119 which does its thing in NH, and VT119 which does its thing in VT.
No need have them both the same level of up-to-date. It's not like this is a single US route crossing the border.

**Comment by jteresco** [comment]
Hate to break the graph connection, but I won't be making another archive set for a few weeks probably, so no big deal.  I'll bring this is now.

**Comment by yakra** [comment]
Ah yes, there is that.
Didn't think of it, somehow!

**Pull request merged**
