### PR TITLE
Forum fixes and labels

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by yakra** [comment]
Kingsway is just [one word](https://www.google.com/maps/@-34.031418,151.0780617,3a,15y,80.56h,92.52t/data=!3m6!1e1!3m4!1sM_tp9oYvesXdZ7x45LAOIg!2e0!7i13312!8i6656).
-> Kin

**Comment by yakra** [comment]
The rest looks good.

**Comment by michihdeu** [comment]
> Kingsway is just one word.

I would also call it KinWay. E.g. most German **street** names ending with **street** are just one word, e.g. Hauptstraße -> HauStr (Main Street)

**Comment by yakra** [comment]
But most English ones are not.

**Comment by michihdeu** [comment]
@si404 ? It's also interesting for the gbnb review....

**Comment by si404** [comment]
I'm waiting for you guys to argue it out before making a decision either way 😜. I agree with both your points (and made them myself when I saw the first comment about it) and am I stuck on the fence (thankfully not painfully) about it.

A grep on 'Kin', 'Que', 'KinWay' and 'QueWay' would be useful.

**Comment by michihdeu** [comment]
Both is fine to me as long as I don't have to change anything in my regions where I have one-word-names with XxxYyy abbreviations.

btw: google can't help me, what does 'grep on' mean? I think it has nothing to do with the computer program 😉

**Comment by michihdeu** [comment]
Let's discuss it on the forum: http://forum.travelmapping.net/index.php?topic=3361

**Comment by yakra** [comment]
> A grep on 'Kin', 'Que', 'KinWay' and 'QueWay' would be useful.

Matching any of these as an entire label, so no `KinSt`, etc.:
`yakra@epoch:~/tm/HighwayData/hwy_data$ grep -v '^+' */*/*.wpt | cut -f1 -d' ' | egrep ':Kin$|:Que$|:KinWay$|:QueWay$'`
AUS-NSW/ausa/ausnsw.a001syd.wpt:KinWay
BC/canbc/bc.bc007.wpt:Kin
COD/afrrtr/cod.rtr101.wpt:Kin
COD/afrtah/cod.tah3.wpt:Kin
COD/codn/cod.n001.wpt:Kin
COG/afrtah/cog.tah10.wpt:Kin
COG/afrtah/cog.tah3.wpt:Kin
COG/cogn/cog.n001.wpt:Kin
COG/cogn/cog.n002.wpt:Kin
COG/cogn/cog.n006.wpt:Kin
CRM/eure/crm.e97.wpt:Kin
CRM/rusa/crm.a252.wpt:Kin
CYP/cypa/cyp.a006.wpt:Kin
DEU-BW/deubwl/deubw.l0380a.wpt:Que
DEU-BW/deubwl/deubw.l0380.wpt:Que
DEU-BW/deubwl/deubw.l0508.wpt:Que
ENG/gbna/eng.a0059.wpt:QueWay
ENG/gbna/eng.a0059.wpt:KinWay
ENG/gbna/eng.a3072.wpt:Kin
ENG/gbna/eng.a4104.wpt:Kin
ENG/gbna/eng.a5027.wpt:KinWay
ENG/gbna/eng.a5036liv.wpt:QueWay
ENG/gbnb/eng.b0601.wpt:Kin
ENG/gbnb/eng.b4100.wpt:KinWay
ENG/gbnb/eng.b4183.wpt:QueWay
ESP-CT/espn/espct.n260aque.wpt:Que
FRA-ARA/fran/fraara.n122.wpt:Que
FRA-BRE/eure/frabre.e50.wpt:Que
FRA-BRE/fran/frabre.n012.wpt:Que
IRL/eurtr/irl.loopheaddr.wpt:Que
IRL/eurtr/irl.waw.wpt:Que
KEN/afrea/ken.ea001.wpt:Kin
KEN/afrtah/ken.tah10.wpt:Kin
KEN/afrtah/ken.tah8.wpt:Kin
KEN/kena/ken.a104.wpt:Kin
LKA/lkaa/lka.a015.wpt:Kin
MEX-DF/mexsf/mexdf.ctobic.wpt:Que
MOZ/afrrtr/moz.rtr35.wpt:Que
MOZ/mozn/moz.n001.wpt:Que
MT/usamts/mt.sr352.wpt:KinWay
NB/cannbc/nb.nb170.wpt:Que
NV/usanv/nv.nv445.wpt:QueWay
RUS/eure/rus.e22.wpt:Kin
RUS/rusm/rus.m007.wpt:Kin
SCT/eurtr/sct.angcoatr.wpt:Kin
SCT/eurtr/sct.morfirtr.wpt:Kin
SCT/eurtr/sct.nc500.wpt:Kin
SCT/eurtr/sct.nwhigtr.wpt:Kin
SCT/gbna/sct.a0085.wpt:Kin
SCT/gbna/sct.a0092.wpt:Kin
SCT/gbna/sct.a0834.wpt:Kin
SCT/gbna/sct.a0838.wpt:Kin
SCT/gbnb/sct.b0801.wpt:Kin
SCT/gbnb/sct.b0829.wpt:Kin
SCT/gbnb/sct.b0965.wpt:Kin
SCT/gbnb/sct.b0977.wpt:Kin
SCT/gbnb/sct.b0979.wpt:Kin
SCT/gbnb/sct.b1347.wpt:Kin
TUR/turd/tur.d885.wpt:Kin
TZA/tzat/tza.t001.wpt:Kin
UGA/afrea/uga.ea001.wpt:Kin
UGA/afrtah/uga.tah10.wpt:Kin

**Comment by ovoss** [comment]
> On November 28, 2019 at 9:50 PM Eric Bryant <notifications@github.com> wrote:
> 
> 
>         > > 
> >         A grep on 'Kin', 'Que', 'KinWay' and 'QueWay' would be useful.
> > 
> >     > 
>     Matching any of these as an entire label, so no KinSt, etc.:
>     yakra@epoch:~/tm/HighwayData/hwy_data$ grep -v '^+' */*/*.wpt | cut -f1 -d' ' | egrep ':Kin$|:Que$|:KinWay$|:QueWay$'
> 
>     BC/canbc/bc.bc007.wpt:Kin
> 
This one is for Kingsway.

> 
>     NV/usanv/nv.nv445.wpt:QueWay
> 
"Queen Way" here. No issue.

**Comment by yakra** [comment]
Broadway as BroWay on:
A505 / B656
-> Bro

**Pull request merged**
