### PR TITLE
Minato (port) national highways

### PR DESCRIPTION
**Pull request by denishanson**
Minato (port) national highways

### CODE REVIEW

**Comment by jteresco** [comment]
Making sure before I merge these in that there's been a datacheck run with these files in place.  @denishanson

**Comment by denishanson** [comment]
Will resubmit after testing

**Comment by denishanson** [comment]
The wpt files are directly copied from the WPT Editor, so I thought they
would be safe to submit.  There are no system level files yet, so nothing
has been hooked up.

I would like to request an account so that I can use a shell account on
TravelMapping's server to test my highway data changes/additions.  (I was
writing an email request for this when I saw your email.)

I have closed the pull requests.  I can resubmit after testing.

**Comment by jteresco** [comment]
I didn't catch that there was not a systems.csv entry yet, so no harm could be done.  I can pull these in if you'd like while we get you set up with a shell account on the server, just for safe keeping of the files.

**Comment by jteresco** [comment]
@denishanson please drop me an email with your preferred username so I can create the account and get back to you with some additional information.

**Comment by denishanson** [comment]
Is *kokudou* OK as a username?  It means national highways in Japanese.  If
not you can assign me whatever username you wish.

I have the files saved on google drive, so there is no need to pull them in
now.  Once I get the shell account verification working, I can resubmit
them plus their system files.

**Comment by jteresco** [comment]
Email me directly and we'll settle on a username and I can share more information about the account I'll create.

**Pull request closed without merging**
