### PR TITLE
datacheckfps cleanup

### PR DESCRIPTION
**Pull request by yakra**
Let's make sure everyone involved signs off on this before merging it in.
Ping @ajfroggie @ntallyn @ovoss @si404

### CODE REVIEW

**Comment by si404** [comment]
Fine by me

**Comment by ntallyn** [comment]
Is the Visible Distance cleanup removing lines that are no longer visible distance errors (and are thus just cluttering up the file)? If so, I'm good with it. If it's something else, I'm not quite sure what is being done.

**Comment by yakra** [comment]
Yes, these are no longer visible distance errors, and thus cluttering up the file. Either because...
* The routes' systems have been promoted to active, in which case VISIBLE_DISTANCE error are no longer flagged (this is the case in the usaga examples), or
* The root is no longer listed in the database

**Comment by jteresco** [comment]
Are we still waiting on any feedback on this one?

**Comment by yakra** [comment]
@ovoss I have removed ` sk.cirdr;SK11/16_A;SK11/16_C;;DUPLICATE_COORDS;(52.089454,-106.604635) `

**Comment by ajfroggie** [comment]
I can't see in my email what's going on or why I was pinged on this.
Haven't been able to log into Github lately, though admittedly haven't
tried much.  Been very busy with work the past couple months.

- A

**Comment by yakra** [comment]
Sent froggie a PM on the forum.

**Comment by yakra** [comment]
Froggie signed off on the changes via the forum.

**Pull request merged**
