### PR TITLE
Update updates.csv

### PR DESCRIPTION
**Pull request by ovoss**
Relates to changes proposed in PRs 7229-7233, for reroute of CA 58 in Bakersfield CA area.

### CODE REVIEW

**Comment by michihdeu** [comment]
@ovoss I guess that update entry no. 3 is not necessary but a duplicate of no. 2?

```
2024-02-20;(USA) California;CA 58;ca.ca058;In Bakersfield area, moved route from Hageman Rd, CA 43, Rosedale Hwy, and CA 99 between exits 24 and 26, to I-5 between exits 253 and 257, Stockdale Hwy, Westside Pkwy, and new Centennial Corridor link to CA 99/CA 58 interchange
2024-02-20;(USA) California;CA 58 (Westside Parkway);;Deleted route (merged into main CA 58)
2024-02-20;(USA) California;Westside Parkway;;Deleted route (merged into CA 58)
```

**Comment by si404** [comment]
@michihdeu ??? there's two different routes (1 usaca, 1 usasf) being deleted, so two similar-but-different updates entries
https://travelmapping.net/hb/showroute.php?units=miles&u=si404&r=ca.ca058wes
https://travelmapping.net/hb/showroute.php?units=miles&u=si404&r=ca.wespkwy

**Comment by ovoss** [comment]
A related issue: my pending pull requests delete ca.ca058wes and ca.wespkwy, both folded into the CA 58 mainline. However, the latter deletion is incomplete. PR # 7233 deletes the route file. However, GitHub's web interface doesn't include usasf's csv files, since it can't handle more than 1000 files, and the usasf (but not usaca) csv files got truncated off the file list. So I can't modify the usasf csvs to remove the lines for ca.wespkwy, and pull in those minor changes for tonight's site update.

**Comment by si404** [comment]
I clicked on a different .csv file and then manually edited the url:

https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/usasf.csv
https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/usasf_con.csv

**Comment by ovoss** [comment]
Thanx. I'm now editing the usasf csv files to remove Westside Parkway.

**Comment by ovoss** [comment]
> > @michihdeu ??? 
> I only saw the usaca csv file changes

The usasf csv changes are now in PRs 7235 and 7236.

**Pull request merged**
