### PR TITLE
I-70/I-76, PA 120, and PA 655 Point Revisions

### PR DESCRIPTION
**Pull request by Markkos1992**
https://forum.travelmapping.net/index.php?topic=6400.0

### CODE REVIEW

**Comment by yakra** [comment]
https://travelmapping.net/devel/manual/wayptlabels.php#multipledesignations

**Comment by yakra** [comment]
> because it would take hours for me just to debate what the

LOL I know what you mean.
Today I came across an area in Connecticut that could use some coord tweaks & potential new points to clean up the mapview.
After considering doing it this way, that way, the other way, graph connections, the manual, and what *is and is not* 1PPI, I said sod it all and went no-build other than exit numbers.

For cases like this I usually gravitate toward calling the route itself primary
* `OldUS202_Aub` on US202
* `ME4_Aub` on ME4
* `ME11_Aub` on ME11
* `ME100_Aub` on ME100

**Comment by Markkos1992** [comment]
Yeah, if this was under PennDOT jurisdiction, then it would be SR 0070 meaning that I should be using I-70 labels (which makes sense for the I-70/I-79 concurrency in Washington).  However, the PTC jurisdiction makes this very tricky.  I could go with I-76 labels based on the SR 7076 designation PennDOT gives it, but I have no clue if the PTC even recognizes that.

**Comment by rickmastfan67** [comment]
Well, IMO, since the exit numbers match I-76 mileage, that's the primary route.  That or MM's should be what decides stuff like this IMO, if they're posted that is of course.

https://maps.app.goo.gl/4hMikLiGST48ZLsf9

**Pull request merged**
