### PR TITLE
Various Europe Stuff

### PR DESCRIPTION
**Pull request by si404**
2016-01-05;France;Rocade Est du Calais;fra.rocest;New Route
2016-01-05;Lithuania;Kaunas - Klapieda Greitkelio;ltu.kauklagre;New
Route
2016-01-05;Lithuania;Vilnius - Kaunas Greitkelio;ltu.vilkaugre;New Route
2016-01-05;Lithuania;Vilnius - Panevezys Greitkelio;ltu.vilpangre;New
Route
2016-01-05;Spain;AC15;esp.ac15;New Route
2016-01-05;Ukraine;Avtostrada Kiev - Boryspil;ukr.avtkievbor;New Route
2016-01-05;Ukraine;Avtostrada Kharkiv - Dnipropetrovsk;ukr.avtkhadni;New
Route

### CODE REVIEW

**Comment by jteresco** [comment]
This is pulled in, but it looks like a bunch of extra zero-size files and a misplaced and misnamed csv file under ROU.

**Comment by si404** [comment]
There are a bunch of extra zero-sized files and a .misplaced (exactly where I want it at the moment - out of the way, but able to be seen for those seeking it) csv, sure, but it's much more than that. Even that commit is more than that - it's showing michih progress on something he told me Romanians were clamouring for before I go away for a week, hopefully saving me emails wondering why I haven't finished it and made it devel in the browser - I've not finished it, and it's not ready for the browser yet!

**Comment by michihdeu** [comment]
Si, I guess there's a misunderstanding. Maybe it's because of my bad English. Sorry!

You sent me a private message 6 months ago. You wrote that you are working on many systems, e.g. Estonian main roads and Macedonia M roads are complete, Maltese roads and Romanian DN roads are in development.

I asked why the "complete" systems are not online with "preview" status and why systems like "roudn" are not online with "devel" status.

------------------------------------------
Your systems (like the French, Serbian, Finnish one's) do all have "preview" status. There are other systems like "cansph" in BC which are incomplete but "devel" status which is ok IMHO. I could map my travels as accurate as it was possible. That was possible because I still remember my routes and there was highway data available. Once it will be "active" or "preview" I could complete my data (there's currently minimum one of my routes missing in highway data).

I minimum want to know which systems are in development. Systems one is working on! I got your private message once but didn't know anything about the advance. If systems like "roudn" had "devel" status I could check it out.
There's a list of regions (https://github.com/TravelMapping/HighwayData/wiki) but not about systems and their status, e.g. roudn "in development but not yet online; responsible Si"

No criticism, I just want to understand and contribute to the project!

---------------------------------------------------------

I've never requested to have hidden data online. I'd like to have
- (incomplete) data online like "cansph" with "devel" status and
- complete data online as "devel" if the developer has not yet checked the data online and
- complete data online as "preview" status if the developer has checked the data and others should check if they find issues to be fixed before it's going "active"

OR

- minimum a system overview with status.

The wiki article about regions with responsibles could be extended or systems.csv could be extended like "#usaky4;USA;Kentucky State Highways 1500-1999;brown;4;devel" (commented in development system)

Sorry, I started submitting list files 2,5 years ago, I'm not an old hand, not familar with all CHM rules et cetera.

Maybe my proposals are bad idea but... We are here to discuss :)

**Comment by michihdeu** [comment]
There's a minor bug in the update list ("0" missing):

2016-01-05;Spain;AC15;esp.ac15;New Route
-->
2016-01-05;Spain;AC15;esp.ac015;New Route

**Comment by michihdeu** [comment]
Not sure if this is the right thread for discussion but AC15 is not yet in service!

http://www.skyscrapercity.com/showpost.php?p=129661290&postcount=285

http://www.lavozdegalicia.es/noticia/coruna/arteixo/2015/12/28/pago-obras-retrasa-apertura-vial-langosteira/0003_201512H28C1992.htm

**Comment by si404** [comment]
AC-15 was shown as open on OSM and I thought that maybe it did open in December like planned and I missed the update.

As for roudn - I uploaded it to show willing for what you are proposing. I simply moved the folder from my unattached local folder into the Romanian folder in the Github repository folder. When I have time I'll sort out the .csv files, hash out what isn't ready yet (the blank files) or fill the blank files with filler (as oscar did with usaca) or the actual route, and then make it devel. As it currently stands, you can at least see the files, put them in the editor made a few months ago (see the data discussion thread, IIRC), and log your travels that way - call it 'alpha testing'. These files will become visible on the main site, but not this week, and probably not next.

**Comment by michihdeu** [comment]
OK.

**Comment by jteresco** [comment]
No problem from my perspective having the draft routes - just was making sure you hadn't committed some things you didn't mean to.  They're doing no harm (other than increasing the "unprocessed wpts" count, which really isn't any harm anyway).

**Pull request merged**
