### PR TITLE
chng complete

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by jteresco** [comment]
Going to pull this in and try it now.  Hopefully you'll be online to help take care of any problems I can't easily clear up.

**Comment by si404** [comment]
Thanks Jim

**Comment by jteresco** [comment]
chngz.g78 doesn't exist in the .csv, but we have this entry in the _con.csv .  What shoudl it be?

`chng;G78;;Baise;chngx.g78bai,chngz.g78`

**Comment by si404** [comment]
It should be in.

**Comment by jteresco** [comment]
I see the file there now, I'll add the needed entry to the .csv and see how it goes.

**Comment by jteresco** [comment]
Looks like a success.  I'll commit the updated csv and the site update should go through.

**Comment by si404** [comment]
sweet

**Pull request merged**
