### PR TITLE
ME26 truncation

### PR DESCRIPTION
**Pull request by yakra**
(USA) Maine ME 26: Truncated between the old southern end at Congress Street and the new end at Cumberland Avenue.

### CODE REVIEW

**Comment by yakra** [comment]
Wait, hold up; the Root is missing from updates.csv...

**Comment by yakra** [comment]
OK. Fixed updates.csv. I see that this pull request is now listing 3 commits instead of 2, and I can still see the older state of the file if I follow its link.
Hopefully GitHub is intelligent enough to pull the latest revision of the file...

**Comment by jteresco** [comment]
I'll need to resolve a conflict in updates.csv to merge this, but that's going to happen as multiple people keep adding entries to the top of that file.  I might suggest an alternate where we have a directory of smaller updates files, one per update set, but let's not worry about that right now.  I'll plan to merge this later unless anyone objects.

**Comment by rickmastfan67** [comment]
Or maybe we flip the 'updates.csv' file and add new entries to the end?

**Comment by yakra** [comment]
Either way there's the potential for conflict: Bob's copy has changes that Pete's copy doesn't have; Pete's copy has changes that Bob's copy doesn't have…

**Comment by jteresco** [comment]
The merging will work well in most cases - it's just these files like updates.csv that multiple people will want to be editing in the same position that causes problems.  I'll take care of this one now.

**Comment by jteresco** [comment]
I think this one's set.  Will be running an update soon and we'll see for sure.

**Comment by ovoss** [comment]
Would it be OK, to help with this problem, for me to wait a few days between 
pull requests for new/updated route files and putting in one pull request 
for updates.csv that covers multiple route file changes? I have two issues 
outstanding that will require Updates entries, and more not yet in the 
system, which could result in my rapid-fire submission of multiple route 
file updates. I hope to address my two open issues tomorrow before I go 
offline for the weekend, with others not until next week, but I'd prefer to 
take care of a batch of Updates entries at once next week.

Oscar

----- Original Message -----

**Comment by jteresco** [comment]
I think even better might just be for now to email the updates entries to me to add directly to the master copy when I pull changes in.  There should pretty rarely be conflicts otherwise.  Maybe occasionally on usai.csv or the other multi-region systems.

**Comment by rickmastfan67** [comment]
Or maybe just add the text in the pull request for that file so you can just copy and paste it Jim?

**Comment by yakra** [comment]
> Or maybe just add the text in the pull request for that file so you can just copy and paste it Jim?

**Comment by yakra** [comment]
> Or maybe just add the text in the pull request for that file so you can just copy and paste it Jim?
IAWTP

**Comment by yakra** [comment]
> Or maybe just add the text in the pull request for that file so you can just copy and paste it Jim?

IAWTP

**Comment by jteresco** [comment]
Yes, that would also work.

**Pull request merged**
