### PR TITLE
Dec 20th Motorway openings

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by michihdeu** [comment]
I need to modify updates.csv too and don't wanna risk getting any problem. Can I merge this in?

**Comment by si404** [comment]
I'm not making any more. Brothers flight was delayed so I got time I didn't expect before  I lose my study for a week, allowinge to get today's stuff added

**Comment by michihdeu** [comment]
```
1: Could not find Route matching root idn.jtmk in system idnjt.
2: No roots in _con.csv line [idnjt;JTMK;;Jalan Tol Mojokerto - Kertosono;idn.jtmk]
3: Could not find Route matching root ind.jtpppas in system idnjt.
4: No roots in _con.csv line [idnjt;JTPP;;Jalan Tol Pasuran - Probolinggo;ind.jtpppas]
5: Duplicate root in route lists: idn.jtbs
6: Duplicate root in con_route lists: idn.jtbs
7: Check FAILED: 48293 routes != 48291 connected route roots.
8: route idn.jtpppas not matched by any connected route root.
9: route pol.s007jed not matched by any connected route root.
10: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/IND/idnjt/idn.jtbj.wpt'
11: Route contains fewer than 2 points: idn.jtbj (0 total points)
12: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/IND/idnjt/idn.jtbs.wpt'
13: Route contains fewer than 2 points: idn.jtbs (0 total points)
14: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/IND/idnjt/idn.jtcn.wpt'
15: Route contains fewer than 2 points: idn.jtcn (0 total points)
16: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/IND/idnjt/idn.jtjmjom.wpt'
17: Route contains fewer than 2 points: idn.jtjmjom (0 total points)
18: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/IND/idnjt/idn.jtks.wpt'
19: Route contains fewer than 2 points: idn.jtks (0 total points)
20: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/IND/idnjt/idn.jtkssur.wpt'
21: Route contains fewer than 2 points: idn.jtkssur (0 total points)
22: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/IND/idnjt/idn.jtmm.wpt'
23: Route contains fewer than 2 points: idn.jtmm (0 total points)
24: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/IND/idnjt/idn.jtnk.wpt'
25: Route contains fewer than 2 points: idn.jtnk (0 total points)
26: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/IND/idnjt/idn.jtss.wpt'
27: Route contains fewer than 2 points: idn.jtss (0 total points)
28: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/IND/idnjt/idn.jtsk.wpt'
29: Route contains fewer than 2 points: idn.jtsk (0 total points)
30: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/POL/pols/pol.s007jed.wpt'
31: Route contains fewer than 2 points: pol.s007jed (0 total points)

```

**Comment by michihdeu** [comment]
@si404 have you run data check? Is it an issue caused by me (all routes are yours though...)

**Comment by michihdeu** [comment]
idnjt_con.csv has 53 lines but idnjt.csv only 52.

**Comment by michihdeu** [comment]
Seems like you've deleted this line by accident (forgot copying):

> idnjt;IDN;JTMK;;;Jalan Tol Mojokerto - Kertosono;idn.jtmk;

I'll change it and run data check again.

**Comment by michihdeu** [comment]
OMG..... Many, many csv trouble...

**Comment by si404** [comment]
I was rushing to get it done. Just comment out systems if you don't want to fix, and I'll fix it when I can.

**Comment by michihdeu** [comment]
Just one left. idn.jtbs is twice in csv but only one wpt file.

**Comment by michihdeu** [comment]
`Data check successful!`

India and Indonesia cannot stop Bavaria! (-:

**Pull request merged**
