### PR TITLE
espcn and espmd activation

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by michihdeu** [comment]
I think there's an issue. I'll run data check...

**Comment by si404** [comment]
I ran it three times - after each of the last three commits. All successful. And just now 

[335.8] Processed 348 highway systems.
Processed 52875 routes with a total of 861612 points and 808737 segments.
WaypointQuadtree contains 39137 total nodes.
!!! DATA CHECK SUCCESSFUL !!!
Finish: 2019-09-17 11:25:56.734435
Total run time: [335.9]
Tue Sep 17 11:26:07 EDT 2019
datacheck.sh: complete

**Comment by michihdeu** [comment]
yep, it's fine. I was confused because you had extended the ESP-CN/espa files.... you deleted them later. Sorry.

**Comment by si404** [comment]
No worries - it was so I could write the updates entries, and with receipts that that is all that changed.

**Pull request merged**
