### PR TITLE
Patch 228

### PR DESCRIPTION
**Pull request by rmihailucian**
TUR O33 added

### CODE REVIEW

**Comment by michihdeu** [comment]
@rmihailucian O33 should get a 'city' name in both csvs.
What's the story behind calling the pull requests 'Patch xxx'?

**Comment by rmihailucian** [comment]
@michihdeu done the city name. The pull request name is just the default name given by GitHub.

**Comment by michihdeu** [comment]
@rmihailucian it's just a name and not very important but a short description would be nice so that other hwy data manager have a little feeling what happens.

I'll merge in and run data check (because I guess you haven't done yet?)

**Comment by michihdeu** [comment]
2: Duplicate root in con_route lists: tur.o033
5: route tur.o033man not matched by any connected route root.

I'll look into it....

**Pull request merged**
