### PR TITLE
DE: Middletown and some other bits

### PR DESCRIPTION
**Pull request by yakra**
Probably left over from before AltLabels were implemented on CHM.
It would have survived Tim's automated conversion process due to different coords from `DE15/299`.

### CODE REVIEW

**Comment by yakra** [comment]
fixes broken multiplex with DE15,DE299

**Comment by ovoss** [comment]
The southern US 301/DE 15/DE 299 junction seems to have moved a little to the southwest, perhaps as a byproduct of the US 301 tollway project now under construction (which I saw over the weekend). Doesn't really need to be fixed now, could wait until US 301 is relocated to the new tollway.

**Comment by yakra** [comment]
I was thinking of having a go at making some related changes anyway.
Stuff will get relabeled; DE15_N may even reappear. Not sure yet.
Let's hold off on merging this in.

**Comment by yakra** [comment]
**US301:**
`DE299_W` -> `*OldDE299`
`DE15/299_S` added
`DE15_S` +-> `*OldDE15`
`DE15/299` +-> `DE15/299_N`
`OldSumBRd` -> `OldSBRd` (labeling conventions)
`BetChuRd` +-> `DE15`

**DE15:**
`CriHolRd` replaced with `ChuHillRd` (parallel freeway interchange; improved shaping)
`US13/13Alt` +-> `US13_N` (US13Alt does not leave multiplex)
`*OldDE15_A` & `WesDr` added
`HazRd_W` -> `*OldDE15_B`
`BraRd` -> `BreRd`
`StAnnCRd` replaced with `*OldDE15_C`
new `StAnnRd` roundabout
`ChaPriPark`, `*OldDE15_D`, `US301_S` added (If DE15 is relocated to new US301 & spur hwy, `US301/299` can be used for new interchange)
`US301/299_S` +-> `*OldDE15_E`
`BunHillRd_W` recentered in roundabout
`+X1` replaced with `ChuRd`

> Removed from a demolished roadway directly connecting waypoints *OldDE15_A and *OldDE15_B, and relocated onto a northwesterly relocation of Wyoming Mill Rd and Hazlettville Rd via an intersection with Westover Dr. Removed from a demolished roadway directly connecting *OldDE15_C and the entrance to Charles E. Price Memorial Park, and relocated eastward via a roundabout at St Annes Church Rd. Removed from a demolished roadway directly connecting waypoints *OldDE15_D and *OldDE15_E, and relocated onto a northwesterly relocation of Levels Rd and Middletown Warwick Rd (US 301).

**DE71:**
`OldSumBRd` -> `OldSBRd` (labeling conventions)
`BetChuRd` +-> `DE15`. Minor adjustments once spur hwy interchange is constructed.

**DE299:**
`*OldDE299` added
`+X904430` added (for user-friendly graph/mapview)
`+x301` added (placeholder for future US301 interchange)
`US301_S` moved to relocated Levels Rd (label in use; no adverse .list impact)
`DE15_S` +-> `OldDE15`

> Removed from a demolished east-west section (approx. 0.1 mi) of Warwick Rd and US 301, and relocated onto a northerly extension of Warwick Rd, parallel to and west of the under-construction US 301 divided freeway, and Levels Rd between a waypoint labelled *OldDE299 and US 301.

**DE896:**
`JamCorRd` added
`BetChuRd` +-> `DE15`. Minor adjustments once spur hwy interchange is constructed.

**Pull request merged**
