### PR TITLE
usaky4 misc fixes

### PR DESCRIPTION
**Pull request by mapcat**
For systemupdates:

2016-05-11;(USA) Kentucky;usaky4;Kentucky State Highways 1500-1999;preview

### CODE REVIEW

**Comment by jteresco** [comment]
@mapcat It looks like there's a conflict here.  Is it possible you didn't merge in my commenting out of usaky5 from systems.csv before putting in this request?

**Comment by jteresco** [comment]
Should be good now.

**Comment by mapcat** [comment]
Sorry, I thought I put the # in front of the line in systems.csv. Did I need to add that somewhere else?

**Comment by jteresco** [comment]
I think it's because I added it and committed, then you made a change in the same part of the file.  Maybe someone else who regularly needs to update their branches to make pull requests can explain the process.

**Pull request merged**
