### PR TITLE
Reroute, add additional waypoint (WA 92)

### PR DESCRIPTION
**Pull request by compdude**
Rerouted along Quarry Road (Granite Falls Bypass) with three new waypoints added; also added one at 84th St NE.

### CODE REVIEW

**Comment by yakra** [comment]
* GraFalByp is in use, and should be included as an AltLabel for GraFalHwy.
* GraAve, also in use, could also be included as an AltLabel for GraFalHwy, so as not to break existing list files. Anyone using this point would have to have another point farther west as the other point in their list file, and would thus not have anything erroneously mapped that they have not actually traveled.

Otherwise, looks good. Once the above is sorted, updates text could read something like
2016-11-26;(USA) Washington;WA 92;wa.wa092;East end removed from Granite Falls Highway between Quary Road and Granite Avenue, and relocated onto Quarry Road between Granite Falls Highway and Mountain Loop Highway.

**Comment by jteresco** [comment]
Will also hold off on this one until those additional changes are put in.

**Comment by compdude** [comment]
Okay, I added in the alt labels. Hopefully I did it right...

**Comment by yakra** [comment]
The AltLabels look good. Merging this one in. I'll leave the updates text, in my previous comment, for @jteresco to handle.

**Pull request merged**
