### PR TITLE
usavt activation

### PR DESCRIPTION
**Pull request by yakra**
Let's allow a little time for discussion before merging this in.

I've made the commits with a few changes to the files as received from Froggie, specifically:
**VT15A:** VT100His -> VT100.
**VT16:** +x01 & +x02 -> QuaRd & NGreRd in situ.
**VT100AltMor:** Since it's a child route, VT15/100 -> VT100_N
**VT242:** put the old AccRd point back in for those who've used it in the past. Indeed, it's already in use in the preview system.

### CODE REVIEW

**Comment by jteresco** [comment]
My internet is spotty this morning, but I'm going to pull this in and see if I can get an update to go through.

**Comment by yakra** [comment]
Well, that was *a little* time for discussion! ;)

**Comment by jteresco** [comment]
Can you tell I think this was was delayed way too long?

Wait, stop everything!  What about those town-maintained sections?!

**Comment by jteresco** [comment]
Didn't even read your message about "let's leave a little time"...

**Comment by yakra** [comment]
Grin grin grin!
> Can you tell I think this was was delayed way too long?
I certainly agree there.

I just don't want Froggie to feel like I'm stepping on his toes with my changes to his changes.

**Comment by jteresco** [comment]
In any case, I can kill the site update and wait a bit if you'd like.

**Comment by yakra** [comment]
Nah, that's fine. Let's proceed with the update.
The roadgeek world has waited long enough!

**Comment by jteresco** [comment]
This could take some time anyway.  The file upload to update the DB is blazing along at 0.0 Kbps...

**Pull request merged**
