### PR TITLE
PAK+SCT+ENG+fixes

### PR DESCRIPTION
**Pull request by si404**

### CODE REVIEW

**Comment by michihdeu** [comment]
@si404 you've removed updates.csv entries for FRA-IDF, FRA-ARA, DEU-NW, DEU-BY, CO, PA and WY! I don't know why it happened... Maybe you should directly pull your changes when editing updates.csv

@jteresco @yakra what do you thin? Any idea what went wrong? Do we need one updates.csv file per region or per contributor? Or a check during site update..... dunno.....

**Comment by si404** [comment]
I know what happened. I forgot to close and reopen updates.csv over the sync up with the master branch. I'll readd.

**Comment by michihdeu** [comment]
thx

**Comment by yakra** [comment]
> I forgot to close and reopen updates.csv over the sync up with the master branch.

I use the pluma text editor. When a file has been saved by another program while I have it open to edit, pluma alerts me & gives me the opportunity to reload or cancel. Comes in handy.

**Comment by michihdeu** [comment]
N++ does also alert 😄

**Comment by yakra** [comment]
Notepad++?
A fine program; I used it back in my Windows days. Even installed it on my mom's machine.

**Pull request merged**
