### PR TITLE
US66 Historic in New Mexico

### PR DESCRIPTION
**Pull request by si404**
ping @oscar

### CODE REVIEW

**Comment by yakra** [comment]
It appears that old 66 is on the frontage road, not I-25 itself.

**Comment by jteresco** [comment]
Will wait for the word that this is good to go before merging in.

**Comment by ovoss** [comment]
If so, should the historic route be using I-25(xx) waypoints?

**Comment by si404** [comment]
I've changed the I-25(xx) waypoint labels on the points on the frontage roads.

**Comment by si404** [comment]
As I've fixed the issue @ovoss raised, I'm going to merge this. Should there be any further issues, they can be dealt with in a further pull.

**Pull request merged**
