### PR TITLE
HUN F260, F222 and ROU DN76B

### PR DESCRIPTION
**Pull request by rmihailucian**
new national roads in HUN and ROU

### CODE REVIEW

**Comment by jteresco** [comment]
Looks like we forgot datacheck:

<pre>
[5.2] ABORTING due to 1 errors:
1: [Errno 2] No such file or directory: '/fast/home/terescoj/travelmapping/HighwayData/data/ROU/roudn/rou.dncora.wpt'
Thu Aug  1 22:40:31 EDT 2024
</pre>

**Comment by jteresco** [comment]
Removing that route from the csvs and trying again.

**Comment by jteresco** [comment]
Looks like it's working.  The csv file entries should be restored when the dncora wpt file is added.

**Comment by si404** [comment]
The route was renamed, so the .csv line doesn't need readding, save maybe as an AltRouteName for DNVO1Z. There was no update entry, and I would have thought it would need that. And while that's being adding, the typo in the below line should be fixed.

> 2024-08-01;Romania;DN**6**6B;rou.dn76b;New Route

**Comment by rmihailucian** [comment]
Did the fixes, should come with the next update.

**Pull request merged**
