### PR TITLE
GA route updates

### PR DESCRIPTION
**Pull request by ntallyn**

### CODE REVIEW

**Comment by jteresco** [comment]
Not sure why all those usausb.csv and usausb_con.csv changes would be showing up here.  It doesn't seem we should have a commit with all of those merged into the master.  Holding off until others can verify that this is all good to go.

**Comment by jteresco** [comment]
I looks a little more myself, and we definitely don't want those changes to usausb's csv files.  They're undoing recent changes.

**Comment by ntallyn** [comment]
I'll see what I can figure out with those, but I made a fresh fork last night and manually added/removed the handful of routes in GA.

**Comment by ntallyn** [comment]
Should be fixed now.

**Comment by jteresco** [comment]
I think it's good.  Bringing it in.  Thanks.

**Pull request merged**
