### PR TITLE
extension of M1610

### PR DESCRIPTION
**Pull request by neroute2**
only changes to existing files (compared to the Mexico2 pull request) so no need to run datacheck

### CODE REVIEW

**Comment by neroute2** [comment]
These three pulls should be run from oldest to newest so each only has the files changed for it and not the ones for the previous pulls.

**Comment by michihdeu** [comment]
@neroute2 I think that some 30% of your links are broken. Please check.
e.g.
https://travelmapping.net/hb/showroute.php?r=mexgto.mex110d
https://travelmapping.net/hb/showroute.php?r=mexemex.emex007d

unfortunately, there is no automated check yet: https://github.com/TravelMapping/DataProcessing/issues/62

**Comment by neroute2** [comment]
> @neroute2 I think that some 30% of your links are broken. Please check. e.g. https://travelmapping.net/hb/showroute.php?r=mexgto.mex110d https://travelmapping.net/hb/showroute.php?r=mexemex.emex007d
> 
> unfortunately, there is no automated check yet: [TravelMapping/DataProcessing#62](https://github.com/TravelMapping/DataProcessing/issues/62)

Both of those are deleted (renamed) routes...

**Comment by michihdeu** [comment]
@neroute2 If the route was renamed, it should link to the new route. If it was fully removed from HB, the field should be empty.

**Comment by neroute2** [comment]
That makes sense. Will fix.

**Comment by michihdeu** [comment]
@neroute2 One of the 2024-04-30 update entry link is still broken: mexbcs.mex0019d

**Pull request merged**
