### PR TITLE
TUR changes

### PR DESCRIPTION
**Pull request by rmihailucian**
@michihdeu please perform datacheck on this one

### CODE REVIEW

**Comment by michihdeu** [comment]
@rmihailucian I'll run it now. Have you already had a change to check [this](https://forum.travelmapping.net/index.php?topic=5870.msg36074#msg36074)? Can I activate tursf?

**Comment by michihdeu** [comment]
@rmihailucian you missed the E87 update entry.

**Comment by michihdeu** [comment]
@rmihailucian the D883 update entry is also missing

**Comment by rmihailucian** [comment]
@michihdeu corrected, tursf can be also activated

**Pull request merged**
