### PR TITLE
turd -> preview

### PR DESCRIPTION
**Pull request by rmihailucian**

### CODE REVIEW

**Comment by michihdeu** [comment]
@rmihailucian you've added something wired to systems.csv.

`cantch;CAN;Trans-Canada Highway;red;2;activehttps://github.com/rmihailucian/HighwayData/network/members`

The main routes of D180, D350, D430, D877, D955 and D975 need 'city' entries.

**Comment by rmihailucian** [comment]
Yes, run it. Tottally comical the cantch line addition...Didn't do anything in that part of the file...

**Comment by rmihailucian** [comment]
Corrected also the .csvs now, added Main for the specified routes.

**Comment by michihdeu** [comment]
I didn't mean that you should enter 'Main' but that the main route needs a city entry. I haven't checked the routes though. If the routes with real city names are quite short (especially if they are branches) it's fine but if both routes are _long_ and just split because the route is interrupted, the main route should also get a real city name.

**Comment by si404** [comment]
Doesn't have to be perfect now, it just has to work. I'm going to pull it and see if it creates errors.

**Comment by si404** [comment]
Having got rid of the question mark at the beginning of turd_con.csv I found the following errors:

1: Could not parse systems.csv line:

2: Duplicate root in route lists: tur.d685
3: Duplicate root in con_route lists: tur.d685
4: Duplicate list name: TUR D550
5: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/TUR/turd/tur.d330mug.wpt'
6: Route contains fewer than 2 points: tur.d330mug (0 total points)
7: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/TUR/turd/tur.d330yes.wpt'
8: Route contains fewer than 2 points: tur.d330yes (0 total points)
9: [Errno 2] No such file or directory: '../../../HighwayData/hwy_data/TUR/turd/tur.d430ova.wpt'
10: Route contains fewer than 2 points: tur.d430ova (0 total points)

1's a double blank line at the end of the file (I removed one from turd_con.csv when I got rid of the question mark at the beginning, so remove that one too).
5&6, 7&8, 9&10 are the same errors expressed in two different ways.

**Comment by jteresco** [comment]
Looks like this shouldn't have been pulled in.  Still getting errors.  Please run data check before submitting pull requests.  I needed to make tonight's site update a quick one and now it's not.

**Comment by si404** [comment]
Sorry Jim, I pulled it in to stop getting emails and then ran datacheck to see if it worked, in the expectation that the errors would be fixed last night given the ping-pong that was happening before I did this. They weren't fixed.

**Comment by michihdeu** [comment]
You can unsubscribe getting emails if discussion is annoying you.

**Comment by rmihailucian** [comment]
Sorry, I wasn't online yesterday night, so I didn't see the comment from si404, with the errors, otherwise I would have corrected them. I appologize for the inconvenience. The problem is that I ran datacheck, and received datacheck succesfull message...

**Comment by michihdeu** [comment]
Datacheck should output this kind of error!?! @jteresco @yakra

**Comment by jteresco** [comment]
@rmihailucian you'll get used to the process.  @si404, @michihdeu can you help get him going on the best way to do all this?

**Pull request merged**
